OdyseeTeam/odysee-frontend

ui/scss/component/_livestream.scss

Fix livestream player height cut-off in certain zoom levels

---

.github/ISSUE_TEMPLATE/--say-thank-you.md
README.md

Removing some functionalities for the LBRY desktop apps on readme, to separate odysee and lbry.
</details>

Readme fixes

---

ui/component/claimPreview/view.jsx
ui/component/claimPreviewReset/index.js
ui/component/claimPreviewReset/view.jsx
ui/constants/livestream.js
ui/scss/component/_claim-list.scss
ui/scss/component/claim-preview-reset.scss

WIP: live stream kill switch

---

ui/component/commentCreate/view.jsx
ui/component/walletSendTip/view.jsx

bugfix persisted state issue

---

ui/component/walletSendTip/view.jsx

Smarter tab selection functionality

---

ui/component/common/markdown-preview.jsx

Issue Number: Closes #234
Also fixed the blockquote filling the whole message content if submitted first in the message
</details>

[Markdown] Fixes Quote and Fixes Images not showing

---

flow-typed/Comment.js
ui/component/channelBlockButton/view.jsx
ui/component/claimMenuList/index.js
ui/component/claimMenuList/view.jsx
ui/component/commentMenuList/view.jsx
ui/modal/modalBlockChannel/index.js
ui/modal/modalBlockChannel/view.jsx
ui/redux/actions/comments.js

As hinted during your request, it currently does nothing, right?  I do see some code using it in commentron, though.
But confirmed that it does not remove the comment.

Block: pass comment ID for deletion when being blocked.

---

ui/component/commentMenuList/view.jsx

Allow admins to delete comments as well.

---

ui/component/walletTipAmountSelector/view.jsx

Issue Number: closes #254
</details>

Fix string

---

package.json
webpack.base.config.js

Enable BundleAnalyzerPlugin + remove 'yarn analyze'

---

static/app-strings.json
ui/component/publishFile/view.jsx
web/setup/publish-v2.js

"There was a problem with your upload. Please try again."
The file has been uploaded ... one last hurdle.
See commit messages.

tus: Attempt to fix `notifiy` connection failures

---

ui/component/channelDiscussion/view.jsx
ui/component/livestreamLayout/view.jsx
ui/component/notification/view.jsx
ui/page/file/view.jsx
ui/page/livestream/view.jsx
ui/page/ownComments/view.jsx

~300KB savings in `ui.js` size (production, uncompressed). Mostly coming from the emoji library.

Lazy-load comment components

---

flow-typed/publish.js
ui/redux/reducers/publish.js
web/setup/publish-v2.js

2 TUS fixes

---

ui/component/fileRender/view.jsx
ui/component/fileRenderFloating/view.jsx
ui/component/viewers/videoViewer/view.jsx

Remove desktop video start time analytics

---

ui/component/viewers/videoViewer/internal/ads.js
ui/component/viewers/videoViewer/internal/videojs.jsx
ui/component/viewers/videoViewer/view.jsx

Clean up the sidebars ads code a bit, don't show ads on embedded content

Clean up the sidebars ads code a bit, don't show ads on embedded content

---

ui/page/livestream/view.jsx

reverse livestream status check

---

web/src/livestreaming/long-polling.js

Adjust livestream interval to 30 seconds

adjust livestream interval

---

ui/component/channelMentionSuggestions/index.js
ui/component/fileSubtitle/view.jsx
ui/component/fileTitleSection/index.js
ui/component/fileTitleSection/view.jsx
ui/component/fileViewCount/index.js
ui/component/fileViewCount/view.jsx
ui/component/livestreamComments/index.js
ui/component/livestreamComments/view.jsx
ui/constants/livestream.js
ui/redux/selectors/comments.js
ui/redux/selectors/livestream.js
ui/redux/selectors/subscriptions.js

Incremental livestream performance fixes

---

ui/component/claimUri/index.js
ui/component/subscribeButton/index.js
ui/page/invited/index.js
ui/redux/selectors/claims.js

Fix url selectors

---

ui/redux/reducers/claims.js

Heavy selectors are still recalculating even when the new claim object was already fetched and contains no new info.
Turns out I only handled it for Content claim, and missed the optimization when fetching Channel and Collection claims, as well as in other claim reducers.
Hunt down the remaining unoptimized pieces. Also added a wrapper to make things clearer.
`is_my_output` will still invalidate when going from `undefined` to `true|false`.  Since we need to store it, we have no choice but to invalidate.  We do prevent invalidating by ignoring the transition from `true|false` to `undefined`, though.

Hunt down remaining claim-invalidation

---

extras/lbryinc/index.js
extras/lbryinc/redux/actions/cost_info.js
extras/lbryinc/redux/selectors/cost_info.js
ui/component/claimInsufficientCredits/index.js
ui/component/embedPlayButton/index.js
ui/component/fileActions/index.js
ui/component/fileDownloadLink/index.js
ui/component/filePrice/index.js
ui/component/fileRenderFloating/index.js
ui/component/fileRenderInitiator/index.js
ui/component/fileRenderInline/index.js
ui/component/fileTitleSection/index.js
ui/page/embedWrapper/index.js
ui/page/file/index.js
ui/redux/actions/content.js
ui/redux/actions/file.js
ui/redux/selectors/claims.js
ui/redux/selectors/content.js

no memo required since they are just directly accessing the store.

Cost Info selector fixes 

---

ui/page/report/view.jsx

https://odysee.com/$/report
Was still linking to lbry-desktop.
also maybe a better name could be Feedback page?

[Report Page] Fix GitHub URL and improve strings

---

ui/component/app/view.jsx
ui/component/sideNavigation/view.jsx
ui/component/viewers/videoViewer/internal/videojs.jsx
web/component/ads/view.jsx
web/component/footer.jsx
web/src/html.js

Adds GDPR support and implements the window.__tcfapi API requested by Aniview

Adds GDPR support 

---

web/component/browserNotificationSettings/use-browser-notifications.js

#85 log "user enabled browser notifications"
----
@dan-peterson, is this the best place to do it?

GA: browser notification subscription

---

ui/component/app/view.jsx

Don't run the script if localStorage is not available

Hotfix embed error

---

ui/component/app/view.jsx

Reverts OdyseeTeam/odysee-frontend#368

Revert "Don't run SecurePrivacy on iframes"

---

ui/component/app/view.jsx

@tzarebczan, I couldn't find the `missing }` error ... tried embeds on both external sites and Posts.
This is a restore of this PR + some linting.

Restore "don't run SP script on iframe (368)" + lint/format

---

ui/scss/component/_main.scss
ui/scss/component/section.scss

Minor tweak to reduce the super large left-right margins in mobile.

Settings Page: maximize width usage in mobile

---

package.json
ui/component/viewers/videoViewer/internal/videojs.jsx
yarn.lock

required by https://embed.ly/providers/new
- Player.js IFrame Compatibility Tester: http://playerjs.io/test.html?url=https%3A%2F%2Fsalt.odysee.com%2F%24%2Fembed%2Fforza-horizon-5-bugatti-divo-1500%2Fb3cb4c4e20b560472a73be32025e697b1a3c3265

add Player.js Support

---

ui/page/home/view.jsx
ui/scss/component/_ads.scss
web/component/ads/view.jsx

Adding an ad to the most bottom right fully visible card, can be used to add ad-cards to the end of categories etc in the future

Add ad to the homepage as a card

---

extras/recsys/recsys.js

Fixes my last fix to the recsys endpoint, which literally undid itself.

FIX recsys endpoint fix

---

ui/component/claimListDiscover/view.jsx
ui/page/discover/view.jsx

Closes https://github.com/OdyseeTeam/odysee-homepages/issues/427
- Available at dev instance
- No pins for English at the moment, though. Need to use other homepages.

Add pinning in Category Pages's Trending Tab

---

ui/scss/component/_media.scss

- Closes https://github.com/lbryio/lbry-desktop/issues/7222
- Also felt it's too squished for the longest time. Previously fixed comments but didn't handle this.

File description (collapsed): show ~3 lines instead of ~1

---

ui/component/viewers/videoViewer/internal/videojs.jsx

Restored css load-order that was changed from a recent refactor.

Fix double pause button in mobile

---

ui/component/inviteNew/index.js
ui/component/inviteNew/view.jsx
ui/component/selectChannel/index.js
ui/component/selectChannel/view.jsx

- Remove unused props (less things to calculate)
- Use lighter selector

Cleanup for `SelectChannel` and few others

---

ui/page/home/view.jsx
web/component/ads/view.jsx

Persists ads between navigation by clearing out state that was saved and prevented ad reloads

Persist ads

---

ui/component/claimLink/index.js

Issue Number: Closes #375
</details>

Fix some certain wordings breaking page

---

ui/component/router/view.jsx
ui/component/sideNavigation/view.jsx
ui/page/home/view.jsx
ui/util/buildHomepage.js

If approved, don't squash this PR.
Anthony's double render
See commit messages.

Category Page double-render for un-auth case

---

ui/component/channelContent/view.jsx
ui/page/discover/view.jsx

Add ads to category pages

---

ui/page/livestream/index.js
ui/page/livestream/view.jsx

- Remove unused prop.
- Use primitives whenever possible, since object references could change.

Livestream page prop optimization

---

ui/component/app/view.jsx

Don't load Google IMA when not authenticated

---

ui/component/textareaWithSuggestions/view.jsx

Fix named capturing groups not supported in some browsers

---

ui/constants/livestream.js

new player domain

---

package.json
ui/component/viewers/videoViewer/internal/chromecast.js
ui/component/viewers/videoViewer/internal/videojs.jsx
ui/component/viewers/videoViewer/view.jsx
ui/scss/component/_file-render.scss
ui/scss/component/_videojs.scss
yarn.lock

Fixes #446
https://www.notion.so/Chromecast-8d5ead2bebe84b83b87aff4d3ec1f0f4

Chromecast -- with "disconnect hack"

---

ui/component/webUploadList/internal/web-upload-item.jsx
web/setup/publish-v2.js

Closes #418 TUS: skip fingerprint storage

tus: skip fingerprint storage

---

ui/analytics.js
ui/component/claimListDiscover/index.js
ui/component/claimListDiscover/view.jsx
ui/component/claimListHeader/index.js
ui/component/claimTilesDiscover/index.js
ui/component/claimTilesDiscover/view.jsx
ui/redux/actions/app.js
ui/redux/actions/sync.js
ui/redux/actions/tags.js

No longer necessary.
Also removed a few `doToggleTagFollowDesktop` props (unused by the View).

Remove `content_tags` and related functions

---

ui/component/common/card.jsx
ui/component/loginGraphic/index.jsx
ui/component/page/view.jsx
ui/component/userSignUp/index.js
ui/component/userSignUp/view.jsx
ui/scss/component/_main.scss

Google Console's complaining about this page, so we don't want to it to drag down the average.
This also serves as a experiment to see if GC/Lighthouse/CoreVitals is actually reflecting the latest site.  The local score is close to perfect, so it should at least move the results a little.
- See commit messages

Sign-up page optimization

---

ui/component/common/form-components/form-field.jsx

Closes #460
ui.js: 4.44MB -> 3.94MB
----
@saltrafael, can you help to test just in case I broke something?

Split MUI and Emoji-Lib

---

static/app-strings.json
ui/component/channelEdit/view.jsx
ui/component/channelThumbnail/view.jsx
ui/component/selectAsset/view.jsx
ui/constants/cdn_urls.js
ui/redux/actions/publish.js

Test: `kp`
Closes #439 
The server still does not spew the exact error message, so I just put something like "the format or extension might not be supported".

Switch thumbnail server: spee.ch --> vanwanet

---

ui/component/page/view.jsx
ui/component/sideNavigation/view.jsx
ui/scss/component/_footer.scss
ui/scss/component/_main.scss
ui/scss/component/_navigation.scss
ui/scss/init/_vars.scss

Issue Number:  😃
Currently, when the menu is opened, there are no animations.
It is very jumpy. 
This PR would add menu animations to all pages.
If the page is the filepage (or the screen size is medium-small) it will use the absolute menu which uses overlay and slide-in animations.
If the page is the fullscreen page, or pretty much any other page that isn't the video page and the screen size is large. It will use push animations and push the content to the right.
Demonstration:
https://odysee.com/@MaxKotlan:5/AnimationDemo:e
I don't believe this contains a breaking change.
However, the component and styles I changed are very central to the entire app. It is possible there is a breaking change, which is why I decided to mark this as a draft. 
I spent a lot of time checking testing for …

New Menu Animations

---

static/app-strings.json
ui/component/channelEdit/view.jsx
ui/component/channelThumbnail/view.jsx
ui/component/selectAsset/view.jsx
ui/constants/cdn_urls.js
ui/redux/actions/publish.js

Reverting until vanwa can provide us failure details to handle accordingly.

Revert "Switch thumbnail server: spee.ch --> vanwanet #497"

---

ui/component/page/view.jsx
ui/component/sideNavigation/view.jsx
ui/scss/component/_footer.scss
ui/scss/component/_main.scss
ui/scss/component/_navigation.scss
ui/scss/init/_vars.scss

Issue Number:
Current branch animates with width which is not very performant on mobile devices.
Adds the new menu animations to the theme rewrite branch.
Although they're not perfect yet, these animations use transforms which are more performant on lower powered platforms. 
When animating width, each frame is recomputed on the cpu by repainting the DOM, whereas transforms are usually gpu accelerated.
Proof of this is from enabling 4x cpu throttling and comparing the framerate of each animation. 
Plus the transitions to the floating menus, micro menu, and push menu are smoother because they're all the same menu in this PR. Whereas before they were different menus.
If this passes I will help work on improving the content transition (using transforms). Right now the width resize is causing …

Neko themes new menu animation

---

ui/scss/component/_main.scss

Issue Number:
New fullscreen page animation. Not as jumpy.
</details>

custom fullscreen page transform

---

flow-typed/Lbry.js
ui/redux/actions/claims.js
ui/redux/actions/livestream.js

Issue Number: #477 
</details>

Add ability to have claim searches auto-fetch up to 3 pages.

---

ui/component/userChannelFollowIntro/index.js
ui/component/userChannelFollowIntro/view.jsx
ui/constants/community_channels.js

per Leo request, only a few so far but can be used for testing for others also.

Add language based channels to Auto follow 

---

flow-typed/sync.js
ui/redux/actions/app.js
ui/redux/reducers/sync.js

Just breaking this up from an upcoming commit to lessen the diff.

Minor cleanup -- no functional change

---

ui/scss/component/_header.scss

Header fallout

---

ui/component/common/credit-amount.jsx
ui/component/livestreamComments/view.jsx
ui/scss/component/_livestream.scss

Issue Number:  Closes #298
The problem was mainly the wrapper around each superchat that would make it re-render while scrolling

[Superchats] Fix scroll re-render issues and improve style when stickers are used

---

ui/component/header/view.jsx

[Header] Fix menu on password reset page

---

ui/component/common/markdown-preview.jsx
ui/component/livestreamComment/view.jsx
ui/component/markdownLink/index.js
ui/component/markdownLink/view.jsx
ui/scss/component/_livestream.scss

[Live Comment] Highlight chat message if your channel is mentioned

---

static/app-strings.json
web/component/nag-no-user.jsx

- add i18n string
- simply component

NagNoUser i18n update

---

ui/component/livestreamComment/index.js

...and not displaying embeds even with enough stake
Issue Number: Closes #597

[LivestreamComment] Fix stakedLevel looking looking for wrong prop

---

ui/component/publishAdditionalOptions/view.jsx
ui/component/publishFile/view.jsx
ui/component/publishForm/view.jsx
ui/component/publishReleaseDate/view.jsx
ui/component/publishStreamReleaseDate/view.jsx
ui/constants/publish_sources.js
ui/modal/modalPublishPreview/view.jsx
ui/redux/selectors/claims.js

Reverts OdyseeTeam/odysee-frontend#565

Revert "Fix publish form when editing livestream "

---

ui/page/notifications/view.jsx

"No notifications" briefly appear when entering Notifications Page if your previous filter was not "All".
When splitting up the category-fetch, the render logic was not updated accordingly.

Notifications: handle view while fetching categories

---

static/app-strings.json
ui/page/buy/view.jsx

Temporarily disable Buy due to Moonpay integration down

---

ui/component/livestreamComment/view.jsx

[LivestreamComment] Allow removing my superchat

---

ui/util/web.js
web/src/html.js
web/src/oEmbed.js

Properly escape referrerQuery before using in meta tags. 
</details>

Escape/encode referrerQuery

---

ui/component/channelContent/view.jsx
ui/page/discover/view.jsx
ui/page/home/view.jsx
web/component/ads/index.js
web/component/ads/view.jsx

Refactor ad implementation, fix two bugs

---

ui/component/publishAdditionalOptions/view.jsx
ui/component/publishFile/view.jsx
ui/component/publishForm/view.jsx
ui/component/publishReleaseDate/view.jsx
ui/component/publishStreamReleaseDate/index.js
ui/component/publishStreamReleaseDate/view.jsx
ui/constants/publish_sources.js
ui/modal/modalPublishPreview/view.jsx
ui/redux/selectors/claims.js
ui/redux/selectors/publish.js

Feature livestream publish form

---

ui/redux/actions/publish.js

Vanwa handle json

---

ui/component/claimList/view.jsx
ui/component/claimListDiscover/view.jsx
ui/component/claimPreview/view.jsx
ui/component/claimPreviewTile/view.jsx
ui/component/scheduledStreams/view.jsx
ui/page/home/view.jsx
ui/scss/all.scss
ui/scss/component/_claim-list.scss
ui/scss/component/_swipe-list.scss
ui/scss/component/_utils.scss

Show scheduled streams as a scrollable horizontal list on mobile-like screens to minimize space usage.
Upcoming streams are displayed as a vertical list.
Upcoming streams are displayed as a swipe-able horizontal list.
</details>

Add horizontal layout

---

web/setup/publish-v2.js

Per developer of `tus-js-client`, it is normal to occasionally encounter upload errors. The auto-retry mechanism is meant to address this.
While implementing tab-lock to prevent multiple uploads of the same file, 423_locked was used to detect this scenario. But 423_locked could also mean "the server is busy writing the chunk" (per discussion with Randy), so we kind of disabled the auto-retry mechanism accidentally.
Meanwhile, from a prior discussion with Randy, one of the chunk-writing duration took 3 minutes. Our current maximum of "retry after 15s" wouldn't help.
1. Given that tab-locking was improved recently and no longer reliant on the server error messages (we use secure storage to mark a file as locked), reverted the change to "skip retry on 409/423". This is now back to normal …

TUS: retry on 423_locked to try address "failed to upload chunk"

---

flow-typed/publish.js
web/setup/publish.js

I think I just forgot to do it the first time.

Route markdown to v1

---

ui/component/fileActions/index.js
ui/component/fileActions/view.jsx
ui/page/file/view.jsx

Also restore reactions
This is only an internal tag

Fix comment disabling on MD

---

web/setup/publish-v2.js

tus: delay adjustments + clean up error messages

---

ui/component/commentCreate/view.jsx
ui/component/textareaWithSuggestions/view.jsx

Fix mentioning with enter on Livestream

---

ui/component/textareaWithSuggestions/view.jsx

Prevent Up and Down keys behavior being overriden in Textfield

---

ui/modal/modalRemoveCard/index.js
ui/modal/modalRemoveFile/index.js
ui/modal/modalRemoveFile/view.jsx
ui/modal/modalRevokeClaim/index.js
ui/modal/modalRevokeClaim/view.jsx
ui/redux/actions/claims.js
ui/redux/actions/collections.js
ui/redux/actions/file.js

Fix doAbandonClaim

---

ui/component/textareaWithSuggestions/view.jsx

Fix livestream key listeners

---

ui/component/page/view.jsx

Fix sidebar

---

flow-typed/Comment.js
static/app-strings.json
ui/redux/actions/comments.js
ui/util/commentron-error.js

https://odysee-workspace.slack.com/archives/C02FMSYF51B/p1642435815038000?thread_ts=1642129696.024400&cid=C02FMSYF51B

Commentron `*Delegates` param update

---

web/setup/publish-v2.js

tus: route errors to sentry

---

ui/component/channelContent/view.jsx

Fixes https://github.com/OdyseeTeam/odysee-frontend/issues/604

Only send search request when string length enough for api expectation.

---

ui/component/fileActions/index.js
ui/component/fileActions/view.jsx
ui/constants/tags.js

Fixes https://github.com/OdyseeTeam/odysee-frontend/issues/742
A future feature would allow users to choose this tag from a special control list.

Respect disable download button tag

---

ui/component/selectAsset/view.jsx

1. Added size-specific error message.
2. Route whatever Vanwa's error instead of showing "unexpected json token". It's ugly, but at least it contains the reason string.  It should go away when Nick handles it.

Channel Thumbnail: handle json errors

---

ui/component/commentsReplies/view.jsx
ui/redux/selectors/comments.js

Fixes https://github.com/OdyseeTeam/odysee-frontend/issues/747
The app was crashing due to `fetchedReplies` being null.  Optional chaining the length prop resolves this.

Fix null property access bug

---

ui/component/viewers/videoViewer/internal/plugins/videojs-recsys/plugin.js

Johnny aware and backend should handle it fine

Force stop event on dispose

---

ui/component/embedTextArea/view.jsx
ui/util/web.js
web/src/oEmbed.js

Issue Number:  closes #787
Now embeds should work with either referral or timestamp params

Fix embed url param parsing

---

ui/component/viewers/videoViewer/view.jsx

this was causing an error and breaking other stuff (play next/previous buttons on playlists) and this simple check alone seems to fix it

Fix player error

---

ui/component/common/debounced-input.jsx
ui/component/sideNavigation/view.jsx
ui/effects/use-debounce.js
ui/scss/component/_navigation.scss

Not sure if this conflicts with some of your road map, but I thought I'd throw this out there.  I was trying to sift through my list to find some channel I'd subbed to and wished I could have filtered it down.  So I thought I'd just slap it in real quick and see what you guys thought about adopting it.
Some of the classes may not be semantically perfect, but I figured I'd just run it by you guys to even see if it's something you'd want to adopt and let you decide on what better classes or styles, if any, might be applied.

Feature Suggestion: Channel list filter

---

web/src/oEmbed.js

should be better now as a constant

Fix embed params regex

---

ui/component/publishFile/view.jsx
ui/component/publishForm/view.jsx
ui/component/publishFormErrors/view.jsx

Add max bitrate messaging

---

ui/component/sideNavigation/view.jsx

I'm dumb and forgot to lowercase the filter term as well:

Case insensitive subscription filter

---

ui/page/help/view.jsx

There is no #help in the new odysee Discord.  Closest I can find is #support

Update chat channel

---

ui/component/comment/index.js
ui/component/comment/view.jsx
ui/component/commentsList/index.js
ui/component/commentsList/view.jsx
ui/component/commentsReplies/index.js
ui/component/commentsReplies/view.jsx
ui/component/fileActions/view.jsx
ui/component/fileTitleSection/view.jsx
ui/page/ownComments/view.jsx

Issue Number: #813
- Fetching new comment list pages
- Fix edit for own claims
- Expand the More view to bottom

[Fixes] Mobile fall out

---

ui/component/comment/index.js

[Fix] Edit

---

ui/scss/component/_videojs.scss

theme-hotfix

---

ui/component/claimLink/view.jsx
ui/component/livestreamChatLayout/index.js
ui/component/livestreamChatLayout/view.jsx
ui/component/livestreamComments/index.js
ui/component/livestreamComments/view.jsx

[Fix] Live tips sorting and scrolling

---

ui/redux/actions/app.js

Fix registering view API

---

ui/component/router/index.js
ui/component/router/view.jsx
ui/component/sideNavigation/index.js
ui/component/sideNavigation/view.jsx
ui/redux/selectors/settings.js

Wild West DE change

---

ui/component/claimList/view.jsx
ui/component/notification/view.jsx

Fix "key missing in list" errors

---

ui/component/livestreamLayout/view.jsx
ui/scss/component/_main.scss

[Fix] Live scroll bar

---

ui/component/router/view.jsx

[Fix] DE wild west

---

ui/component/app/view.jsx
ui/component/sideNavigation/view.jsx
ui/scss/component/_header.scss
ui/scss/init/_gui.scss
ui/scss/init/_vars.scss
ui/scss/themes/dark.scss
ui/scss/themes/light.scss

- Adds custom scrollbar to body in chrome.
- Prevents user from scrolling content when the overlay is opened on the file page.
Issue Number:
**Custom scrollbar**
Currently uses native browser scrollbar
**Overlay:**
Currently, when the overlay is open you can still scroll the content behind it.
**Custom scrollbar**
**Overlay:**
Now when the overlay is opened, the content scrollbar is disabled until the overlay is closed.
For the body scrollbar, I did make it twice as wide as the scrollbars used other places. To me the body scrollbar seemed a little too small so I decided to make it  slightly larger for accessibility purposes. 
The default chrome scrollbar is 17px, and the current custom scrollbar is 6px, so I thought 12px was a healthy middle-ground. 
Tested in Chrome and Firefox.
Did some …

Custom body scrollbar + Disable overlay scrolling

---

ui/component/headerProfileMenuButton/view.jsx

[Fix] Header null activeChannel case

---

ui/component/sideNavigation/view.jsx

Add "Sync YT Channel" to sidebar

---

web/src/html.js

Doesn't seem to do much, but it is what others do, so might has well be specific.

Increase specificity of `og:type`

---

ui/component/livestreamLayout/view.jsx
ui/page/show/index.js
ui/page/show/view.jsx
ui/redux/actions/publish.js

Issue Number: linked comment: #813
- Fixes linked livestreams (like clicking from notifications) passing the wrong uri and not playing on mobile
- Fixes linked comments being erased from the url and not scrolling

[Fix] linked uris

---

ui/component/claimPreview/view.jsx
ui/component/claimPreviewSubtitle/view.jsx
ui/component/claimPreviewTile/view.jsx
ui/component/claimPreviewTitle/view.jsx
ui/component/claimRepostAuthor/view.jsx
ui/component/sideNavigation/view.jsx
ui/component/uriIndicator/view.jsx
ui/scss/component/_navigation.scss

Use titles vs names on channel claim previews, but show name in channel areas

---

web/setup/publish-v2.js

Stop logging localStorage sizes

---

web/setup/publish-v2.js

Closes #910
- Change the "message" from a generic "tus-upload" to more specific ones like "tus: failed to resume upload". These are grouped as "Events" in sentry, so we can isolate and search for them easily.
- Pass more info to Sentry (previously only available from Slack). 
- Was unable to change the "unknown" problem mentioned in the ticket. The API does not accept `new Error('xxx')`, even though that's being mentioned by many in the forums. It might be due to the version of Sentry that we are using.
- To search for tus issues, go to "Issues" and query `message:tus*`. Results are collapsed per event, so click on the item of interest, then click "Events" at the upper right to see all occurrences of the same problem.

tus: sentry improvements

---

ui/component/common/icon-custom.jsx

Fix ICONS.SUBMIT lost in a prior commit

---

ui/scss/component/_claim-search.scss

Restore spacing between Sort and Filter on mobile

---

ui/scss/component/_main.scss

Steps:
- On incognito, play a video
- click something that needs auth like Support or Save
- the floating player can't be dragged down
can test on https://salt.odysee.com

[Fix] floating player on auth page

---

extras/lbryinc/redux/actions/stats.js
extras/lbryinc/redux/reducers/stats.js
static/app-strings.json
ui/component/app/view.jsx
ui/component/claimListDiscover/view.jsx
ui/component/common/debounced-input.jsx
ui/component/router/view.jsx
ui/component/sideNavigation/view.jsx
ui/constants/claim_search.js
ui/constants/pages.js
ui/constants/subscriptions.js
ui/page/channelsFollowing/view.jsx
ui/page/channelsFollowingManage/index.js
ui/page/channelsFollowingManage/view.jsx
ui/scss/init/_gui.scss

- Indirectly closes #647
- Closes #986
`kp` dev instance

Add "Manage Following" Page

---

ui/component/scheduledStreams/view.jsx
ui/page/channelsFollowing/view.jsx
ui/scss/component/_main.scss

See commit messages for list of changes.
Unsquash for this one too

More livestream tweaks + Following Page fixes

---

ui/component/recommendedContent/view.jsx
ui/scss/init/_gui.scss

It takes a while sometimes, so it feels like not doing anything.

Recommended section: add spinner while searching

---

web/setup/publish-v2.js

https://odysee-workspace.slack.com/archives/C02FH1UGKGR/p1646236430266669?thread_ts=1642130367.009400&cid=C02FH1UGKGR

tus: try longer retry delays to maybe avoid lockups

---

static/app-strings.json
ui/component/nagLocaleSwitch/index.js
ui/component/nagLocaleSwitch/view.jsx

Issue Number: closes #1011
- fixed logic for handling different scenarios (language, homepage, either, none, is set in settings etc)
live on https://salt.odysee.com

[Fix] Locale switch nag also appears if the language/homepage already selected

---

ui/component/app/view.jsx

[Fix] locale fetch

---

ui/component/homepageSelector/view.jsx

Localize the homepage selector too

---

ui/scss/component/_ads.scss
web/component/ads/view.jsx

Fix EU ad fallout

---

ui/scss/component/_collection.scss
ui/scss/component/_comments.scss
ui/scss/component/_file-render.scss
ui/scss/init/_gui.scss

Fix design related issues
- Fix tag alignment on channel-to-follow page
- Fix font size for channel handles in comment section on desktops
- Fix background for wrapper in recommended section on desktops

Fix design & UI issues

---

ui/scss/component/_claim-list.scss
ui/scss/component/_collection.scss
ui/scss/component/_comments.scss
ui/scss/component/_file-render.scss
ui/scss/init/_gui.scss

Fix play icon on active element in playlist.

Design patch v2

---

ui/component/uriIndicator/index.js
ui/component/uriIndicator/view.jsx

uriIndicator: calling normalizeURI called without a try-catch

---

.env.defaults
config.js
flow-typed/user.js
static/app-strings.json
ui/component/app/view.jsx
ui/constants/settings.js
ui/page/livestream/view.jsx

Support for creator-requested geoblocking

---

ui/component/commentsList/index.js
ui/page/file/index.js
ui/page/ownComments/index.js
ui/redux/reducers/comments.js
ui/redux/selectors/comments.js

Fix comment count not incremented correct if it was previously 0

---

extras/recsys/recsys.js

**Ticket:** Closes #1080
**Reason:** unreliable; often blocked.
**Additional:** add auth-token, per suggestion in FYP PR.
Need second pair of eyes ...

Replace recsys beacon with regular network call

---

ui/page/home/view.jsx
web/component/ads/view.jsx

Homepage-Following: insert instead of replace when ad-blocker is detected

---

.env.defaults
config.js
flow-typed/Blocklist.js
flow-typed/user.js
static/app-strings.json
ui/constants/action_types.js
ui/index.jsx
ui/page/livestream/view.jsx
ui/page/show/index.js
ui/page/show/view.jsx
ui/redux/actions/blocked.js
ui/redux/reducers/blocked.js
ui/redux/selectors/blocked.js
ui/redux/selectors/claims.js

Closes [#1079 Support geoblocking channels/videos](https://github.com/OdyseeTeam/odysee-frontend/issues/1079)
- Replaced the .env version with iapi version.
- Includes 'videos' blocking and custom messages.

Geo blocklist - reimplement with backend support

---

ui/redux/actions/search.js

FYP: batch resolve results

---

static/app-strings.json
ui/component/claimMenuList/index.js
ui/component/claimMenuList/view.jsx
ui/component/claimPreviewTile/view.jsx
ui/component/fileHideRecommendation/view.jsx

- This allows mobile to reject recommendations.
- Also changed from "I dislike this" to "Not interested". Less negative?
#1102

FYP: allow mobile to reject + change phrasing

---

ui/component/fileRenderInitiator/view.jsx

fileRenderInitiator: missing timer cleanup

---

ui/scss/component/_main.scss
ui/scss/init/_vars.scss

Fix file page layout shift

---

ui/scss/component/_main.scss

I think the scss code is due a refactoring, some things that are intended to behave the same have separate values, etc.

Fix playlist side column

---

ui/lbry.js

<sub>This reverts commit 36a63e27c122bd47ff3deb96e6adb5a1ad76da3c.</sub>
Probably a bad idea, too many

Revert "Log which method caused `Failed to fetch`"

---

ui/component/app/index.js
ui/component/app/view.jsx
ui/component/nagLocaleSwitch/view.jsx
ui/redux/actions/settings.js
ui/redux/reducers/user.js
ui/redux/selectors/user.js

Issue Number: closes #1032
- Prevents Nag displaying too early and "flickering"
- Only suggests homepage switch when on the homepage instead of subpages
- Prevents Nag on embedded content

Locale Nag Fixes

---

static/app-strings.json
ui/constants/pageTitles.js
ui/constants/pages.js
web/src/category-metadata.js

- _I don't know if "Artists" is just a title change or a new category entirely (I assumed the latter)_

Category: Artists

---

ui/effects/use-ad-outbrain.js

This is a quick-fix without having to make the 2 components know about each other.
Somewhat closes #1165

Push outbrain below the Nag

---

ui/component/settingsRow/view.jsx

Also increased opacity a bit as it's hard to read the subtitle which is already grayed out.

SettingsRow: filter clicks when grayed out

---

ui/component/page/view.jsx
ui/component/router/view.jsx
ui/page/discover/view.jsx
ui/page/home/view.jsx
ui/scss/init/_gui.scss

Exclude Following and Wild West

Hide repost ribbon in Category Pages

---

ui/page/embedWrapper/index.js
ui/page/embedWrapper/view.jsx
ui/redux/actions/user.js
ui/redux/selectors/rewards.js

Fix referrer on embed

---

ui/component/notificationBubble/view.jsx
ui/component/router/index.js
ui/component/router/view.jsx
ui/util/notifications.js

Update browser window title when notifications are received

---

ui/component/nagLocaleSwitch/index.js
ui/component/nagLocaleSwitch/view.jsx
ui/redux/selectors/user.js

Improve locale Nag wording for CA

---

ui/component/viewers/videoViewer/internal/plugins/videojs-overlay/plugin.scss
ui/scss/component/_expandable.scss

https://github.com/OdyseeTeam/odysee-frontend/pull/1191

Fix scss deprecation warnings

---

ui/page/channel/view.jsx

OptimizedImage: clean up attribute removal

---

ui/component/viewers/videoViewer/internal/videojs.jsx

Reverts OdyseeTeam/odysee-frontend#1210

Revert "Send 10 percent of livestream traffic to other server"

---

ui/component/viewers/videoViewer/internal/overlays.js
ui/component/viewers/videoViewer/internal/videojs-keyboard-shortcuts.jsx
ui/constants/keycodes.js

Issue Number: not sure if there is an issue for this
allows clicking 0, 1, 2, 3 etc to move to 0, 10%, 20%... duration of a video

Add percentage video duration keybinds

---

ui/component/claimSupportButton/index.js
ui/component/claimSupportButton/view.jsx
ui/component/commentCreate/index.js
ui/component/commentCreate/view.jsx
ui/component/common/icon-custom.jsx
ui/component/txoList/view.jsx
ui/component/walletFiatAccountHistory/view.jsx
ui/component/walletSendTip/index.js
ui/component/walletSendTip/view.jsx
ui/component/walletTipAmountSelector/index.js
ui/component/walletTipAmountSelector/view.jsx
ui/constants/icons.js
ui/page/settingsStripeCard/view.jsx
ui/redux/actions/wallet.js

Supports tipping in EUR
Can be confirmed by trying a test tip, and checking for `tip` in the Network Call, then look for `currency: eur` in the response

Support EUR tipping

---

ui/component/claimTilesDiscover/index.js
ui/component/claimTilesDiscover/view.jsx
ui/page/discover/view.jsx
ui/page/home/view.jsx

Ticket: Closes #1220
Test: `kp`

Force reposts in Homepage + Category Page, except Following & WW

---

ui/component/walletSendTip/view.jsx
ui/scss/component/_channel.scss
ui/scss/component/_claim-list.scss
ui/scss/component/_claim-search.scss
ui/scss/component/_comments.scss
ui/scss/component/_livestream-chat.scss
ui/scss/component/_notification.scss
ui/scss/init/_gui.scss
ui/util/notifications.js

Design fallout patch 2

---

ui/scss/component/_file-render.scss
web/component/fileViewerEmbeddedEnded/view.jsx

Issue Number: closes #1218
also moved around the end strings, some make sense for both to see?

Improve embed end screen

---

ui/component/commentsList/view.jsx

Issue Number: closes #1223
the problem was that a page would fetch 1+ pages, and then the next page would try to fetch the same page

Fix claim switch comment.List fetch behavior

---

ui/component/claimPreview/view.jsx
ui/component/claimPreviewProgress/index.js
ui/component/claimPreviewProgress/view.jsx
ui/component/claimPreviewTile/view.jsx
ui/component/viewers/videoViewer/view.jsx
ui/scss/component/_claim-list.scss

Watch-progress indicator (no-API version)

---

ui/component/app/view.jsx
ui/effects/use-ad-outbrain.js

I don't think these pages should be serving ads.
Close if disagree :)

Exclude outbrain in certain pages

---

ui/scss/component/_claim-list.scss
ui/scss/component/_file-price.scss
ui/scss/component/_modal.scss
ui/scss/component/_videojs.scss
ui/scss/init/_gui.scss

Design patch 6

---

ui/component/fileWatchLaterLink/view.jsx
ui/scss/component/_claim-list.scss
ui/scss/component/_media.scss

Design patch 7

---

ui/effects/use-ad-outbrain.js

- Due to the timer used, the script could be loaded after the path-checking useEffect ran.
- Stale closure is also an issue.
Create refs for the props, and listen to `onload` as well to resolve the visibility state.

Patch for outbrain visibility (e68bba1d)

---

ui/page/signInVerify/view.jsx

Test: `kp`
Closes #1233 
Expand commit messages for details.
I've excluded the previous improvement PR to keep the review/testing simple.

Fix double `confirm` call

---

ui/component/viewers/videoViewer/internal/videojs.jsx
ui/constants/livestream.js
ui/redux/actions/websocket.js
ui/util/livestream.js

Incremental support - if you go direct, refresh, or through a channel page, it will try the new API and fallback to old...

partial new livestream api support

---

ui/scss/component/_file-drop.scss
ui/scss/component/_media.scss
ui/scss/component/_search.scss
ui/scss/component/_wunderbar.scss
ui/scss/component/section.scss
ui/scss/init/_gui.scss

Design fallout patch 9

---

ui/component/sideNavigation/view.jsx
ui/component/viewers/videoViewer/internal/videojs.jsx
ui/effects/use-screensize.js
ui/util/platform.js
web/component/ads/view.jsx

Consolidate duplicate and scattered platform-detection stuff into `platform`.

Consolidate platform-detection code

---

static/app-strings.json
ui/component/publishName/name-help-text.jsx
ui/redux/actions/claims.js

Fix name-availability-check for Reposts
3f805a61 broke Reposts. The action needs to return whether there are any clashes.

Fix name-availability-check for Reposts

---

flow-typed/gui.js
ui/component/claimList/view.jsx
ui/component/claimListDiscover/view.jsx
ui/component/claimTilesDiscover/view.jsx
ui/effects/use-get-last-visible-slot.js

Support callback method to inject items

---

ui/scss/component/_main.scss
ui/scss/component/_navigation.scss
ui/scss/component/_notification.scss
ui/scss/component/_tags.scss
ui/scss/component/section.scss

Design Patch 2022-04-19

---

ui/component/common/credit-amount.jsx

Fix NaN Tipped

---

ui/component/page/index.js
ui/component/page/view.jsx
ui/page/file/view.jsx
ui/scss/component/_file-render.scss

Disable theater mode for non-video file pages.

Filepage theater fix

---

ui/component/claimInsufficientCredits/index.js
ui/component/claimPreview/index.js
ui/component/fileDownloadLink/index.js
ui/component/filePrice/index.js
ui/component/fileRenderFloating/index.js
ui/component/fileRenderInitiator/index.js
ui/component/fileRenderInline/index.js
ui/page/file/index.js
ui/page/file/view.jsx
ui/redux/actions/content.js
ui/redux/selectors/claims.js

Fix purchased content failing to play

---

flow-typed/homepage.js
ui/component/claimListDiscover/view.jsx
ui/component/homepageSort/view.jsx
ui/component/router/view.jsx
ui/component/sideNavigation/index.js
ui/component/sideNavigation/view.jsx
ui/constants/homepage_languages.js
ui/page/discover/livestreamSection.jsx
ui/page/discover/view.jsx
ui/page/home/view.jsx
ui/util/buildHomepage.js
ui/util/livestream.js

- Test: `inf` (new!)
- :warning: requires simultaneous push with homepage PR.
- See commit messages for details.  Diffs will be clearer if go through one by one.
- Closes https://github.com/OdyseeTeam/odysee-homepages/issues/1318
_Route back to me if approved -- I'll clean up and perform the push._

Make Wild-West a proper Category + additional features.

---

ui/component/commentCreate/view.jsx

Comment: ignore minAmount when in Fiat

---

ui/page/settingsStripeAccount/view.jsx
ui/scss/component/_button.scss
ui/scss/component/_claim-list.scss
ui/scss/component/_comments.scss
ui/scss/component/_main.scss
ui/scss/component/_tags.scss
ui/scss/themes/dark.scss
ui/scss/themes/light.scss

Design patch 2022-04-25

---

ui/scss/component/_file-render.scss
ui/scss/component/_videojs.scss

Ticket: Closes #1288
1. Move airplay slot away from the first.
2. Fix sizing to match the rest.

AirPlay button fixes

---

package.json
yarn.lock

- Console error for multiline in Autocomplete component was changed into warning
Issue Number: Closes #464
The fix:
`https://github.com/mui/material-ui/pull/30680`

Bump @mui/material

---

ui/component/textareaWithSuggestions/view.jsx

Closes #1301 and I'm pretty sure also closes #1347
_flow failed but condition was already considered above_

Fix textarea undefined value case

---

ui/component/viewers/videoViewer/internal/plugins/videojs-hls-quality-selector/plugin.js

Reverts OdyseeTeam/odysee-frontend#1403

Revert "Fix original and livestream quality switch behavior"

---

ui/page/ownComments/view.jsx

Fix missing uri param for fetchReplies

---

ui/component/common/header-menu-link.jsx
ui/component/headerMenuButtons/view.jsx

Show upload menu for no-auth but redirect to sign up

---

ui/lbry.js

This one probably needs more scrutiny...
Test: `inf` (it includes sso, though. Use a different account if don't want to mess up, just in case).
Closes #1320
- Create a layer on top of `Lbry` to log failures. `ApiFailureMgr` encapsulates this.
- Only logging `claim_search` for now as a start. Can be used for all methods.
- When a `claim_search` (with the same options) repeatedly failed for 5 times within 500ms, block subsequent calls for a duration of 1 minute.
- These values can be adjusted.
1. Homepage
2. Block `claim_search` from dev_tools
3. Go to Following
4. Hammer on "try again in a few seconds" as fast as you can.  `claim_search` will stop appearing in Network.
5. Wait 1 minute, and hit "try again in a few seconds" (unblock first if you want).  `claim_search` will appear again.

Pause successively-failed `claim_search` calls for 1 minute

---

ui/modal/modalRepost/view.jsx

Fix repost modal crashing if uri has spaces

---

ui/component/channelEdit/view.jsx

Add Sync youtube channel button on New Channel page

---

ui/component/fileRenderInitiator/view.jsx

Fix wrong logic for live polling

---

ui/component/button/view.jsx
ui/component/repostCreate/view.jsx
ui/component/router/view.jsx
ui/constants/pageTitles.js
ui/constants/pages.js
ui/page/repost/index.js
ui/page/repost/view.jsx

Bring back ability to direct link repost

---

static/app-strings.json
ui/redux/actions/wallet.js
ui/util/api-message.js

Was just getting a generic "Transaction failed" and had to check devTools to figure out what's wrong.

Relay fund-transfer failure reason to user

---

static/app-strings.json
ui/component/viewers/videoViewer/internal/chapters.jsx
ui/scss/component/_file-render.scss
ui/scss/component/_videojs.scss

- Make the chapters button appear consistently.
- Previously, it was only appearing for Original.
- We still hide it for mobile, as per previous explanation.
- Changed the Chapters button position and popup aesthetics.

Player: chapter follow-up tweaks

---

ui/redux/actions/comments.js

Allow creators to Creator-Like on top of basic reactions

---

ui/component/headerProfileMenuButton/index.js
ui/component/headerProfileMenuButton/view.jsx
ui/component/router/index.js
ui/component/router/view.jsx

Issue Number: closes #1467 
- and fixes mobile unauth state

Channel select fallout

---

ui/lbry.js

v1 publishing timeout is already being recorded, under the string `publish-v1: timed out after`

Restore SDK error logging, limiting to `support_create`.

---

.env.defaults
config.js
ui/util/web.js

remove hard coded stream url > use get

---

.env.defaults
config.js
ui/util/web.js

Reverts OdyseeTeam/odysee-frontend#1497

Revert "remove hard coded stream url > use get"

---

web/src/getHomepageJSON.js

Fix broken v1 homepage api

---

flow-typed/Comment.js
ui/component/channelDiscussion/index.js
ui/component/channelDiscussion/view.jsx
ui/component/comment/index.js
ui/component/comment/view.jsx
ui/component/commentMenuList/view.jsx
ui/component/commentsList/index.js
ui/component/commentsList/view.jsx
ui/component/commentsReplies/index.js
ui/component/commentsReplies/view.jsx
ui/component/common/wait-until-on-page.jsx
ui/component/expandable/view.jsx
ui/component/notification/view.jsx
ui/component/publishForm/view.jsx
ui/component/userChannelFollowIntro/view.jsx
ui/constants/comment.js
ui/index.jsx
ui/page/file/index.js
ui/page/file/view.jsx
ui/page/show/view.jsx
ui/redux/reducers/comments.js
ui/redux/selectors/comments.js
ui/scss/component/_card.scss
ui/scss/component/_comments.scss
ui/scss/component/_main.scss
ui/scss/component/_textarea-suggestions.scss

Issue Number: closes #1044
live on https://salt.odysee.com
here's a long thread to test: https://salt.odysee.com/@test:a4?view=discussion&tc=89257f8e158c50cfc867bf95c799133de9196e512853151177b6d71c21ad9e8c

Re-design comment threads

---

flow-typed/content.js
ui/redux/reducers/content.js
ui/redux/selectors/content.js

Fix ContentState type

---

web/src/routes.js

:facepalm: missed one ...
http://localhost:1337/$/stream/rompiendo-defendiendo-el-silencio-sobre/e65f2afaa90869626a12813b3cebbde67d9800a4 now works

Fix bad stream url redirect.

---

ui/component/channelContent/index.js
ui/component/channelContent/view.jsx
ui/component/recommendedContent/index.js
ui/component/recommendedContent/view.jsx
ui/page/discover/index.js
ui/page/discover/view.jsx
ui/page/home/index.js
ui/page/home/view.jsx
ui/page/search/index.js
ui/page/search/view.jsx

Remove Premium+ Tiles when Premium+ is active

Remove Premium+ Tiles when Premium+ is active

---

ui/component/viewers/videoViewer/internal/videojs.jsx

If there's no mouse (aka fine pointer) then don't load image preview thunbnails

Don't run image preview if there's no mouse

---

ui/component/commentsList/view.jsx

Issue Number: closes #1509 
Now properly fetches the right page for the given claim when switching

Fix comment list when switching claims

---

ui/component/viewers/videoViewer/internal/plugins/videojs-mobile-ui/plugin.scss

Fix touch overlay max-height on mobile

---

ui/scss/component/_ads.scss
ui/scss/component/_claim-list.scss
ui/scss/init/_gui.scss

Running on `inf` ... seems to be ok

Remove relative paths in sass

---

static/app-strings.json
ui/component/userChannelFollowIntro/view.jsx
ui/constants/channels.js
ui/page/discover/livestreamSection.jsx
ui/page/odyseeMembership/view.jsx
ui/redux/actions/user.js

Misc list of cleanup

---

ui/component/commentsList/view.jsx

Fix comment sort change

---

ui/component/claimList/view.jsx

Issue Number: closes #1548, closes #1047

Fix Drag-and-drop error

---

static/app-strings.json
ui/component/claimPreview/index.js
ui/component/claimPreview/view.jsx
ui/component/claimPreviewTile/index.js
ui/component/claimPreviewTile/view.jsx
ui/page/show/view.jsx

Additional geoblock support

---

.flowconfig
extras/recsys/recsys.js
flow-typed/Claim.js
flow-typed/recsys.js

No functional change -- mainly to help make the next task easier through the type safest and reference.
Flow fixes: opted to do either "safe" fixes, or suppress them for now to avoid invalidating any existing recsys data set.

Recsys: add flow and fix uncovered issues

---

ui/component/app/index.js
ui/component/app/view.jsx
ui/component/channelSelector/index.js
ui/component/channelSelector/view.jsx
ui/redux/actions/settings.js

Automatically set default channel on sign up

---

ui/page/show/view.jsx

Closes [#1539 "no content found" flicker on direct page loads](https://github.com/OdyseeTeam/odysee-frontend/issues/1539)
See commit messages for details

Show-page: fix "no content found" flicker 

---

ui/redux/selectors/claims.js
ui/redux/selectors/comments.js
ui/util/geoRestriction.js

Leave unsquashed please.
Performance was a concern, but seems to be on par with existing version, so I guess the extra loop is not so bad.

Comments: filter geo-blocked channels

---

ui/scss/component/_claim-list.scss

Addresses the issue using a css media interaction
https://caniuse.com/css-media-interaction
Closes [#544 iPad: need to double click on tile](https://github.com/OdyseeTeam/odysee-frontend/issues/544)

Fix hover bug on iPad requiring double click

---

ui/component/app/view.jsx

Fix wait for prefs on default channel set

---

ui/analytics.js
ui/constants/storage.js
ui/redux/actions/app.js
ui/redux/actions/livestream.js
ui/redux/actions/user.js
ui/redux/selectors/user.js
ui/util/storage.js
ui/util/tus.js
web/component/ads/view.jsx

Closes #1572
- Consolidated the keys into one place for easier tracking.
- It'll also be easier to code using constant autocomplete.
- Cleaned up the wrapper to be as close to the original function prototype.
- Updated existing code to use the wrapper (even if they already handled the availability) to encourage future code to just use the wrapper.

Fix localStorage crash

---

flow-typed/homepage.js
static/app-strings.json
ui/component/homepageSort/view.jsx
ui/component/sideNavigation/view.jsx
ui/constants/homepage_languages.js
ui/modal/modalCustomizeHomepage/index.js
ui/modal/modalCustomizeHomepage/style.scss
ui/modal/modalCustomizeHomepage/view.jsx
ui/page/home/helper.jsx
ui/page/home/view.jsx
ui/util/buildHomepage.js

`INF` instance
(miko?)
Closes [#1536 Custom-homepage: can't select "News" and "Wild West" + add "Default Config"](https://github.com/OdyseeTeam/odysee-frontend/issues/1536)
Expand commit messages for details

Homepage: add "reset" + 'hideByDefault' categories

---

web/src/rss.js

Users are seeing timeout with the RSS calls.
- Before:
- <img width="500" alt="image" src="https://user-images.githubusercontent.com/64950861/170643095-0115fe92-a98a-41da-8f92-776dad08b094.png">
- After:
- <img width="500" alt="image" src="https://user-images.githubusercontent.com/64950861/170643155-cd3a332d-5ed8-4e17-9a61-1943f2f477b7.png">
Even before this PR, `inf` seems to produce the results significantly faster than odysee.com.  
CF messing things up?

RSS: parallel-fetch the stream urls

---

ui/component/app/index.js
ui/component/app/view.jsx
ui/component/channelContent/view.jsx
ui/effects/use-ad-outbrain.js
ui/effects/use-should-show-ads.js
ui/page/discover/view.jsx
ui/page/home/index.js
ui/page/home/view.jsx
ui/scss/component/_ads.scss
web/component/ads/view.jsx
web/component/adsBanner/index.js
web/component/adsBanner/view.jsx

Test:  `kp`
List of changes:  see commit messages

Adnimation

---

ui/component/viewers/videoViewer/index.js
ui/component/viewers/videoViewer/internal/videojs-events.jsx
ui/component/viewers/videoViewer/internal/videojs.jsx
ui/component/viewers/videoViewer/view.jsx

Integrate media session api into our player. This allows us to set the media meta & controls for the browser media controls.

Media Session API integration

---

ui/page/home/view.jsx

https://odysee-workspace.slack.com/archives/C02G20Z2AEL/p1653779545610999

Don't limit livestreams for Following section

---

flow-typed/search.js
ui/component/searchOptions/view.jsx
ui/constants/search.js

Code change, no behaviour change
Code change, no behaviour change
</details>

Fix spelling of SORT_ASCENDING in search constants

---

ui/effects/use-should-show-ads.js
ui/page/home/view.jsx

Ad: premium+ check

---

ui/component/claimList/view.jsx
ui/component/claimTilesDiscover/view.jsx

This fixes the uneven grid with multiple injections like the ones we use with the new ad provider.

Fix grid with adnimation

---

ui/component/publishForm/view.jsx
ui/component/viewers/videoViewer/internal/plugins/videojs-http-streaming--override/playlist-selectors.js
ui/component/viewers/videoViewer/internal/plugins/videojs-mobile-ui/plugin.scss
ui/scss/component/_ads.scss
ui/scss/component/_channel.scss
ui/scss/component/_content.scss
ui/scss/component/_file-render.scss
ui/scss/component/_form-field.scss
ui/scss/component/_main.scss
ui/scss/component/_modal.scss
ui/scss/component/_videojs.scss
ui/scss/init/_gui.scss

Design patch 22-05-31

---

ui/scss/component/_nudge.scss

Issue Number:
#1596 
Fixed bubble misplacing on width change.
- [ x ] Bugfix
- [ x ] Code style update (formatting)
- [ x ] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
</details>

Fix Bubble misplace

---

ui/scss/component/_ads.scss

Fix close button in adnim footer banner

Fix close button in footer banner

---

ui/scss/init/_gui.scss

Design patch 22 06 01

---

ui/scss/component/_modal.scss

Adjust toggle buttons in modal

Adjust toggle buttons in modal

---

extras/recsys/recsys.js
flow-typed/recsys.js
ui/component/recommendedContent/view.jsx
ui/redux/selectors/search.js
ui/util/search.js

Reverts OdyseeTeam/odysee-frontend#1616

Revert "Recsys: determine the clicked index based on raw results instead of rendered order"

---

ui/scss/component/_button.scss
ui/scss/component/_content.scss
ui/scss/component/_file-render.scss
ui/scss/component/_videojs.scss

Realign & adjust player icons

---

ui/component/headerMenuButtons/index.js
ui/component/headerMenuButtons/view.jsx
ui/component/headerProfileMenuButton/view.jsx
ui/scss/component/_header.scss
ui/scss/component/menu-button.scss

Rearrange header navigation items

Restructure header navigation

---

ui/component/viewers/videoViewer/internal/plugins/videojs-http-streaming--override/playlist-selectors.js
ui/scss/component/_button.scss
ui/scss/component/_file-render.scss
ui/scss/component/_videojs.scss

Fix player icon size & position on Desktop & Mobile.

Player icons patch

---

ui/scss/component/_button.scss
ui/scss/component/_file-render.scss
ui/scss/component/_videojs.scss

- Resolve player icon hover conflict

Resolve player icon hover conflict

---

ui/scss/component/_ads.scss
ui/scss/component/_claim-list.scss
web/component/adsBanner/view.jsx

Replace current adnim solution with a more dynamic one.
- Dynamic number of tiles (1, 3, 4 & 6)
- Dynamic mode (Desktop, Mobile)
- New theme
Known issues
- The last two widgets on the homepage only show 1 tile for KP. I wasn't able to find out why. It seems to work for everybody else.

Adnim patch

---

web/component/ads/view.jsx

Also placed both tag ids in case one breaks again.

Switch to file-page ad until Adnim fixes the script

---

ui/component/headerNotificationButton/index.js
ui/component/headerNotificationButton/view.jsx
ui/component/headerProfileMenuButton/view.jsx
ui/scss/component/_notification.scss
ui/scss/component/menu-button.scss

This PR adds a drop-down menu to the notification button.

Notification menu

---

ui/component/channelContent/view.jsx
ui/effects/use-fetch-live.js
ui/page/livestream/view.jsx
ui/redux/actions/livestream.js

Remove polling

---

static/app-strings.json
ui/component/headerNotificationButton/view.jsx
ui/component/notificationBubble/index.js
ui/component/notificationBubble/view.jsx

- Rename components per filename changes.
- Fix missing React key.
- Add new strings.

Notification-popup patch

---

ui/component/headerNotificationButton/view.jsx
ui/scss/component/menu-button.scss

Update notification menu
- Increase number of notifications to 20
- Add scrollbar
- Hide channel badge in title

Update notification menu

---

ui/scss/component/_button.scss
ui/scss/component/_header.scss
ui/scss/component/_modal.scss
ui/scss/component/_wunderbar.scss

- Add open animation to modals
- Improve & fix modal layout on mobile

Animate modals & improve modal layout on mobile

---

ui/page/channel/index.js
ui/page/channel/view.jsx
ui/scss/component/_channel.scss

Change premium badge position on channel pages

Change premium badge position on channel page

---

ui/component/claimList/view.jsx

Fix missing tile in full grid

---

ui/scss/init/_gui.scss

Add transform exception for lightbox modal.

Add transform exception for lightbox modal

---

ui/component/fileRenderFloating/view.jsx
ui/scss/component/_content.scss

Parts of the draggable component can block the controls of the mini player. I've removed the entire component for the mini player on mobile.

Mini-Player controls patch

---

ui/page/livestream/view.jsx
ui/redux/reducers/livestream.js

Bugfix issue that Raphael pointed out today

Bugfix live status state

---

ui/component/viewers/videoViewer/internal/videojs.jsx
ui/effects/use-thumbnail.js

Addresses: https://github.com/OdyseeTeam/odysee-frontend/issues/1665
And another issue Miko pointed out (poster not available on first play of audio file)

Fix poster bugs

---

ui/component/headerNotificationButton/view.jsx

Add `href` links to notification menu entries.

Add href links to notification menu entries

---

ui/scss/component/_ads.scss
web/component/adsSticky/view.jsx

Inject close button into footer banner ad

Inject close button into footer banner ad

---

ui/component/claimCollectionAdd/view.jsx
ui/modal/modalSocialShare/view.jsx
ui/scss/component/_card.scss

Minor design fixes in modals

---

ui/component/viewers/videoViewer/internal/videojs.jsx

Addresses https://github.com/OdyseeTeam/odysee-frontend/issues/1708 and also a bug Miko pointed out to me
Miko tested and should be OK for a merge

Bugfix streams continuing to run in the background

---

web/component/ads/view.jsx

Reverts OdyseeTeam/odysee-frontend#1719

Revert "Undo the hardcoded ad div id"

---

ui/component/headerNotificationButton/index.js
ui/component/headerNotificationButton/view.jsx
ui/component/notificationBubble/view.jsx
ui/scss/component/_notification.scss
ui/scss/component/menu-button.scss

- ~Mark notifications in dropdown as seen on hover.~
- Increase dot size
- Mark all notifications as seen on button click

Notification Menu Upgrade

---

ui/component/claimPreview/view.jsx
ui/component/fileActions/index.js
ui/component/fileActions/view.jsx
ui/component/preorderButton/index.js
ui/component/preorderButton/view.jsx
ui/component/preorderContent/index.js
ui/component/preorderContent/view.jsx
ui/component/walletFiatAccountHistory/index.js
ui/component/walletFiatAccountHistory/view.jsx
ui/component/walletFiatPaymentHistory/view.jsx
ui/constants/modal_types.js
ui/modal/modalPreorderContent/index.js
ui/modal/modalPreorderContent/view.jsx
ui/modal/modalRouter/view.jsx
ui/page/file/view.jsx
ui/redux/actions/wallet.js
ui/redux/selectors/claims.js
ui/scss/all.scss
ui/scss/component/_preorder-button.scss

Allows a user to set a preorder purchase

Preorder content functionality

---

extras/recsys/recsys.js
flow-typed/recsys.js
ui/component/viewers/videoViewer/internal/plugins/videojs-recsys/plugin.js
ui/component/viewers/videoViewer/view.jsx

Ticket: closes #1751
Details: see commit notes

Recsys: fix resumed-send missing `totalPlayTime`

---

package.json
ui/component/fileActions/index.js
ui/component/preorderButton/index.js
ui/component/preorderButton/view.jsx
ui/component/preorderContent/index.js
ui/component/preorderContent/view.jsx
ui/redux/selectors/claims.js

Only thing not done is the `prettify` solution pending some discussion with KP on how to do it outside of `lint-staging`

Preorder button touchups

---

ui/component/viewers/videoViewer/internal/chapters.jsx
ui/component/viewers/videoViewer/internal/videojs.jsx
ui/component/viewers/videoViewer/view.jsx

Because of the change of how the video player is loaded could use some testing, chapter button fix and current time not updating fast enough also included

Don't dispose switching between video/livestream, chapter button fix, current time not updating quickly fix

---

ui/component/fileReactions/view.jsx

Crash when reacting while Google Translate is active.
https://github.com/facebook/react/issues/11538#issuecomment-390386520

FileReactions: make it robust against external DOM manipulation

---

ui/component/youtubeTransferStatus/view.jsx
ui/scss/component/_ads.scss
ui/scss/component/_comments.scss
ui/scss/component/_livestream-chat.scss
ui/scss/component/_main.scss
ui/scss/component/_wunderbar.scss
ui/scss/component/nag.scss
ui/scss/component/section.scss
ui/scss/init/_gui.scss

Design Patch 2022-06

---

ui/redux/actions/rewards.js

Remove 'many_downloads' auto-claim (let user manually claim)

---

ui/component/livestreamChatLayout/livestream-menu.jsx
ui/component/livestreamChatLayout/view.jsx

Fix Livestream Popout Chat not refreshing when popout window closed

---

web/setup/publish-v2.js

Reverts OdyseeTeam/odysee-frontend#1808

Revert "tus: Fix `upload not found` scenario"

---

ui/page/collection/internal/collectionPublish/view.jsx

> _:warning: This goes into `playlist-v2` branch instead of `master` due to large conflicts.  Does not block the playlist PR -- can ship together or wait._
For a large list, the playlist publish form is unusable (super-slow typing) due to the entire list being mounted despite the Items tab is not active.
The full solution is still to paginate it, but for now, don't mount the tab until it is selected. Add a spinner to indicate something is loading. It's not prefect, but it's throwaway code anyway. At least we can fill in the fields properly now.

PublishList: delay mounting Items tab to prevent lock-up

---

ui/component/comment/view.jsx

Primarily for the upcoming Report Comment feature.

Comment: add `hideContextMenu` + hide reply button too when `hideActions` is set

---

.env.defaults
config.js
ui/redux/actions/app.js

Patches d16ae73c
See commit message for details

(patch) Don't nudge to refresh in localhost

---

ui/page/odyseeMembership/view.jsx

This supports the new way the backend API returns the membership options

Update frontend to work with new API response

---

ui/page/odyseeMembership/view.jsx

Revert "Update frontend to work with new API response"

---

.env.defaults
flow-typed/publish.js
web/setup/publish-error.js
web/setup/publish-v1.js
web/setup/publish-v2.js
web/setup/publish.js

Patch for d41b9ff1
- Extend to remaining areas (both v1 and v2).
- XHR: Add few more status details.
- TUS: Add retry attempt count.
- TUS: Add file size (via fingerprint).
Bumped MINIMUM_VERSION to force a refresh.

(patch) Publish: add additional info in the error log

---

ui/component/livestreamLayout/view.jsx
ui/component/playlistCard/view.jsx

Fix live chat and empty queue opening by default on file pages

---

flow-typed/content.js
ui/component/commentsList/index.js
ui/component/commentsList/view.jsx
ui/component/common/expandable.jsx
ui/component/common/markdown-preview.jsx
ui/component/fileRenderFloating/index.js
ui/component/fileRenderFloating/view.jsx
ui/component/fileRenderInitiator/view.jsx
ui/component/livestreamComment/view.jsx
ui/component/markdownLink/view.jsx
ui/component/viewers/videoViewer/index.js
ui/component/viewers/videoViewer/internal/effects/use-autoplay-next.js
ui/component/viewers/videoViewer/view.jsx
ui/redux/actions/content.js
ui/redux/reducers/content.js
ui/redux/selectors/content.js

Issue Number: closes #1818
- `isMarkdownPost` was never being passed down
- also fixed how it identifies if it's floating on the same page but different tab (markdown on channel discussion vs switching to videos etc should start floating)

Fix markdown floating case

---

ui/modal/modalError/view.jsx
ui/redux/actions/publish.js
web/setup/publish-error.js
web/setup/publish-v2.js

Publish: various logging changes

---

ui/effects/use-should-show-ads.js

Closes #1868
Multiple pings on google's ad url due to all In-content ads being mounted at the same time.
The locking mechanism was lost when the result was moved to Redux.

Restore ad-detection single call "lock"

---

ui/component/fileRenderInitiator/index.js
ui/component/fileRenderInline/index.js
ui/redux/selectors/content.js

fix: isPlaying selector comparing wrong uris

---

ui/component/comment/view.jsx

fix: clearPlayingUri is not a function error

---

ui/redux/selectors/publish.js

Fix null or undefined being passed on collection publish params

---

ui/component/publish/post/postForm/view.jsx

Closes #1846
Form allowed to publish despite having name and other errors

Post: disable button if form is invalid

---

ui/scss/component/_content.scss
ui/scss/component/section.scss

Fix floating player button contact areas

---

web/src/html.js

Reverts OdyseeTeam/odysee-frontend#1898

Revert "Fix Escape html property on ctx.query"

---

ui/component/app/view.jsx
ui/component/sideNavigation/view.jsx
ui/page/home/index.js
ui/page/home/view.jsx
ui/scss/component/_ads.scss
web/component/ads/view.jsx
web/component/adsBanner/view.jsx
web/component/adsSticky/index.js
web/component/adsSticky/view.jsx

- Removed "in-content"
- Replaced "sticky" with the slightly less-intrusive "read next".

Ad improvements

---

ui/component/fileRenderInitiator/index.js
ui/component/fileRenderInitiator/view.jsx

Allow uploaders to view own paid content

---

ui/component/preorderButton/index.js
ui/component/preorderButton/view.jsx
ui/component/viewers/videoViewer/internal/videojs.jsx
ui/page/file/index.js
ui/page/file/view.jsx
ui/redux/actions/claims.js
ui/redux/reducers/claims.js
ui/redux/selectors/claims.js

Touchup redux and call customer list if it's a preorder

Touchup redux

---

ui/component/preorderContent/view.jsx

Assume the user has no card by default

Set card as unsaved by default

---

ui/component/preorderButton/view.jsx
ui/component/viewers/videoViewer/internal/videojs.jsx

Allow player to use transcoded secured content

Fix transcoded secured urls

---

extras/lbryinc/lbryio.js
extras/lbryinc/redux/actions/blacklist.js
extras/lbryinc/redux/actions/filtered.js

Includes "Use 'get' for file/list_* to handle CF caching issues"
Closes #1947

Default api calls from 'get' to 'post' (attempt 2)

---

ui/scss/component/_careers.scss
web/page/careers/itProjectManager/view.jsx
web/page/careers/view.jsx

Just some minor design adjustments...

Redesign career pages

---

flow-typed/publish.js
ui/redux/actions/publish.js

Pass claim_id to form edit as requested in #1858.

Pass claim_id to edit payload

---

ui/component/viewers/videoViewer/internal/plugins/videojs-mobile-ui/plugin.scss

Fixes an isssue where the loading spinner on embedded uploads is off

fix spinner for embedded videos

---

ui/modal/modalPublishPreview/view.jsx

Update label in publish confirmation modal.

Adjust labels in publish confimration modal

---

ui/component/channelSections/SectionList/style.scss

Update channels tab scss on channel page

Update channels tab scss on channel page

---

ui/component/claimListHeader/view.jsx

Disables auto-expansion of content filters if settings are changed.

Don't open filters by default

---

ui/component/fileRenderInitiator/index.js
ui/component/fileRenderInitiator/view.jsx
ui/scss/component/_claim-list.scss

rental fixes

---

ui/component/snackBar/view.jsx
ui/page/channel/view.jsx
ui/scss/component/_snack-bar.scss

Replace stacked snackbar indicator with counter.

Add counter to snackbar

---

ui/component/channelSelector/view.jsx
ui/scss/component/_channel.scss

Make channel selector dropdown consistent across entire site

Make channel selector dropdown consistent across entire site

---

ui/component/headerMenuButtons/index.js
ui/component/headerMenuButtons/view.jsx
ui/component/publish/shared/publishAdditionalOptions/view.jsx
ui/component/publish/shared/publishPending/view.jsx
ui/scss/component/_channel.scss
ui/scss/component/_comments.scss
ui/scss/component/_file-render.scss
ui/scss/component/_modal.scss
ui/scss/init/_gui.scss

Fixing #2004 + some design stuff
The licence field did not update in edit mode when switched to "copyright" without manually setting `otherLicenseDescription` as well. This patch sets it to "All rights reserved" by default.

Licence field

---

ui/modal/modalClaimCollectionAdd/internal/claimCollectionAdd/internal/collectionSelectItem/view.jsx

Channel-sections are not meant to appear outside of Channel Pages.

Hide channel-sections from the "Save to..." dialog

---

.sentryclirc
ui/analytics/sentryWrapper.js
web/webpack.config.js
yarn.lock

These are safe/minor fixes that doesn't require much review/testing. 
Isolating into separate PR as the next one would require scrutiny.  Will submit that one after a day of hang time + testing.

Incremental sentry fixes

---

.gitignore
package.json
ui/analytics.js
ui/analytics/sentryWrapper.js
web/webpack.config.js
yarn.lock

Sentry: upload source-map to resolve stack trace

---

ui/component/commentMenuList/index.js
ui/component/commentMenuList/view.jsx
ui/redux/actions/comments.js
ui/scss/component/_comments.scss

Fix moderator context menu in chat (#1907).

Chat patch

---

ui/analytics/sentryWrapper.js

Not sure why the `whitelistUrls` aren't working for this case.

Sentry: skip aniview issues

---

web/src/push-notifications/push-supported.js

Handle push-notification init exceptions

---

ui/redux/middleware/auth-token.js
ui/redux/middleware/batch-actions.js
ui/redux/setup/persistedState.js
ui/redux/setup/sharedState.js
ui/store.js

Moved supporting code to their respective folders for easier maintenance as the number of middleware and supporting code is getting larger.

Re-organized redux setup code

---

ui/component/button/index.js
ui/component/button/view.jsx
ui/component/preorderAndPurchaseContentCard/view.jsx
ui/component/walletTipAmountSelector/view.jsx
ui/page/odyseeMembership/view.jsx
ui/page/settingsStripeAccount/index.js
ui/page/settingsStripeAccount/view.jsx
ui/redux/selectors/stripe.js

Issue Number: closes #2066, closes #2069
- 41c1ce6817442722b28064321b7873e61c7bb51a fixes double `link` calls on bank account page

Stripe: fallout fixes

---

web/component/ads/view.jsx

per request from Amir -- but it's weird since we never added it before.
I assume this is what "separate" means.

Additional aniview tag

---

ui/component/viewers/videoViewer/internal/videojs-events.jsx

Livestream: Reset playbackrate on live edge

---

ui/component/viewers/videoViewer/internal/videojs-events.jsx

Livestream: live tracker visibility change

---

yarn.lock

Fix vtt `replaceAll` failures in older browsers

---

ui/redux/selectors/stripe.js

fix(#2093): account requires verification state

---

ui/analytics/watchman.js
ui/component/viewers/videoViewer/internal/videojs-events.jsx

Handle null vhs playlist media

---

ui/scss/component/_header.scss
ui/scss/component/_main.scss
ui/scss/component/_videojs.scss
ui/scss/component/tabs.scss
ui/scss/init/_gui.scss
web/page/tos/view.jsx
web/page/youtubetos/view.jsx

Fix remaining issues in #1986.

Design Patch August

---

ui/component/app/view.jsx

`wrapperElement` as a `ref` would never trigger the useEffect

fix: React element error when opening modals

---

ui/component/fileReactions/index.js
ui/redux/actions/reactions.js
ui/redux/selectors/reactions.js

Closes #2078
The fix just involves checking against both null and undefined (instead of just null)
While at it, fix the incorrect `makeSelect*` usage, since it was relatively easy to test.

Fix undefined reaction handling

---

static/app-strings.json
ui/component/settingLanguage/view.jsx
ui/effects/use-persisted-state.js
ui/i18n.js
ui/page/settings/index.js
ui/page/settings/view.jsx
ui/redux/actions/settings.js
ui/redux/reducers/settings.js
ui/redux/setup/persistedState.js
ui/util/storage.js
ui/util/zoomWindow.js

Closes [#921 language refresh / selection issues](https://github.com/OdyseeTeam/odysee-frontend/issues/921) -- including the localStorage problems mentioned.
- See commit messages for walkthrough.
- :warning: The last commit involves a behavioral change. I think it's for the better, but we can omit it if majority dislikes.

localStorage + language fixes

---

ui/component/comment/view.jsx
ui/modal/modalRemoveComment/view.jsx

Don't obscure slimed comment in removal modal

---

static/app-strings.json
ui/component/settingLanguage/view.jsx
ui/effects/use-persisted-state.js
ui/i18n.js
ui/page/settings/index.js
ui/page/settings/view.jsx
ui/redux/actions/settings.js
ui/redux/reducers/settings.js
ui/redux/setup/persistedState.js
ui/util/storage.js
ui/util/zoomWindow.js

Reverts OdyseeTeam/odysee-frontend#2118

Revert "localStorage + language fixes"

---

static/app-strings.json
ui/page/show/index.js
ui/page/show/view.jsx

Closes #1945
Only show the following message ...
```
lbry://@xxx#6/xxx#f
This content violates the terms and conditions of Odysee and has been filtered.
```
... and block all buttons and widgets. If the user wants to delete, they can do so from the Uploads Page.
:warning: Check grammar

FilePage: handle display of filtered content

---

static/app-strings.json
ui/component/claimListHeader/index.js
ui/component/claimListHeader/style.scss
ui/component/claimListHeader/view.jsx
ui/page/discover/index.js
ui/page/discover/view.jsx

ClaimListHeader: Restore tag filter + enter query directly

---

ui/component/sideNavigation/view.jsx
ui/scss/component/_navigation.scss

Sidebar: indicate there are more subscriptions

---

static/index-web.html

Add role="application" to main div (web)

---

web/component/ads/view.jsx

Giant ads when transition from certain pages.
- Vendor addresses
- There are lots of console errors, but probably not show stopper.

Fixed giant video ads

---

ui/component/channelDiscussion/index.js
ui/component/channelDiscussion/view.jsx
ui/component/commentCreate/index.js
ui/component/commentCreate/view.jsx
ui/component/commentsList/index.js
ui/component/commentsList/view.jsx
ui/component/livestreamLayout/index.js
ui/constants/tags.js
ui/page/file/index.js
ui/page/file/view.jsx
ui/page/livestream/index.js
ui/page/livestream/view.jsx
ui/page/show/index.js
ui/page/show/view.jsx
ui/redux/selectors/comments.js

Fix: disabled comments setting

---

ui/page/file/index.js

Restored original code from c36fd425. Don't think duration is re-used anywhere else anymore

Fix crashing duration

---

ui/component/uriIndicator/view.jsx
ui/scss/component/_channel.scss
ui/scss/component/_claim-list.scss
ui/scss/component/tabs.scss

Fix claim preview layout on mobile.

Fix multiple issues in claim preview layout on mobile

---

static/index-web.html

see https://github.com/OdyseeTeam/odysee-frontend/pull/2175#issuecomment-1256247293

Revert "Add role="application" to main div (web)"

---

ui/component/channelContent/view.jsx
ui/component/claimListDiscover/view.jsx
ui/page/channelsFollowing/view.jsx
ui/page/discover/view.jsx
ui/util/search.js

Closes #2186
See commits for details

TagSearch updates

---

ui/component/app/index.js
ui/component/app/view.jsx
ui/component/invited/index.js
ui/component/invited/view.jsx
ui/component/router/index.js
ui/component/router/view.jsx
ui/modal/modalSetReferrer/index.js
ui/modal/modalSetReferrer/view.jsx
ui/page/embedWrapper/index.js
ui/page/embedWrapper/view.jsx
ui/page/livestream/index.js
ui/page/livestream/view.jsx
ui/redux/actions/user.js
ui/redux/selectors/claims.js
ui/util/claim.js

Issue Number: closes #2190 & fixes https://sentry.odysee.tv/organizations/odysee/issues/30326/?project=2&query=is%3Aunresolved

Fallout embed fixes

---

ui/component/claimPreview/index.js
ui/component/claimPreviewTile/index.js
ui/component/fileActions/index.js
ui/component/fileDownloadLink/index.js
ui/component/fileRender/index.js
ui/component/fileRenderFloating/index.js
ui/component/fileRenderInline/index.js
ui/component/postEditor/index.js
ui/page/embedWrapper/index.js
ui/page/embedWrapper/view.jsx
ui/page/file/index.js
ui/page/file/view.jsx
ui/redux/actions/content.js
ui/redux/actions/file.js
ui/redux/reducers/file_info.js
ui/redux/selectors/claims.js
ui/redux/selectors/file_info.js

Issue Number: closes #2198 closes #2206

fix: streaming url changes and add fileGet on embedWrapper

---

ui/component/viewers/videoViewer/internal/plugins/videojs-http-streaming--override/playlist-selectors.js

Closes #1817
> _Livestreams: it will try to switch between resolutions and because the different resolutions may be a second or two off (and there's a 1 sec cache on m3u8s), it may seem like parts of the video are repeated or buffer at that time._
Not sure whether to combine into `kp` now, or test one thing at a time. Might need stashu for this.
Tweak the algorithm to stash the first-found rendition and re-use that for the same stream.
If user changes away from auto, the stash is cleared. If auto is selected again, it will stash the first-found rendition again.
- There is an option to disregard player dimensions in the algorithm. But I don't think that's the cause for the jumping-around since we aren't resizing the player much. Mostly network bandwidth, I think.
- Sometimes, dev tools is …

Livestream: use first-found rendition for Auto

---

ui/component/viewers/videoViewer/internal/plugins/videojs-watchdog/plugin.js
ui/component/viewers/videoViewer/internal/videojs-events.jsx
ui/component/viewers/videoViewer/internal/videojs.jsx

Closes #1361
Test: `kp` 
- Probably need some testing since this is not a fool-proof way.
- Reproduction is also very hard.
Details: see commit message

Livestream watchdog to reload when stuck buffering

---

ui/component/settingsStripeCard/view.jsx
ui/scss/component/_stripe-card.scss
ui/scss/init/_gui.scss

fix: stripe script null case

---

ui/component/viewers/videoViewer/internal/videojs-events.jsx

MediaSession thumbnail called without proxy

---

ui/redux/selectors/memberships.js

- This gets it loading for signed-out case, but it's still not working for signed in + no premium case.

Partial fix for missing ads

---

static/app-strings.json
ui/page/creatorMemberships/creatorArea/internal/tabWrapper/view.jsx

Membership: move error messages

---

ui/component/chat/chatComment/view.jsx
ui/component/comment/index.js
ui/component/comment/view.jsx
ui/component/commentMenuList/view.jsx
ui/component/common/credit-amount.jsx
ui/modal/modalRemoveComment/view.jsx
ui/scss/component/_comments.scss
ui/scss/component/_file-render.scss
ui/scss/component/_livestream-chat.scss
ui/scss/component/_livestream-comment.scss

- Realign & resize comments & chat messages.
- Add sprouts to the comments

Chat & comment patch

---

ui/component/joinMembershipCard/view.jsx

Membership: index of 0 is false

---

ui/component/collectionGeneralTab/view.jsx
ui/page/collection/internal/collectionPublish/index.js
ui/page/collection/internal/collectionPublish/view.jsx
ui/redux/selectors/app.js

Playlist: can't publish collection with activeChannelClaim === null

---

ui/modal/modal.jsx
ui/modal/modalFeaturedChannelsEdit/style.scss
ui/modal/modalFeaturedChannelsEdit/view.jsx
ui/modal/modalSendTip/view.jsx
ui/scss/component/_button.scss
ui/scss/component/_modal.scss
ui/scss/init/_vars.scss

See commit message
Pre-reviewed with Rave.

Restore original modal width + add wide options

---

flow-typed/homepage.js
ui/component/claimListDiscover/view.jsx
ui/component/claimTilesDiscover/index.js
ui/component/claimTilesDiscover/view.jsx
ui/page/discover/view.jsx
ui/util/buildHomepage.js

currently featured only has it set, at 60+ seconds

Use duration from homepage if available

---

flow-typed/Lbry.js
flow-typed/claimSearch.js
ui/component/claimListDiscover/view.jsx
ui/component/claimTilesDiscover/index.js
ui/redux/actions/claims.js
ui/util/claim.js

Just affects flow-check -- avoided making functional changes (by ignoring flow errors) to keep status quo and reduce testing to 0.
Will revisit those warnings one day.

Add type for claim_search options

---

ui/component/commentCreate/comment-selectors.jsx

Small part of #2180 
It was just missing the `loading="lazy"` flag

Lazy-load twemoji categories

---

ui/component/notification/view.jsx

fix: read notification

---

ui/page/file/view.jsx
ui/redux/actions/content.js

Issue Number: closes #2275 closes #1915

Playlist: Mature fixes

---

web/component/adsSticky/view.jsx

Remove ads from sensitive pages like...
- reset
- resetpassword
- verify 
- walletpassword

Remove ads from sensitive pages

---

ui/component/commentCreate/comment-selectors.jsx

All emoji image files are being fetched on F5 (#2180)
- Something is causing `loading="lazy"` to not work reliably. I'm guessing it's due to ReachUI's Tab, or it just doesn't support a tabbed scenario.
- Also, EmojisPanel and StickersPanel currently requires all emojis to be mounted for the "scroll to category" to work correctly.
Until those components support pagination, alleviate the problem by not mounting the emojis until the panel is opened.
While all the images are still being fetched when the panel is opened, at least it is not loaded on F5 where most people aren't commenting directly.
One downside to the approach is that there will be a lag when opening the panel for the very first time. Subsequent ones would be fine.

Alleviate emoji img loading

---

static/app-strings.json
ui/component/fileDownloadLink/index.js
ui/component/fileDownloadLink/style.scss
ui/component/fileDownloadLink/view.jsx
ui/redux/actions/file.js
ui/util/downloadClaim.js

Allows downloading of protected static file and prompts you to buy a membership if you don't have access

Add functionality around protected static content

---

ui/component/viewers/videoViewer/internal/videojs-events.jsx
ui/component/viewers/videoViewer/internal/videojs-shortcuts.jsx
ui/component/viewers/videoViewer/internal/videojs.jsx

Allows a user to skip forward or backwards a frame using either the comma or period keyboard shortcut.
Offered by YouTube, part of moving closer to YouTube feature parity
https://support.google.com/youtube/answer/7631406?hl=en

Use comma or period button to step a frame forward or backward

---

ui/component/channelSections/FeaturedChannelsEdit/view.jsx
ui/page/collection/internal/collectionActions/internal/deleteButton/index.js
ui/page/collection/internal/collectionActions/internal/publishButton/index.js
ui/page/collection/internal/collectionHeader/index.js
ui/page/collection/internal/collectionPublish/view.jsx
ui/redux/actions/collections.js
ui/redux/actions/content.js

Playlist: fix null items

---

ui/component/publish/livestream/livestreamForm/view.jsx
ui/page/creatorMemberships/creatorArea/internal/tiersTab/internal/editingTier/view.jsx
ui/page/creatorMemberships/creatorArea/internal/tiersTab/view.jsx
ui/redux/actions/memberships.js

Fixes bug where the order of tiers is out of sync when a tier is edited
Fixes: 
#2303
#2293

Bugfix tier edit

---

ui/component/publishProtectedContent/view.jsx

Fix bug when colors were incorrect while selecting tiers

---

web/src/getHomepageJSON.js

portal homepage data

---

ui/component/viewers/videoViewer/internal/plugins/videojs-snapshot-button/plugin.js

Fixes bug where snapshot button can't save file because of emoji present

Strip emojis for snapshot button

---

ui/modal/modalPublishPreview/index.js
ui/modal/modalPublishPreview/view.jsx

Tier colors were off here, this fixes it

Fix tier colors on tier preview confirmation

---

ui/scss/component/_ads.scss
ui/scss/component/_channel.scss
ui/scss/component/_comments.scss
ui/scss/component/_membership.scss
ui/scss/component/_snack-bar.scss
ui/scss/init/_gui.scss
web/component/ads/view.jsx

October Patch https://github.com/OdyseeTeam/odysee-frontend/issues/2226

Design patch

---

ui/component/viewers/videoViewer/internal/plugins/videojs-snapshot-button/plugin.js

Fix race condition where CORS wouldn't be set in time for the button

Fix race condition with snapshot button

---

ui/component/walletFiatBalance/view.jsx

Pending cash balance is broken, this fixes it

dont show broken pending balance

---

ui/component/filePrice/view.jsx

fix: extra odd 0 on embed titles

---

ui/component/claimPreview/view.jsx
ui/component/claimPreviewTile/view.jsx
ui/component/fileThumbnail/index.js
ui/component/fileThumbnail/view.jsx
ui/page/playlists/index.js
ui/page/playlists/internal/collectionsListMine/index.js
ui/page/playlists/internal/collectionsListMine/internal/collectionPreview/view.jsx
ui/page/playlists/internal/collectionsListMine/view.jsx
ui/page/playlists/view.jsx
ui/redux/actions/claims.js
ui/redux/reducers/claims.js
ui/redux/selectors/collections.js

Issue Number: closes #2345
live on https://salt.odysee.com

Playlist fallout

---

ui/component/embedTextArea/view.jsx

fix: autoplay checkmarks have the same form-name

---

flow-typed/publish.js
ui/redux/actions/memberships.js
ui/redux/actions/publish.js

Still pending some testing, not ready for a merge yet
Update: Can be merged now

Pass claim name while saving member_content

---

ui/redux/selectors/content.js

fix: comparing wrong page uri

---

ui/component/previewOverlayProtectedContent/index.js
ui/component/previewOverlayProtectedContent/view.jsx
ui/redux/actions/publish.js

If claim id already exists it indicates an edit  in which case it's safe to pass the claimId and note that it's not a pending claim

Pass claim id if it exists already

---

ui/component/claimListDiscover/view.jsx
ui/page/discover/view.jsx

Reverts OdyseeTeam/odysee-frontend#2379

Revert "fix: /$/docs searching all claims when no channel_ids present"

---

ui/page/wallet/view.jsx

The currency value query param value should be fiat not currency

---

ui/modal/modalClaimCollectionAdd/internal/claimCollectionAdd/internal/collectionSelectItem/view.jsx

Fix: modal playlist selection

---

ui/hocs/withCollectionItems/index.js
ui/page/collection/index.js
ui/page/collection/view.jsx
ui/redux/actions/claims.js
ui/redux/reducers/claims.js

Playlist fix: Total staked amount shows 0

---

ui/scss/component/_modal.scss

Issue Number: closes #1704, closes #1085

Fix: modal scrolls page back up

---

ui/component/experiment/index.js
ui/component/experiment/view.js
ui/hocs/withCollectionItems/index.js
ui/page/channel/tabs/homeTab/internal/homeTabSection/view.jsx
ui/page/collection/index.js
ui/page/collection/view.jsx
ui/redux/actions/claims.js
ui/redux/reducers/claims.js
ui/scss/component/_modal.scss

Ab testing

---

ui/component/claimListDiscover/view.jsx
ui/component/featuredBanner/view.jsx
ui/component/homepageSort/index.js
ui/component/homepageSort/view.jsx
ui/component/portals/view.jsx
ui/modal/modalCustomizeHomepage/view.jsx
ui/page/channel/view.jsx
ui/page/home/view.jsx
ui/page/portal/index.js
ui/page/portal/view.jsx
ui/redux/selectors/settings.js

Portals patch

---

ui/redux/actions/search.js

fixes: https://github.com/OdyseeTeam/odysee-frontend/issues/2432

Add userid to lighthouse search

---

ui/component/portals/style.scss
ui/component/portals/view.jsx

Makes the portals section on the homepage dynamic based on the number of portals by adding a rotator.

Portals Section Update

---

static/tosdr.txt

Added tosdr.txt on the site to easily make some changes on the tosdr.org website

Added tosdr.txt

---

ui/component/claimListDiscover/view.jsx
ui/page/channel/tabs/homeTab/internal/homeTabSection/index.js
ui/page/channel/tabs/homeTab/internal/homeTabSection/view.jsx
ui/page/channel/tabs/homeTab/view.jsx
ui/page/channel/view.jsx

- Prevent loading of wrong featured section on home tab and make loading smoother
- Inject ads into content grid on home tab
- Adjust legacy header threshold

Hometab Patch

---

web/webpack.config.js

tosdr.txt issued a 404 error when accessed. i forgot to add that on odysee

added tosdr.txt as root

---

ui/component/streamClaimRenderInline/index.js
ui/component/streamClaimRenderInline/view.jsx

Fix view log on inline render stream claim pages (images, posts etc.).

Fix view log on inline render stream claims

---

ui/component/claimPreview/index.js
ui/page/listBlocked/index.js
ui/page/listBlocked/view.jsx

Fix unresolved blocked and muted channels on settings page.

Fix unresolved blocked and muted channels on settings page

---

static/app-strings.json
ui/component/userVerify/view.jsx

Sometimes there is confusion that verification is required to be able to use/get LBC at all.  
Maybe this caused some part of it.

Clarify verification only affects getting LBC from rewards

---

ui/hocs/withStreamClaimRender/view.jsx
ui/scss/component/_content.scss

Fix endless loading loop on auto play next.

Play next fix

---

static/app-strings.json
ui/modal/modalRevokeClaim/view.jsx

Seems that the current text gets overlooked or ignored more often than not.
Attempt to make it more clear for how to fix.

Clarify sync deletion doesn't fix

---

ui/hocs/withStreamClaimRender/view.jsx
ui/redux/actions/content.js
ui/redux/selectors/content.js

Fix notification links

---

ui/scss/component/_file-render.scss

Fix player height in theater mode

---

ui/component/viewers/videoViewer/index.js
ui/component/viewers/videoViewer/style.scss
ui/component/viewers/videoViewer/view.jsx
ui/scss/component/_file-render.scss

Shows a recommendation overlay when the video ends and `autoplay-next` is disabled. Needs more work on mobile for the replay button + adjustments for the embedded player.
[rec.webm](https://user-images.githubusercontent.com/94839278/215794874-e201fe3e-b557-4190-82ba-ae16d4db1936.webm)

Recommendation player overlay

---

ui/component/commentCreate/index.js
ui/component/commentCreate/view.jsx
ui/component/selectAsset/style.scss
ui/component/selectAsset/view.jsx

Adds an image upload button to the comment editor for premium plus users.

Image Upload button

---

ui/component/claimPreview/view.jsx

Hide order-edit-buttons on list when in public view

---

ui/page/claim/internal/claimPageComponent/internal/channel/tabs/homeTab/internal/homeTabSection/index.js
ui/page/claim/internal/claimPageComponent/internal/channel/tabs/homeTab/internal/homeTabSection/view.jsx

Fixes #2532 
Bit of a random shot, but wanted to try.  
I think this approach makes sense(pretty much copied from existing code), but don't know if there is a better way.

Fix attempt - Resolve claims from edited list in homepage section

---

web/src/rss.js

Reverts OdyseeTeam/odysee-frontend#2540

Revert "fetch 150 max videos for RSS, fix mp3"

---

ui/scss/component/_channel.scss

Fix position of Save & Cancel button position on channel edit page

Fix position of Save & Cancel button position on channel edit page

---

.github/workflows/node.js.yml
package.json
yarn.lock

Update Node.js to v18.14.2 LTS

---

flow-typed/Collections.js
ui/component/claimList/view.jsx
ui/component/claimPreview/view.jsx
ui/component/collectionEditButtons/view.jsx
ui/component/collectionItemsList/view.jsx
ui/component/header/index.js
ui/component/header/view.jsx
ui/constants/collections.js
ui/page/collection/index.js
ui/page/collection/internal/collectionActions/index.js
ui/page/collection/internal/collectionActions/view.jsx
ui/page/collection/internal/collectionPublishForm/index.js
ui/page/collection/internal/collectionPublishForm/view.jsx
ui/page/collection/view.jsx
ui/redux/actions/collections.js
ui/redux/reducers/collections.js
ui/redux/selectors/collections.js
ui/scss/component/_collection.scss
ui/scss/component/_main.scss
ui/scss/component/section.scss
ui/scss/init/_gui.scss

Allows sorting items in collection by release_time.  
@toshokanneko 
I can't figure out how to make UI stuff. Could you help(make) the UI side? 
This is what my try looks currently. And no idea if scss is done correctly.
EDIT:  Could you also help with lint? I don't really understand what it wants.

Sort collection by release time buttons

---

ui/component/userVerify/index.js
ui/component/userVerify/view.jsx

Redirect verified users on reward verification page to rewards

Verified redirect

---

ui/component/wunderbarSuggestions/view.jsx

Fix artifact in search results with 0 subs

---

ui/page/collection/internal/collectionPublishForm/view.jsx

Fix attempt - Editing items in collection publish didn't saved on publish

---

ui/component/sideNavigation/view.jsx
ui/page/home/view.jsx

Fix console errors

---

flow-typed/homepage.js
ui/component/app/index.js
ui/component/app/view.jsx
ui/component/homepageSelector/index.js
ui/component/homepageSelector/view.jsx
ui/component/settingAppearance/index.js
ui/component/settingAppearance/view.jsx
ui/component/settingUnauthenticated/index.js
ui/component/settingUnauthenticated/view.jsx
ui/index.jsx
ui/redux/actions/settings.js
ui/redux/selectors/settings.js
ui/util/homepages.js
web/src/getHomepageJSON.js
web/src/homepageApi.js

This restores #2575 along with a fix for development mode.

Fix and restore "Support language specific /$/content/get" 

---

flow-typed/stripe.js
ui/page/wallet/txoList/index.js
ui/page/wallet/txoList/view.jsx
ui/page/wallet/walletFiatAccountHistory/index.js
ui/page/wallet/walletFiatAccountHistory/view.jsx
ui/page/wallet/walletFiatPaymentHistory/index.js
ui/page/wallet/walletFiatPaymentHistory/view.jsx
ui/redux/actions/stripe.js

Closes #2566
Test: `kp`
If it's good, route back to me -- I'll clean further and merge.
----
It was never implemented, and I think Anthony was waiting for the API to support pagination and simply truncated to 100 at the moment.
I looked, and it doesn't seem like the API has been updated, so this PR just removes the truncation and performs pagination on the UI side.

Paginate tip transactions

---

ui/component/claimLink/internal/preview/view.jsx
ui/component/claimLink/view.jsx
ui/component/videoClaimInitiator/view.jsx
ui/component/videoClaimRender/view.jsx
ui/component/viewers/videoViewer/internal/videojs-events.jsx
ui/component/viewers/videoViewer/internal/videojs.jsx
ui/component/viewers/videoViewer/style.scss
ui/component/viewers/videoViewer/view.jsx
ui/hocs/withStreamClaimRender/index.js
ui/hocs/withStreamClaimRender/internal/paidContentOverlay/style.scss
ui/hocs/withStreamClaimRender/view.jsx
ui/modal/modalPreorderAndPurchaseContent/internal/preorderAndPurchaseContentCard/view.jsx
ui/page/embedWrapper/internal/embedClaimComponent/view.jsx
ui/page/embedWrapper/view.jsx
ui/redux/selectors/claims.js
ui/scss/component/_claim-list.scss
ui/scss/component/_content.scss
ui/scss/component/_file-render.scss
ui/scss/component/_markdown-preview.scss
ui/scss/component/_videojs.scss

Fix embedded player behavior in markdown (posts, comments, chat) and external sites.

Fix Embedded Player

---

.devcontainer/devcontainer.json

Node 18, yarn v1
Not sure how to auto-select the max cores automatically, though (but that's minor).
<strike>Reviewing with Niko on 1 more thing...</strike>

Add codespace configuration

---

ui/component/publish/livestream/livestreamForm/view.jsx
ui/component/publish/post/postForm/view.jsx
ui/component/publish/upload/uploadForm/view.jsx
ui/modal/modalPublish/view.jsx
ui/modal/modalPublishPreview/view.jsx
ui/redux/actions/publish.js

I would like to propose a minor change that will help move some coding issues from runtime to compile-time.
See commit messages for details. 
I'm not sure when we will move to typescript, but I assume the changes will be somewhat compatible when we do.
----
It's a "no functional changes" PR, so should be safe.
Turn off whitespaces to see it clearer:
https://github.com/OdyseeTeam/odysee-frontend/pull/2662/files?diff=split&w=1

Example: use exact function type

---

ui/redux/reducers/collections.js

#2683 
Prevent deleting recent if delete is only called on unsaved changes.

fix recent playlist context menu item

---

ui/component/publish/livestream/publishLivestream/view.jsx

Root: 84629edc
Restore old logic, with minor tweaks to appease flow

Replays: fix duration representation

---

ui/component/viewers/videoViewer/view.jsx

#2337 
The callback was using the old muted value on playerReady.

preserve muted on reload

---

ui/component/app/view.jsx

Fix crash when browser language is not within our list

---

static/app-strings.json
ui/page/signInVerify/view.jsx

Changes: 
- If login fails -> show text that says login failed and that a new verification email was sent
- When successful login, show "Continue to Odysee" button on page. 
This is for scenarios where auto redirecting to home page doesn't work. Like when verification page is only Odysee tab in current session, or on mobile.

Improvement attempt - Login verification page

---

ui/component/featuredBanner/view.jsx

Handling playlists and other params in featured banner links.

Pass search to banner navigation

---

ui/component/chat/chatComment/view.jsx
ui/component/comment/view.jsx
ui/component/commentMenuList/index.js
ui/component/commentMenuList/view.jsx
ui/component/markdownLink/view.jsx
ui/modal/modalBlockChannel/view.jsx
ui/scss/component/_block-list.scss
ui/scss/component/_comments.scss
ui/scss/component/menu-button.scss

Adjust user context menu (when clicking on a channel name in chat or comments).

Adjust user menu

---

ui/component/channelEdit/view.jsx
ui/component/claimAbandonButton/view.jsx
ui/component/claimPreview/view.jsx
ui/page/livestreamSetup/style.scss
ui/page/playlists/style.scss
ui/scss/component/_button.scss
ui/scss/component/_card.scss
ui/scss/component/_claim-preview.scss
ui/scss/component/_claim-search.scss
ui/scss/component/_file-render.scss
ui/scss/component/_form-field.scss
ui/scss/component/_modal.scss

Style patch

---

ui/page/discover/internal/livestreamSection/view.jsx
ui/scss/component/_claim-search.scss
ui/scss/component/_livestream.scss

Adjust default number of displayed livestreams on mobile.

Adjust default number of displayed livestreams on mobile

---

ui/component/claimPreview/index.js
ui/component/claimPreviewTile/index.js
ui/util/formatMediaDuration.js

Fix media duration string being formatted as "time"

---

ui/component/claimMenuList/view.jsx
ui/component/socialShare/view.jsx
ui/util/url.js

Quick patch notes:
It looks like the new generateShareUrlMaybeShortened is somewhat a refactor of generateShareUrl but they both exist at the moment. We'll talk to @infinite-persistence to get his take.

quick patch shortened share urls

---

ui/component/publish/shared/publishVisibility/style.scss
ui/component/publish/shared/publishVisibility/view.jsx
ui/page/fileListPublished/style.scss
ui/scss/themes/dark.scss
ui/scss/themes/light.scss

https://github.com/OdyseeTeam/odysee-frontend/issues/2791#event-9260064914

Scheduled content style pass

---

flow-typed/Comment.js
ui/component/comment/index.js
ui/component/comment/view.jsx
ui/component/commentCreate/index.js
ui/component/commentCreate/view.jsx
ui/component/commentsList/index.js
ui/page/ownComments/index.js
ui/page/ownComments/view.jsx
ui/redux/actions/comments.js
ui/redux/reducers/comments.js
ui/redux/selectors/comments.js

Pulling out the low-hanging fruits to make the next PR easier to review.

Simple optimizations for `comments` selectors

---

flow-typed/publish.js
ui/component/fileDescription/view.jsx
ui/component/fileDetails/view.jsx
ui/component/publish/shared/publishAdditionalOptions/view.jsx
ui/component/publish/shared/publishReleaseDate/view.jsx
ui/redux/actions/publish.js
ui/scss/component/_media.scss

Closes #2790
See commit messages for details

Fix copyright field + restore in File Details

---

ui/page/claim/internal/claimPageComponent/internal/channelPage/tabs/homeTab/internal/homeTabSection/index.js
ui/page/claim/internal/claimPageComponent/internal/channelPage/tabs/homeTab/internal/homeTabSection/view.jsx
ui/page/claim/internal/claimPageComponent/internal/channelPage/tabs/homeTab/view.jsx
ui/page/claim/internal/claimPageComponent/internal/channelPage/view.jsx

https://github.com/OdyseeTeam/odysee-frontend/issues/2369#event-9279369095

Add repost section option to channel home tab

---

extras/lbryinc/redux/reducers/stats.js
extras/lbryinc/redux/selectors/stats.js
flow-typed/Claims.js
flow-typed/publish.js
flow-typed/redux.js
ui/component/claimMenuList/view.jsx
ui/redux/actions/content.js
ui/redux/actions/publish.js
ui/redux/reducers/claims.js
ui/redux/selectors/blocked.js
ui/redux/selectors/claims.js
ui/redux/selectors/coinSwap.js
ui/redux/selectors/collections.js
ui/redux/selectors/comments.js
ui/redux/selectors/content.js
ui/redux/selectors/livestream.js
ui/redux/selectors/memberships.js
ui/redux/selectors/search.js
ui/redux/selectors/stripe.js
ui/redux/selectors/tags.js

Remaining `State` definition cleanup

---

flow-typed/Claim.js
ui/component/scheduledStreams/index.js
ui/page/claim/internal/claimPageComponent/internal/channelPage/tabs/homeTab/internal/homeTabSection/index.js
ui/page/claim/internal/claimPageComponent/internal/channelPage/tabs/homeTab/internal/homeTabSection/view.jsx

See commits.
Closes [Can see already released upload still as upcoming for a while](https://github.com/OdyseeTeam/frontend-qa/issues/47) 
Closes [upcoming stream duplicated](https://github.com/OdyseeTeam/odysee-frontend/issues/2559)

Handle elapsed claims in "Upcoming" section

---

ui/component/claimListDiscover/view.jsx
ui/page/claim/internal/claimPageComponent/internal/channelPage/tabs/contentTab/internal/searchResults.jsx
ui/page/claim/internal/claimPageComponent/internal/channelPage/tabs/contentTab/view.jsx
ui/scss/component/_wunderbar.scss

Currently up on https://neko.odysee.tv/
- Consider `order_by` setting in search results (new, trending, top)
- Make search query exact (use quotes)
- Add "clear button" to wunderbar

Improve search on channel page content tab

---

ui/component/channelSections/Section/view.jsx
ui/component/claimListDiscover/index.js
ui/component/homepageSort/view.jsx
ui/component/settingContent/index.js
ui/component/settingContent/view.jsx
ui/component/sideNavigation/view.jsx
ui/component/upcomingClaims/index.js
ui/component/upcomingClaims/view.jsx
ui/modal/modalCustomizeHomepage/style.scss
ui/page/channelsFollowing/index.js
ui/page/channelsFollowing/view.jsx
ui/page/claim/internal/claimPageComponent/internal/channelPage/tabs/contentTab/view.jsx
ui/page/claim/internal/claimPageComponent/internal/channelPage/tabs/homeTab/internal/homeTabSection/view.jsx
ui/page/home/helper.jsx
ui/page/home/view.jsx
ui/scss/component/_claim-preview.scss
ui/scss/component/_home.scss
ui/scss/component/_meme.scss
ui/scss/init/_breakpoints.scss

Updating the upcoming section to reflect its expanded usage beyond livestreams.
**Home Page**
- Make upcoming section position customizable
- Default position: above `Following`
**Following Page**
- Upcoming section is now collapsible
**Settings Page**
- "Hide Scheduled Livestreams" option removed since it's no longer appropriate or necessary

Upcoming section revamp

---

ui/component/publish/shared/publishName/view.jsx

Closes #2842
Pulling this out from the bigger PR since I found a last minute bug there.  Pushing this first since it's small and a direct customer complaint.

PublishName: fix issues from throttling

---

ui/component/channelSections/Section/style.scss
ui/component/channelSections/Section/view.jsx
ui/component/channelSections/SectionList/style.scss
ui/component/channelSections/SectionList/view.jsx
ui/page/claim/internal/claimPageComponent/internal/channelPage/tabs/homeTab/internal/homeTabSection/view.jsx
ui/page/claim/internal/claimPageComponent/internal/channelPage/tabs/homeTab/style.scss
ui/page/featuredChannels/index.js
ui/page/featuredChannels/view.jsx

- Make "View more" label conditional on home tab
- Show all featured channels by default on channels tab
- Add link to separate section page to context menu
- Fix hover effects

Revamp featured channels layout

---

ui/redux/reducers/comments.js

LBRY-DESKTOP-WEB-1B6V
Lost reference.

Fix crash when deleting pinned comment

---

ui/scss/init/_gui.scss

Redesign gdpr popup on mobile

---

ui/component/previewOverlayProperties/index.js
ui/component/previewOverlayProperties/view.jsx
ui/redux/actions/publish.js
ui/util/claim.js
ui/util/publish.js

Livestream: fix few 'anytime' type issues

---

ui/component/commentMenuList/view.jsx

Adds report option for comments.

Add "report comment" menu entry

---

flow-typed/publish.js
static/app-strings.json
ui/component/publish/livestream/livestreamForm/index.js
ui/component/publish/livestream/livestreamForm/view.jsx
ui/component/publish/post/postForm/index.js
ui/component/publish/post/postForm/view.jsx
ui/component/publish/shared/publishFormErrors/index.js
ui/component/publish/shared/publishFormErrors/view.jsx
ui/component/publish/shared/publishPrice/index.js
ui/component/publish/shared/publishPrice/view.jsx
ui/component/publish/upload/uploadForm/index.js
ui/component/publish/upload/uploadForm/view.jsx
ui/component/publishProtectedContent/index.js
ui/component/publishProtectedContent/view.jsx
ui/modal/modalPublishPreview/index.js
ui/modal/modalPublishPreview/view.jsx
ui/redux/actions/memberships.js
ui/redux/actions/publish.js
ui/redux/reducers/publish.js
ui/redux/selectors/publish.js
ui/scss/component/_card.scss
ui/util/memberships.js
ui/util/publish.js

Reverts OdyseeTeam/odysee-frontend#2866
Handles #2877

Revert "Restriction-related fixes"

---

ui/page/claim/internal/claimPageComponent/internal/streamClaimPage/internal/markdownPost/index.js
ui/page/claim/internal/claimPageComponent/internal/streamClaimPage/internal/markdownPost/view.jsx

Closes #2891
- Missing state mapping (need enforced types, lol)
- Looks like intentionally tried to show nothing in this case? Maybe to make the Post page cleaner?
Add the same messages used in other claim formats.

Posts: tell user if creator has disabled comments

---

ui/component/claimRepostButton/view.jsx
ui/component/fileActions/view.jsx

Scheduled: repost/download button should be visible after elapsed

---

web/src/rss.js

They will show up once the date is passed now.

fix: rss + scheduled content

---

ui/page/fileListPublished/view.jsx

Show my reposts of content from muted channels in my uploads

---

ui/component/comment/view.jsx
ui/constants/comment.js
ui/scss/component/_comments.scss

Closes #2941
Test:  `inf`
It seems like the typical delta is 1s. Chose 5s to err on the side of not showing, vs incorrectly showing, but feel free to adjust.

Comments: add 'edited' label

---

static/index-web.html

Re-enable Google Analytics temporarily

Temporarily Restore Google Analytics

---

web/src/rss.js

- don't need to call backend get for now
- not sure if we need to remove other async chain, seemed to work okay.
This will probably change once andriy can support extensions on new v6 urls

fix rss for new cdn

---

.env.defaults
web/webpack.config.js
webpack.base.config.js

There were reports of page-load failures, which also coincide with the execution of the "js cleanup" script.
While we investigate if the script is problematic, rebuild to ensure there aren't any unintended lost chunks.

Synchronize build

---

ui/component/common/form-components/plugins/inline-attachment/inline-attachment.js

Editor: allow webp-upload for inline images

---

ui/util/publish.js

Don't add `c:scheduled-livestream` tag to scheduled file/post uploads

---

ui/util/web.js
web/src/oEmbed.js

Helps fill full width, this should work in most cases
Hardcoding oembed return to match youtube - sounds like that's the min height/width which sin't too important.

fix: embedding size

---

ui/component/selectThumbnail/view.jsx

It seems to work, but is filtered in the file by default.

Add .webp as accepted thumbnail filetype

---

ui/component/router/view.jsx

Show collection title in tab title, instead of just "Odysee"

---

ui/scss/component/_ads.scss
web/component/ad/aboveComments/style.scss
web/component/ad/aboveComments/view.jsx
web/component/ad/tileB/view.jsx
web/component/ad/view.jsx

Adds rmbl Ad provider for area above comments. Either 3, 2 or 1, depending on the available space. Sometimes they're unique, but sometimes it also loads the same one 3 times. Might require more adjustments to avoid that.

Rmbl provider

---

ui/component/sideNavigation/view.jsx
ui/scss/component/_ads.scss
web/component/ad/adSticky/view.jsx
web/component/ad/tileA/view.jsx
web/component/ad/view.jsx

Update Tile A

---

ui/component/commentReactions/index.js
ui/component/commentReactions/view.jsx
ui/component/fileReactions/index.js
ui/component/fileReactions/view.jsx
ui/constants/tags.js

Tags:
`c:disable-slimes-all`
`c:disable-slimes-video`

Allow disabling sliming with tags

---

ui/component/streamClaimRenderInline/view.jsx
ui/component/viewers/imageViewer.jsx
ui/constants/file_render_modes.js
ui/page/claim/internal/claimPageComponent/internal/streamClaimPage/index.js
ui/page/claim/internal/claimPageComponent/internal/streamClaimPage/view.jsx

(Some what) fixes #503 
<details>
<summary>Images</summary>
Comic: https://odysee.com/@BrendonBrewer:3/brigham:f
Application/...: https://odysee.com/@RemoteBasketballAcademy:3/data-analyst-report(excelsheet):4
Model: https://odysee.com/@Decimal_Dot:d/A-Salt-Inator:7
</details>

Show file thumbnail for non-viewable files - fix attempt

---

flow-typed/Claims.js
ui/redux/actions/collections.js
ui/redux/reducers/claims.js
ui/redux/selectors/claims.js

Reverts OdyseeTeam/odysee-frontend#3092

Revert "Don't wipe list items on edit when claim_search fails"

---

flow-typed/Claims.js
ui/redux/actions/collections.js
ui/redux/reducers/claims.js
ui/redux/selectors/claims.js

This time without resolve spam

Fix playlist item disappear

---

ui/scss/component/_channel.scss
ui/scss/component/_claim-search.scss

Details in commit messages.
Not exactly sure what I'm doing, but didn't see this breaking anything. 
<details>
<summary>Images</summary>
</details>

Minor mobile layout fixes

---

ui/redux/actions/publish.js
ui/redux/selectors/publish.js

Limit non-public visibility to video/audio/image/text content and posts

Limit non-public visibility to video/audio/image/text content and posts

---

ui/redux/actions/publish.js
ui/redux/selectors/publish.js

Reverts OdyseeTeam/odysee-frontend#3109

Revert "Limit non-public visibility to video/audio/image/text content and posts"

---

ui/page/search/view.jsx

Reset search `from` when the search term changes

---

ui/constants/channels.js

add french autofollow channel

---

ui/component/claimListHeader/internal/tagSearch/tagSearch.jsx
ui/component/wunderbarSuggestions/view.jsx
ui/scss/component/_wunderbar.scss

- Show the clear-search-button when there is search text
- Hide the clear-tag-search-button when the tag-search is empty

Add back the clear search button

---

static/app-strings.json
ui/redux/actions/collections.js

Show error which users can understand when playlist is too large.

Improve playlist-size-error message

---

ui/page/claim/internal/claimPageComponent/internal/channelPage/tabs/homeTab/internal/featuredSection/view.jsx

Show more title in channel page's featured claim

---

package.json
ui/component/selectAsset/style.scss
ui/component/selectAsset/view.jsx
ui/modal/modal.jsx
ui/modal/modalImageUpload/view.jsx
yarn.lock

Cropper for avatar & banner images

---

static/app-strings.json
ui/component/tagsSearch/view.jsx
web/src/rss.js

Allow download disabled content in RSS

---

ui/component/comment/view.jsx
ui/component/commentsList/view.jsx
ui/component/commentsReplies/view.jsx

- Comments from the deleted channel were showing in the totalcomments count.
- Totalcomments count can decrease as more comments are loaded, if some are from deleted channels.

Improve UI filtered comments from deleted channels

---

static/app-strings.json
ui/component/headerProfileMenuButton/index.js
ui/component/logo/index.js
ui/component/streamClaimRenderInline/index.js
ui/component/themeSelector/index.js
ui/component/themeSelector/view.jsx
ui/redux/reducers/settings.js
ui/redux/selectors/settings.js

-Adds option "System" to theme selector
Works on Firefox and Brave, but not on Chorme.
Found some thread about issue with Chromium, but on a quick look didn't find how to make it work, will look more if we get complains. https://issues.chromium.org/issues/40642550

Allow defaulting to browser theme

---

ui/page/claim/internal/claimPageComponent/internal/channelPage/tabs/aboutTab/view.jsx

If missing, add `https://` to the About page Site

---

static/app-strings.json
ui/modal/modalConfirmOdyseeMembership/index.js
ui/modal/modalConfirmOdyseeMembership/view.jsx
ui/page/odyseeMembership/internal/premiumOption/view.jsx
ui/redux/actions/memberships.js

-typos
-extra capitalizations
-fix amount to always have two decimals
-remove duplicate currency symbol/info from amount
OLD:
NEW:

Premium page fixes

---

ui/redux/selectors/comments.js

Don't filter personally blocked comments on channels I'm a mod for.

Disable personal blocks on moderated channels

---

ui/component/userVerify/view.jsx

Remove link to a broken faq page

---

ui/scss/component/_card.scss

**NEW:**
**OLD (breaks title from the middle of a word):**

Prefer breaking long title at the end of the word

---

ui/component/viewers/videoViewer/internal/videojs-events.jsx
ui/component/viewers/videoViewer/internal/videojs-functions.jsx

auto restart failures and cache bust 

---

ui/component/app/view.jsx
ui/redux/actions/user.js

fixes: #3176  
When user/new failed the flow errored before geoblocks got fetched. Didn't issues with moving fetching of the geoblock list bit higher in the flow.

Fix emebds not loading sometimes

---

.env.defaults
config.js
ui/redux/actions/blocked.js

Needed to do same with geo blocked list, than what was done with LOCALE_API. 
This needs to be added in .env
```
GEO_BLOCK_API=https://api.odysee.com/geo/blocked_list
```

Actually allow playing videos if api down

---

ui/modal/modalRemoveAccount/thunk.js
ui/page/settingsStripeAccount/index.js
ui/page/settingsStripeAccount/view.jsx
ui/redux/actions/stripe.js

Removes both Stripe account/customer on account deletion. (Also shows toast with errors)
Adds "Remove Account" button here.  (Shows a toast message on successful deletion)

Stripe account/customer deletion

---

web/page/tos/view.jsx

Added software credits section to TOS file.

Added software credits to TOS

---

ui/component/viewers/videoViewer/internal/plugins/videojs-hls-quality-selector/plugin.js

Always show quality

---

web/page/privacypolicy/view.jsx
web/page/tos/view.jsx
web/page/youtubetos/view.jsx

Updated addresses & contact info in TOS and privacy policy 
Issue Number:
- [x ] Documentation changes
- [ x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [ x] I have checked that this PR does not introduce a breaking change
</details>

Updates to TOS & Privacy Policy

---

ui/component/claimShareButton/view.jsx
ui/component/claimSupportButton/view.jsx
ui/component/common/icon-custom.jsx
ui/component/subscribeButton/view.jsx
ui/page/claim/internal/claimPageComponent/internal/channelPage/view.jsx
ui/scss/component/_channel.scss
ui/scss/init/_vars.scss

-Try to show full channel cover image on mobile. 
-Removed texts from buttons on mobile, and changed them to show in row.
-Updated the follow button on mobile to indicate the current state of the follow.
<details>
<summary>Old</summary>
</details>
<details>
<summary>New</summary>
Not Following:  
Following:
</details>

Mobile channel cover

---

static/app-strings.json
ui/component/publish/livestream/publishLivestream/view.jsx
ui/component/publish/upload/publishFile/view.jsx

Update video encoding warning

---

ui/page/claim/internal/claimPageComponent/internal/channelPage/tabs/homeTab/internal/featuredSection/style.scss
ui/scss/component/_claim-preview.scss
ui/scss/component/_content.scss
ui/scss/component/_media.scss

https://spaceodysee.slack.com/archives/C07GN4GHK60/p1741799386091039 (?)
OLD:
NEW:

Thumbnails force fit to 16:9 (?)

---

ui/page/claim/internal/claimPageComponent/internal/channelPage/tabs/homeTab/internal/featuredSection/style.scss
ui/scss/component/_claim-preview.scss
ui/scss/component/_content.scss
ui/scss/component/_media.scss

Reverts OdyseeTeam/odysee-frontend#3260

Revert "Thumbnails force fit to 16:9 (?)"

---

web/src/html.js

(already optimized)
Issue Number:
</details>

don't cdn OG image through optimizer

---

ui/component/claimPreview/view.jsx
ui/component/claimPreviewTile/view.jsx
ui/component/joinMembershipCard/internal/previewPage/view.jsx
ui/component/settingsStripeCard/view.jsx
ui/component/walletTipAmountSelector/view.jsx
ui/page/claim/internal/claimPageComponent/internal/channelPage/tabs/membershipTab/view.jsx

Filter empty reposts (Still allow on "uploads" page)

---

ui/scss/component/_claim-preview.scss

UI error in the claim preview button. I temporarily set it to 40px.

Fix menu-button hitbox

---

ui/page/collection/index.js
ui/page/collection/view.jsx

If playlist is geoRestricted, handle like other claims.

Handle playlist geoRestricted

---

ui/component/claimListDiscover/view.jsx
ui/component/claimListHeader/view.jsx
ui/constants/claim_search.js
ui/hocs/withStreamClaimRender/internal/paidContentOverlay/view.jsx

Add options for filtering Paid and Rentable content + a minor typo fix in rentable content AR price

Improve Paid content filtering + minor fix

---

extras/lbryinc/index.js
extras/lbryinc/redux/actions/blacklist.js
extras/lbryinc/redux/actions/filtered.js
extras/lbryinc/redux/reducers/blacklist.js
extras/lbryinc/redux/reducers/filtered.js
extras/lbryinc/redux/selectors/ban.js
extras/lbryinc/redux/selectors/blacklist.js
extras/lbryinc/redux/selectors/filtered.js
ui/index.jsx
ui/page/claim/internal/claimPageComponent/index.js
ui/page/claim/internal/claimPageComponent/internal/channelPage/index.js
ui/page/claim/internal/claimPageComponent/internal/channelPage/view.jsx
ui/page/home/view.jsx
ui/redux/selectors/comments.js
ui/util/claim.js

Change block/filtering to use claim_ids instead of outpoints

Blacklist/filtering from outpoint to claim_id

---

ui/component/userSignUp/view.jsx
ui/component/userVerify/view.jsx

Remove cc verification + skip rewards verify in login if user has balance

---

ui/component/sideNavigation/view.jsx

Make publish/wallet pages easier to access/find on mobile 

---

ui/component/header/index.js
ui/component/header/view.jsx

https://github.com/user-attachments/assets/4b79cbb9-946f-4591-b1d5-01a4d565641d

Hide wallet on mobile header if miniplayer open

---

flow-typed/Collections.js
ui/component/claimMenuList/index.js
ui/component/claimMenuList/view.jsx
ui/redux/reducers/collections.js
ui/redux/selectors/collections.js
ui/redux/setup/persistedState.js

Track 3 last used collections + store in preferences

---

ui/modal/modalArweaveConnect/view.jsx
ui/redux/actions/stripe.js

Show error modal if address registration errors

---

static/app-strings.json
ui/component/settingPlayer/view.jsx

Adjust video quality text
