OdyseeTeam/odysee-frontend

ui/component/commentMenuList/view.jsx
ui/component/common/markdown-preview.jsx
ui/component/livestreamComment/view.jsx
ui/scss/component/_comments.scss
ui/scss/component/_livestream.scss
ui/scss/component/_markdown-preview.scss
ui/util/remark-lbry.js
ui/util/remark-timestamp.js
web/scss/themes/odysee/init/_gui.scss

Issues: https://github.com/lbryio/lbry-desktop/issues/5560, https://github.com/lbryio/lbry-desktop/issues/5560, https://github.com/lbryio/lbry-desktop/issues/5561
Continuing from https://github.com/lbryio/lbry-desktop/pull/7193
embeds that require channel stake weren't resized properly:
[![image.png](https://i.postimg.cc/zfP6yPQt/image.png)](https://postimg.cc/KKBJVQxB) [![image.png](https://i.postimg.cc/6pJPRvYK/image.png)](https://postimg.cc/hfsMRhkZ)
fixed overflow on embed on super-chat causing scroll issues:
removed "copy comment link" from livestream comments:
[![image.png](https://i.postimg.cc/HWPwf1yP/image.png)](https://postimg.cc/8sMf63wh)
multiple quotes will show once and won't break live chat: 
[![image.png](https://i.postimg.cc/hPxtBNj0/image.png)](https://postimg.cc/svjrP65B …

[Comment/Livestream] Markdown and style fixes

---

ui/component/commentsList/view.jsx

Meant to re-use strings, but I forgot to change the variable name in the prior commit.  Oops.

i18n - refix total comments

---

ui/component/comment/view.jsx
ui/component/commentsList/view.jsx

Now that we batch-resolve the comment authors before displaying the comments, the linked-comment scrolling logic didn't work well with nested replies.
Previously, I didn't want to put the logic at the lowest level (`Comment`) because it was hard for the child to know whether to scroll or not. For example, we don't want to scroll when user changes the comment filters or presses the Refresh Comments button.
Relented and moved the logic to `Comment`, and pass a flag via `window` to indicate whether a scrolling is needed (I know this is frowned upon by some, but it's the cleanest solution I can think of for a non-critical action).
This is now more efficient overall as we don't need to scan the DOM, and scrolls with minimal delay.
In markdown posts with lots of images, a layout shift due to …

Fix linked-comment scrolling (again)

---

ui/component/claimPreviewSubtitle/index.js
ui/component/claimPreviewSubtitle/view.jsx
ui/component/fileViewCountInline/view.jsx
ui/scss/component/_claim-list.scss

Adds sub count to search and other areas, this was a idea from @mayeaux.
Issue Number: [#7164](https://github.com/lbryio/lbry-desktop/issues/7164)
Only shows Channel Name and Claim Amount.
Now shows Channel Name, Claim Amount and Follower Count.
</details>

Add follower count to search and other areas.

---

flow-typed/Comment.js
package.json
ui/component/channelMentionSuggestions/index.js
ui/component/claimPreview/index.js
ui/component/claimPreviewTile/index.js
ui/component/claimTags/index.js
ui/component/comment/index.js
ui/component/commentReactions/index.js
ui/component/commentReactions/view.jsx
ui/component/commentsList/index.js
ui/component/commentsReplies/index.js
ui/component/dateTime/index.js
ui/component/fileDescription/index.js
ui/component/fileDescription/view.jsx
ui/component/livestreamComment/index.js
ui/component/livestreamComments/index.js
ui/component/livestreamComments/view.jsx
ui/component/supportsLiquidate/index.js
ui/component/supportsLiquidate/view.jsx
ui/page/file/index.js
ui/page/ownComments/index.js
ui/redux/actions/comments.js
ui/redux/reducers/blocked.js
ui/redux/reducers/tags.js
ui/redux/selectors/blocked.js
ui/redux/selectors/claims.js
ui/redux/selectors/comments.js
ui/redux/selectors/tags.js
yarn.lock

1. Lots of extra renders and calculations due to:
- Selectors not memoized correctly (`makeSelectXX` pretty much defeats the memoization in `createSelector`).
- Trivial (direct access of store values) type of selectors are being memoized -- wasted memory.
- Reference invalidation in the store and/or selectors.
2. Incrementally closes [#7177 Look into heavy CPU/render usage during comment display](https://github.com/lbryio/lbry-desktop/issues/7177)
- Use `re-reselect` to solve the single-dimension caching of `creatorSelector` (i.e. replaces the `makeSelectXX` approach).
- Incrementally replace those selectors to reduce testing and potential errors.
- Be mindful when updating states in Reducers -- don't update (invalid reference) if there is no actual change in value.

Incremental selector memoization fixes

---

yarn.lock

Our `<CodeViewer>` and `react-simplemde-editor` uses `codemirror`, and they were each bundling a different version.
Re-generate yarn.lock for `codemirror`. Since we are upgrading anyway, upgraded to the latest and greatest.

Upgrade codemirror + module sharing

---

ui/scss/component/_videojs.scss

Issue Number: [#6184](https://github.com/lbryio/lbry-desktop/issues/6184)
Theatre mode sidebars are currently black.
Changes the theatre mode sidebar colors to Odysee theme.
I am unable to change the "square edge" into "rounded edge".
</details>

Theatre mode sidebars background color

---

ui/component/app/view.jsx
ui/component/page/view.jsx
ui/component/router/view.jsx
ui/component/viewers/videoViewer/internal/videojs.jsx
ui/component/wunderbar/view.jsx
ui/page/show/view.jsx
ui/scss/component/_videojs.scss

95% of `secondary.js` is unused code.
- It was meant to reduce network overhead by chunking up files that are mostly likely needed after bootup, and also to reduce the number of `vendor-*.js` files.
- But it ended up accidentally grabbing lots of stuff, thus defeating the purpose of code-splitting.
Don't bother grouping up the chunks for now

Split `secondary.js`

---

ui/component/claimPreview/view.jsx
ui/redux/selectors/claims.js
ui/util/lbryURI.js

Closes [#129 "Total Blocking Time" doubled after redux-consolidation commit](https://github.com/OdyseeTeam/odysee-frontend/issues/129)
See commit messages.  Unsure if I covered all cases for the `isURIEqual` replacement.  Will there be any odd encodings that would break it?
- Before:  pausing a video took ~200ms
- <img src="https://user-images.githubusercontent.com/64950861/139851451-595b3271-5f6a-40ca-804f-b6e2acf44940.png" width="300">
- After:  pausing a video takes ~80ms
- <img src="https://user-images.githubusercontent.com/64950861/139851523-5d511f64-2025-4486-9478-77a1e4c5bab9.png" width="300">

URI parsing improvements

---

ui/modal/modalRouter/view.jsx

There was one instance of ModalError that wasn't wrapped in the Suspense.
- Moved `getModal` outside to make the code cleaner. Due to the length of `getModal`, I didn't notice the early return statement.
- Fix ModalError's Suspense.

Fix crash with ModalError

---

ui/util/lbryURI.js

No point for it to keep appearing if nobody cares?
Anyway, added option to hide it via environment variable for those who are annoyed by it.

Add option to hide `buildUri` warnings

---

ui/component/header/view.jsx

Fixes #190
Issue about sums it up. As an example, press the cog button in header section, then try doing everything that you expect from the hyperlink on "Settings" or "Help" item. You'll see that nor middleclicking, nor pressing <kbd>Ctrl + Enter</kbd> on any item will ever open in a new tab. This is a bad UX and I can't stand it.
Only 2/3 could be done here. I think it's because of the peculiarities brought by Reach components, they can't be dragged: [MenuLink](https://reach.tech/menu-button/#menulink), [MenuItem](https://reach.tech/menu-button/#menuitem).
In most cases, just middleclicking and keyboard navigation are enough, so I think it's a win. …

Transform route-leading menu items to hyperlinks

---

ui/util/comments.js

Also, moved the `replace` outside of the find-loop so that we don't re-run it each time.

Use `replace` instead of `replaceAll` for browser compatibility

---

ui/component/channelThumbnail/view.jsx
ui/component/commentsList/index.js
ui/component/commentsList/view.jsx
ui/component/livestreamComments/index.js
ui/component/livestreamComments/view.jsx
ui/redux/reducers/claims.js
ui/redux/selectors/claims.js
ui/redux/selectors/comments.js
ui/scss/component/_livestream.scss

Closes [#210 livestream page lag / batch resolve comment claims? ](https://github.com/OdyseeTeam/odysee-frontend/issues/210)
It's the classic store invalidation and re-render.  
- The superchat row is re-mounted on each render --> components call resolve --> invalidates the store (flags, etc) --> re-renders the gui --> The superchat row is re-mounted on each render --> rinse and repeat
If the resolve list is huge, the invalidation won't settle fast enough to cut the chain.
- Fixed some of the invalidation stuff ... the remaining is hard to change without refactoring.
- Shortened initial superchat list to 10, and batch-resolve before opening the full list.
- Will need to paginate the list.
- Look into using Immutable.js in reducers to handle the invalidation issue.

Handle huge superchat list

---

ui/component/comment/index.js
ui/component/comment/view.jsx
ui/component/commentCreate/index.js
ui/component/commentCreate/view.jsx
ui/component/commentsReplies/index.js
ui/component/commentsReplies/view.jsx
ui/component/fileActions/index.js
ui/component/fileActions/view.jsx
ui/component/publishForm/index.js
ui/component/repostCreate/index.js
ui/component/repostCreate/view.jsx
ui/component/settingAccount/index.js
ui/component/settingAccount/view.jsx
ui/component/walletSend/index.js
ui/page/channels/index.js
ui/page/channels/view.jsx
ui/page/creatorDashboard/index.js
ui/page/creatorDashboard/view.jsx
ui/page/listBlocked/index.js
ui/page/listBlocked/view.jsx
ui/page/livestreamSetup/index.js
ui/page/livestreamSetup/view.jsx
ui/redux/selectors/claims.js

- selectMyChannelClaims depends on `byId`, which currently is always invalidated per update, so it is not memoized.
- Most of the use-cases just needs the ID or the length of the array anyways, so avoid generating a Claim array (in selectMyChannelClaims) unnecessarily -- the client need to reduce it back down to IDs again :/
- The simpler boolean also removes the need to memoize the selector, which saves a bit of memory.

Use 'selectHasChannel' instead of the full 'selectMyChannelClaims'

---

ui/component/fileRenderFloating/view.jsx
ui/scss/component/_content.scss

Issue Number:206
Dragging the floating video player plays/pauses the video upon release.
Dragging the floating video player no longer plays/pauses the video upon release.
I tried to use event.preventDefault on the click handler but that didn't 
work. So instead I'm using css 'pointer-events: none' to disable click 
events on the player while the player is being dragged.
https://github.com/OdyseeTeam/odysee-frontend/issues/206
</details>

Fixes the play/pause on drag issue with the floating player.

---

flow-typed/Comment.js
ui/component/commentMenuList/index.js
ui/component/commentMenuList/view.jsx
ui/modal/modalRemoveComment/index.js
ui/modal/modalRemoveComment/view.jsx
ui/redux/actions/comments.js

Closes [#223 Add ability for delegated moderators to delete comments](https://github.com/OdyseeTeam/odysee-frontend/issues/223)
I believe the API also allows Admins to delete as well, but wasn't sure if that's what we want, so I left that out.
If yes, it's just another 1-liner to allow it.
- Refactored doCommentAbandon's signature so we don't end up converting between "uri" and "Claim" several times and needing to lookup redux when the client can already provide us the exact values that we need.
- Pass the new moderator fields to the API.
- Remove the need to call 'makeSelectChannelPermUrlForClaimUri' since it's a simple field query when we already have the claim.
`kp`

Allow moderators to delete comment

---

ui/redux/reducers/claims.js
ui/redux/selectors/app.js
ui/redux/selectors/claims.js

Closes #116
See commit messages for full details, but it's basically it's `byId[]` invalidation fixes, then fixing up 2 frequently-running selectors as a test.  
There are lots of others selectors that depend on byId.  Will continue with the rest once this is passes, as the rest would just be a rinse-and-repeat operation of cleaning up the selectors.
`kp`

`byId[]` fixes to reduce invalidation

---

ui/component/comment/view.jsx

Closes [#238 Comments: author-name not highlighted when in Channel Community tab](https://github.com/OdyseeTeam/odysee-frontend/issues/238)
- Channel claims don't have a signing channel. Use `getChannelFromClaim`, which handles both content and channel claim.

Comment: Fix missing author highlight in Community Tag

---

ui/component/app/view.jsx

- Not needed for web since the browser does it, and should have been gated under 'app'
- This reverts lbry-desktop 3744.

Remove mouse-back/forward listeners

---

ui/component/claimPreview/index.js
ui/component/claimPreview/view.jsx
ui/component/claimPreviewReset/index.js
ui/component/claimPreviewReset/view.jsx
ui/component/fileSubtitle/view.jsx
ui/component/livestreamLink/view.jsx
ui/page/livestream/view.jsx
ui/scss/component/claim-preview-reset.scss
web/src/livestreaming/index.js
web/src/livestreaming/long-polling.js

Issue Number:
1) 
- Move long polling mechanism out of React components and in to reusable module.
2) 
- Kill switch now uses long polling and shows only when stream is active. 
- Also shows on watch page. 
</details>

Fix livestream state issues. Create unified long polling mechanism.

---

ui/redux/reducers/claims.js
ui/redux/selectors/claims.js

- selectMyActiveClaims memo problem -- being recalculated on every click -- high workload for wallet with large uploads.
- Mistake in handling abandoning IDs (it was trying to extract keys from an array)
- selectAbandoningIds: never use `state` as an input selector. Breaks memo.
- Don't use selectMyClaimsRaw and then reduce it back to IDs. Use selectMyClaimIdsRaw instead.
- selectAbandoningIds is already in array form, so don't run Object.keys.
- Fix abandoningById never clearing when succeeded.

Fix memo: selectMyActiveClaims, selectAbandoningIds

---

ui/component/channelContent/index.js
ui/component/claimMenuList/index.js
ui/component/claimPreview/index.js
ui/component/claimPreviewReset/index.js
ui/component/claimProperties/index.js
ui/component/collectionContentSidebar/index.js
ui/component/commentCreate/index.js
ui/component/commentMenuList/index.js
ui/component/commentReactions/index.js
ui/component/commentsList/index.js
ui/component/commentsReplies/index.js
ui/component/fileActions/index.js
ui/component/fileDescription/index.js
ui/component/fileDownloadLink/index.js
ui/component/filePrice/index.js
ui/component/fileValues/index.js
ui/component/postViewer/index.js
ui/component/previewLink/index.js
ui/component/previewOverlayProperties/index.js
ui/component/walletSendTip/index.js
ui/modal/modalRemoveCollection/index.js
ui/modal/modalRemoveFile/index.js
ui/page/channel/index.js
ui/page/collection/index.js
ui/page/show/index.js
ui/redux/actions/app.js
ui/redux/actions/content.js
ui/redux/selectors/claims.js

`normalizeUri` | `parseURI` is expensive and has been causing sluggish operations when called repeatedly or within a loop.
Since I'm not confident enough to remove the call entirely from makeSelectClaimIsMine (although I've yet to find a scenario that the uri is not already normalized), we'll try caching the calls instead.
- in a simple test of toggling between 2 category pages, we saved 20ms from `parseURI` calls alone.
- in a test of opening all categories one time, the memory usage remained similar. This makes sense since we removed a `makeSelect*` (which creates a selector for each call + not memoizing), and replaced that with a cached selector that's actually memoizing.

`selectClaimIsMineForUri` to replace `makeSelectClaimIsMine`

---

ui/page/livestream/view.jsx
web/component/browserNotificationSettings/use-browser-notifications.js

Adjust some initial states to optimize initial render. Further adjustment to livestream (if needed) can be made with upcoming changes.
On live stream you briefly see the "not streaming" message rendered on load.
On notification settings you briefly see the not supported hints rendered on load.
Both are not rendered by default.
</details>

Adjust some initial states to optimize initial render

---

web/setup/publish-v2.js

We want to avoid the double `notify`, and also to confirm whether the SDK is timing out.

Notify: Re-enable delay but only for initial connection problem

---

web/setup/publish-v2.js

The status = 0 is due to unresponsive backend right after the tus-upload. No root-cause found yet.
It may or may not help, but adding a delay to account for the unresponsive stage for now.

Band-aid: wait a while before sending `notify`

---

ui/component/claimMenuList/index.js
ui/component/claimPreview/index.js
ui/component/claimProperties/index.js
ui/component/invited/index.js
ui/component/previewOverlayProperties/index.js
ui/component/subscribeButton/index.js
ui/page/channel/index.js
ui/redux/selectors/subscriptions.js

- It will not return true if the uri provided is canonical, because the compared subscription uri is in permanent form. This was causing certain elements like the Heart to not appear in claim tiles.
- It is super slow for large subscriptions not just because of the array size + being a hot selector, but also because it is looking up the claim twice, not memo'd, and also calling `parseURI` to determine if it's a channel which is unnecessary if you already have the claim.
- Optimize the selector to only look up the claim once, and make operations using already-obtained info.
- Fix memo.
I'm confident with this PR from a performance standpoint (measured and all), but not sure why there is such a dependency between canonical vs permanent url.  Was it intentionally, for example, to make the …

Fix and optimize makeSelectIsSubscribed

---

ui/component/channelEdit/index.js
ui/component/channelThumbnail/index.js
ui/component/claimPreviewTile/index.js
ui/component/collectionEdit/index.js
ui/component/collectionPreviewTile/index.js
ui/component/comment/index.js
ui/component/embedPlayButton/index.js
ui/component/fileRender/index.js
ui/component/fileRenderInitiator/index.js
ui/component/livestreamLayout/index.js
ui/component/previewLink/index.js
ui/component/sideNavigation/view.jsx
ui/component/viewers/videoViewer/index.js
ui/page/channel/index.js
ui/page/collection/index.js
ui/redux/selectors/claims.js
ui/util/buildHomepage.js

On Firefox Android with 100 subscriptions, it takes almost 1 second to open up the menu
Only show 10 subscriptions and tags until "Show more" is pressed.  I know we haven't figured out how this should look, but I think performance matters more?
- Web: I can now toggle quickly, non-stop.
- Mobile: It's a bit faster, but still slow overall. Couldn't pinpoint the remaining bottleneck yet, but feels like some selector is re-sorting something.
`kp`

Attempt to speed up sidebar menu for mobile

---

web/component/browserNotificationBanner/view.jsx
web/component/browserNotificationSettings/use-browser-notifications.js

Add initialization status to push notification hook. Can be used to better control render strategy in cmpnts utilizing it.
Prevent unnecessary render of notifications banner on notifications page.
The notifications subscription banner can briefly render on page load because it doesn't know the user is subscribed fast enough.
Banner will not be shown if subscription status has not yet been determined.
</details>

Prevent unnecessary render of notifications banner

---

ui/redux/reducers/blocked.js

When the muted list was being cleared from another app, the web version ended up restoring the previous muted list.
- As long as `blocked` is defined, return that since an empty array is a valid result.
- If undefined, something went wrong when calling the reducer, so retain the muted list. I believe this was the original intention of that line.
It could be that at one point, that reducer was expecting a delta. But now it expects the full list, so checking for `length` no longer make sense.

Fix unable to clear muted list

---

ui/component/app/index.js
ui/component/app/view.jsx
ui/redux/actions/app.js
ui/redux/actions/sync.js
ui/redux/reducers/blocked.js
ui/redux/reducers/tags.js

Every time the app goes into focus and syncs, the GUI updates and does a lot of re-calculations even when the sync hash indicates "no change".
At first, I moved `doGetAndPopulated` preferences under the `hasNewData` if-block, since from the function standpoint, it makes sense to not update when there is no new data.
However, I realized the app is stuck in the "still preparing" state at startup, which probably means that it needs to populate at least once.
I found a place that already does that one-off action, but it's for Desktop only. Enabling that does fix the issue, but I think `getWalletSyncPref` is for Desktop only, so I did a simpler version that just updates the prefs.

Avoid user_state_populate when there is no change.

---

ui/page/livestream/view.jsx

Make sure we set livestream status to false if we aren't long polling.
Livestream status defaults to true on livestream content page and isn't always correctly set to false.
Livestream status is correct on livestream content page.
</details>

Hotfix livestream status

---

ui/component/fileRenderFloating/view.jsx

- Closes #251 
- Resizing the browser on homepage, even when FP is not there, was laggy.
- The floating player is also supposed to track the right edge when the browser is resized (albeit not very accurately).  That behavior was lost.
Recent changes and/or refactoring combined the effects or added dependancies into the effects, causing them to re-run excessively.
- Restored effects to their original behavior.
- Don't perform the boundary checks when dragging -- only do it when released.
- Do proper debouncing for the 'resize' listener -- the previous method was incorrect as a new function is created on each render.
It's still pretty sluggish when vjs goes crazy.  Anthony will look at it.
`Floating-player high CPU usage on Chrome #158`

Floating player position-listener fixes

---

ui/component/yrbl/index.jsx

`<div>` cannot be a descendend of `<p>`, and `{subtitle}`s sometimes need to have `<div>`s.
Just switch from `<p>` to `<div>`, and let the client decide when the actual text paragraphs are.

Fix annoying hierarchy error with Yrbl

---

web/src/routes.js
web/src/tempfile.js

Some admin processes need files in strange non-root places (unlike robots.txt).
Use this path for that.

facilitate admin temp files

---

extras/lbryinc/redux/selectors/ban.js

Tried to simplify the logic between checking Signing Channel vs Content claim, and ended up always checking against Channel. This is ok for commentron blocklists, but not for blacklists where the txid is per claim.
- Restored original logic.
- While at it, restored the usage of `selectClaimForUri` (i.e. no need to split into 4 selectors anymore), since we've updated the reducer to prevent invalidation from things like `confirmations` and `is_my_output`.

Fix blacklisted claims appearing in tiles

---

ui/page/notifications/view.jsx
ui/scss/component/_notification.scss

Closes #312 Save notification on back navigation, enable filter on mobile
- Don't clear then filter when mounted and there are unread notifications.
- We previously clear the filter because the user could be clicking the notification bell (which is showing some number) and we ended up with a blank page because of the filter.
- Show the filter drop-down in mobile.
- Previously, it was intentionally removed for mobile (see bd42418f). I believe it was just because we don't have the style set up for mobile. Here's my quick attempt -- not the best looking...
`kp` dev instance

Notifications filter changes

---

ui/component/fileViewCount/index.js

Get active viewers even when not live (we want waiting count)
We only select active viewers when live.
Always select active viewers.
</details>

Get active viewers even when not live (we want waiting count)

---

ui/redux/actions/app.js
ui/redux/actions/notifications.js

- Large resolve count on bootup.
- Skip the resolve call on sign-in (we just want the notification count). The same call will happen when you click the notification bell, so it's not too late to resolve at that time.
- Added `true` to `doResolveUris` to return cached results, otherwise it will keep resolving the same channels every time we enter Notifications Page.

Notifications: skip resolve during boot

---

ui/component/claimLink/index.js
ui/component/claimLink/view.jsx

- It was checking the blacklist on every render.
- Finding opportunities to improve performance.
Since the final destination will be a dead end anyways, skip the blacklist-check so that livestreams can render a bit faster when there lots of mentions.
The only downside is that a claim preview for a blacklisted item would now appear (vs. being a text previously)

ClaimLink: skip blacklist check

---

static/app-strings.json
ui/component/webUploadList/internal/web-upload-item.jsx
ui/scss/component/_claim-list.scss
web/setup/publish-v2.js

#276 improve upload error handling 
- `tus-js-client` clears the upload fingerprint on any 4xx error, which makes it not resumable and ended up creating a new session instead.  So, when a user tries to resume the same session/file from 2 different tabs concurrently, one of the tabs eventually hits `423` and starts a new upload session, hence the double SDK calls.
- Detect and disallow concurrent uploads.
- Use the client's "vimeo mode" (direct URL mode) to bypass that odd behavior of creating a new session on failure.
- Fortunately, there is this direct URL mode, otherwise we would need to fork. We (Randy and I) still think it's odd for the client to do that -- it should let the user decide if they want to give up or not.

TUS: Detect and disallow concurrent uploads

---

static/app-strings.json
ui/component/app/view.jsx
web/effects/use-degraded-performance.js

When sync fails, we crash the app.
Maybe handles [#39 Better handle both internal and web backend interruptions / downtime](https://github.com/OdyseeTeam/odysee-frontend/issues/39) too?
I'm tackling this from the standpoint that (1) sync errors are not that fatal -- we'll just lose a few recent changes (2) network disconnection is the common cause.
1. Downgrade the crash to a nag.
2. Detect if it's just a simple network disconnection, and tell the user.
3. If it's not network disconnection, tell the user that settings are now potentially unsynchronized. Then, add a button to retry to sync.
Try @ `kp`
Besides disconnecting the network, I don't really know how to simulate an actual sync error -- I just tweaked the code locally.
I'm not listening to `navigation.onLine` to keep things lite. …

SyncFatalError: show nag instead of hard-crashing.

---

ui/modal/modalError/view.jsx

This is a known state that is now handled in the GUI.

TUS: Skip logging "423/409 concurrent upload" errors.

---

ui/component/app/view.jsx

If SecurePrivacy loads some scripts but not others, it can cause issues
This workaround ensures that __tcfapi function is available and will not cause issues with the banner

Workaround for SecurePrivacy issues with VPNs

---

ui/page/discover/view.jsx

Closes [#155 All live streams show on tag explore/discovery page + content type filters don't work there](https://github.com/OdyseeTeam/odysee-frontend/issues/155)
`!dynamicRouteProps` wasn't good enough to determine if it's Wild West. Use direct path instead.

Fix livestream tiles appearing in Tag Search

---

ui/component/commentMenuList/view.jsx
ui/constants/token.js
ui/lbry.js
ui/modal/modalBlockChannel/index.js
ui/modal/modalBlockChannel/view.jsx
ui/page/show/index.js
ui/page/show/view.jsx
ui/redux/actions/claims.js
ui/redux/selectors/claims.js
ui/redux/selectors/comments.js

@tzarebczan, I still have some scenarios to test, but I think I've tested enough for us to try in parallel.  Need to help to verify the API call (even though the change is just to omit the auth header).
----
Part of [#306 Optimize backend calls (try to use non-auth and batching where possible) ](https://github.com/OdyseeTeam/odysee-frontend/issues/306)
- `apiCall`: allow clients to add `no_auth` in the existing `param` to signal that we don't want to send the headers (it is doing that by default).  The function will strip off `no_auth` before sending the actual payload.
- `doResolveUris`: default to no-auth as `page/show` is the only place that actually needs it to be populated.
- In other non-critical areas like Claim Context Menu, use the signing channel to check if the claim is ours. …

Un-authenticated `resolve`

---

ui/component/claimListDiscover/index.js
ui/page/discover/view.jsx

Closes #9: Wild west + scroll down tries to reload livestreams

Fix livestream tiles reloading placeholders then scrolled

---

ui/analytics.js
ui/page/livestream/view.jsx

#85: "user joined livestream"
Add `loaded_livestream` into the existing `player :: action` event, so we can compare it against `loaded_video | loaded_image | loaded_markdown | loaded_audio`.

GA: entered livestream

---

ui/component/claimListDiscover/view.jsx
ui/component/claimTilesDiscover/index.js
ui/component/settingContent/view.jsx
ui/redux/reducers/settings.js
ui/util/buildHomepage.js

Note: when I first tried it, I was still seeing duplicates with `--remove_duplicates`.  After lunch, things started to work.  I confirm that my params remained the same before and after lunch.  Perhaps my hub switched .... i.e. some hubs are not old?
Closes [#37 Examine re-enabling reposts on odysee homepage](https://github.com/OdyseeTeam/odysee-frontend/issues/37)
- Added `--remove_duplicates` to Tile and List `claim_searches`.
- Brought back the "Hide reposts" setting.

Re-enable reposts on homepages

---

ui/component/app/view.jsx

If page is detected to be loaded in an iframe, don't run SecurePrivacy

Don't run SecurePrivacy on iframes

---

ui/component/viewers/videoViewer/view.jsx

Closes [#189: Overall React Lag or Extra Re-renders / Volume slider laggy since v0.48](https://github.com/OdyseeTeam/odysee-frontend/issues/189)
Potential cherry-pick for https://github.com/lbryio/lbry-desktop/issues/4862
Every redux update results in each mounted component's prop mapping function (the `select` and `perform` stuff) to be recalculated. This is normal per redux, but we do lots of heavy stuff there.
The slider was sending tons of redux update for the Volume and Muted setting.
The redux volume/muted setting is just used to restore vjs to the user's setting on the next video, so it doesn't need to be updated immediately/constantly -- vjs keeps it's own video settings.  Debounced that action.
You should see only 1 pair of said redux changes per finalized slider position change.

Debounce volume and muted state update.

---

config.js
web/src/html.js
web/src/lbryURI.js
web/src/oEmbed.js
web/src/routes.js
web/src/rss.js

Already live on https://salt.odysee.com/
- Here is an example request: https://salt.odysee.com/$/oembed?url=https%3A%2F%2Fsalt.odysee.com%2Flbry%3A%2F%2F%40Kona_and_Suba_Guinea_Pig_Adventures%23c%2Fdinner-time!%234&format=json
- Here is Embedly's validation tool: https://embed.ly/providers/validate/oembed?endpoint=https%3A%2F%2Fsalt.odysee.com%2F%24%2Foembed&url=https%3A%2F%2Fsalt.odysee.com%2F%40Kona_and_Suba_Guinea_Pig_Adventures%3Ac%2Fdinner-time%21%3A4

add oEmbed Support for video claims

---

ui/component/sideNavigation/view.jsx
ui/scss/component/_navigation.scss

`kp` dev instance
- Moved Notifications to the top for mobile.
- Added separate lines between sections.
The array method is too restrictive (hard to move things with display logic around). It's also hard to read.
Instead of trying to populate an array, just directly populate the return tree. Added `getLink` to make things readable. It's now easier to see the sections in a glance, and move things around in the future.

Mobile: move 'Notifications' to the top

---

extras/recsys/recsys.js

Brave's shield blocks the clickstream endpoint. uBlock origin
does not (it seems).

Change clickstream endpoint for brave's shield

---

web/component/ads/view.jsx

Tom seeing crashes on the line that was trying to remove the script, saying it's not a child of that node.
- I'm guessing the found `fjs` sometimes is not in `head`, but we always remove from `head` during cleanup. Just append to the bottom of head, and remove from head. I think script order doesn't matter if we are injecting at runtime?
- Fixed effect dependency while at it (the latest PR removed the need to check for `type`).

Change ad script injection method + fix effect dependency

---

ui/component/claimPreview/view.jsx
ui/redux/selectors/subscriptions.js
ui/util/claim.js

Closes [#317 Can't remove abandoned channel ](https://github.com/OdyseeTeam/odysee-frontend/issues/317)
Affected areas:
- "blocked and muted" page
- "channel" page that has been abandoned
See commit messages for details

Fix inability to unblock and unsubscribe an abandoned claim

---

ui/page/discover/view.jsx

Closes [#390 Wild west > show all livestreams > click > back = livestreams not expanded ](https://github.com/OdyseeTeam/odysee-frontend/issues/390)
Available in test instance
Wanted to put it as an injected tile, but requires more work to do it in a general-purpose way, as opposed to a hardcoded way like how ads are currently injected. It also needs to work on both Tile and List format.
So ... just place the button at the upper-right for now. Although a bit odd, at least it'll be a consistent place (i.e. position won't be affected by live tile count).
See commit messages

Add persistence to live tile expansion in Wild West

---

extras/lbryinc/redux/selectors/ban.js
ui/page/channel/index.js
ui/page/channel/view.jsx
ui/page/show/index.js
ui/page/show/view.jsx

We already have a pre-calculated map, but not used except for comments.
At the expense of pre-calculating it, the subsequent queries are instantaneous compared to the loop.
We are still not perfect in terms of reducing re-renders, so this helps a lot.

Blacklist: use existing map instead of looping

---

ui/scss/component/menu-button.scss

Issue Number: 
Currently, menus have their transform origin in the middle so they expand from the center.
This PR sets the transform origin on the top of the menu. 
Unfortunately, when there isn't enough screen space to display the menu below the target element, the menu will appear on top and it will look like this:
It would be nice if it was possible set the transform origin on the bottom if the menu is above the target element
That would look like this:
I couldn't figure out an easy way to determine if the menu was above or below the target element, so I jus set the transform origin to the top in all cases. I think this makes sense because according to the [reach ui menu button docs](https://reach.tech/menu-button/#menupopover-position), the menu will always try to position itself …

updated the transform origin for menus

---

ui/page/discover/view.jsx

Fix category page labels not being translated

---

ui/component/commentCreate/view.jsx

Issue Number:  possibly related to #297
even if the button is disabled, the function shouldn't allow tips to be re-sent without a success or fail return, or else multiple might end up being charged at once

Only allow to resubmit a tip when a previous has completed or failed

---

flow-typed/publish.js
static/app-strings.json
ui/component/app/view.jsx
ui/component/webUploadList/internal/web-upload-item.jsx
ui/component/webUploadList/view.jsx
ui/constants/storage.js
ui/redux/actions/publish.js
ui/redux/reducers/publish.js
ui/util/storage.js
ui/util/tus.js
web/setup/publish-v1.js
web/setup/publish-v2.js
web/setup/publish.js

kp.odysee.com
- [Better tab-sync / tab-lock to prevent unnecessary error ](https://github.com/OdyseeTeam/odysee-frontend/issues/276#issuecomment-983655883)
- Pre-work for upcoming [#426 Prevent concurrent uploads with same lbry name](https://github.com/OdyseeTeam/odysee-frontend/issues/426) -- fix the key clash part first.
- When you upload on one tab and open another tab, the other tab should say "it's being uploaded in another tab".
- When the upload completes, both tabs should not show the item (in the previous version, the upload item lingers in the second tab and clickable).
- When both tabs are up and both are refresh, both will be in the stopped state.  You can resume from either tab, and the other tab will say "it's being uploaded in another tab".

Upload: tab sync and various fixes

---

ui/scss/component/_button.scss
ui/scss/component/_file-render.scss
ui/scss/component/_videojs.scss

- Closes [#300 Video: control bar misalignment](https://github.com/OdyseeTeam/odysee-frontend/issues/300)
- So many `!important` overrides that makes it hard to customize for the upcoming chromecast button.
- Weird `813px max-width` check -- it feels random, plus does not adjust accordingly to zoom-levels.
- The button text is not always vertically centered for all layout and zoom-levels because it is being centered using hardcoded margins.
- The 2 popups don't have consistent fonts and styling, plus their customizations are all over the place.
- Try to remove as many unnecessary `!important` as possible. Adding specificity is sufficient, and won't block other customizations.
- Try using `rem` instead of hardcoded margins. The icons/text/margin should resize accordingly per zoom-levels.
- …

Videojs css fix

---

ui/component/commentCreate/view.jsx

Issue Number: Closes #315
`Cancel` wasn't clearing the selection, so if a sticker was selected it would consider a sticker is selected to be sent when trying to comment

Fix cancel sending Sticker anyway

---

ui/page/discover/view.jsx

I accidentally over-limited it to Wild West when trying to exclude Tag Searches from showing livestreams.

Fix missing livestream in Category Pages

---

ui/component/claimList/view.jsx
ui/component/page/view.jsx
ui/constants/classnames.js

Cross-importing was making things hard to code-split efficiently, because the entire file gets evaluated when imported.

Move MAIN_CLASS to constants file for better code-splitting.

---

ui/page/show/index.js

- Using `selectIsSubscribedForUri` instead, because the given uri is in Canon while the subscription list is in Permanent, so the result was always `false`.  `selectIsSubscribedForUri` looks up the claim for the Perm.

PageShow: fix `isSubscribed` always `false`

---

static/app-strings.json
ui/component/publishName/index.js
ui/component/publishName/name-help-text.jsx
ui/component/publishName/view.jsx

Closes #464 
Currently, we check if we have any existing claims with the same name when uploading, i.e. "lbry://name". It does not include claims that you are still uploading, so you might end up with duplicate claims.
In the ticket, there is also the issue of 2 uploads sharing the same GUI slot, causing the progress indicator to jump between the uploads. That has been fixed by a prior PR using a guid instead of using `name`.
I think there is another request to allow the same name but on different channel ... next time, next time ....

Prevent concurrent uploads with same lbry name

---

.env.defaults

- Moved to default file + store in git for better tracking of changes.
- Updated 2 of them to use a faster version.
- `LOGIN_IMG_URL`: no need to grab full size + faster from direct url.
- `FAVICON`: not much benefit resizing an already-small image.
**NOTE:  the affected envs need to be removed from the prod customizations.**
----
For the odysee logo, it's also super huge, but leaving as-is for now as Raphael is looking at converting it to SVG.

Image env changes

---

ui/component/viewers/videoViewer/internal/plugins/videojs-mobile-ui/touchOverlay.js
ui/scss/component/_file-render.scss

Closes https://github.com/lbryio/lbry-desktop/issues/6844
This negates 49abbec.
Now that we have a dedicated chromecast button, we don't need to hack Chrome's default cast button to appear on top of vjs-mobile-ui.  The hack no longer works anyway, since the CSS exposure has been deprecated around mid 2020 -- it is still available, but its abilities has become less and less.

Remove old mobile chromecast css hack

---

.env.defaults

I'm trying to figure out what's causing our "odysee" search term to show simple results ...
...while "odysee.com" shows the rich results:
I think it is less likely for someone to type "odysee.com" in a search, so this is not ideal.
My guess is `OG_HOMEPAGE_TITLE` might be the culprit.
Even if `OG_HOMEPAGE_TITLE` is not the culprit, I think the cards look better with the change anyways since it is currently showing double URLs.
before --> after

`OG_HOMEPAGE_TITLE`: 'odysee.com' --> 'Odysee'

---

ui/page/discover/view.jsx

- Log out
- Wild West
- Click "Show more livestreams"
- Click "Show less livestreams" (top-right corner)
- Crash

Disable ads in Wild West until ads fail more gracefully

---

ui/scss/init/_vars.scss

Issue Number: 🧀
Player height in theater mode is too long that only the title is visible and you have to scroll down to see the like/dislike and share buttons.
Player height in theater mode is just enough to see like/dislike and share buttons without scrolling down.
#
</details>

Changed max inline player height

---

ui/scss/init/_mixins.scss

https://www.notion.so/Performance-Fixes-927f825a5d674bd09323830be1d263af#1beab2fee011421492b56b88f68681a3
> _We currently lazy-load the tiles in the category sections (but not the sections themselves, because we want to retain scroll position on Back action). This puts gray placeholders until the section is visible on screen.  which turns out to be quite expensive, because the placeholders are animated, so we have a perpetual animation in the background after the homepage loads + user did not scroll._
Just disable the barely-noticeable animation for now.
There are alternatives, but probably not worth polluting the code with:
- Just like the thumbnails, use intersection observer to decide when to animate.
- Find solution to the "lazy load section + need to retain scroll position".

Disable `placeholder` animation

---

ui/page/home/view.jsx

The ad tile causes a layout shift on certain screen/zoom, pushing CLS from green to red.
- Do replacement instead of insertion. 
- Fixed "null lastCard" flow warning instead of suppressing it.
Hopefully the changes are small enough to not overlap/mess if other pending work.

Home: prevent layout shift from ads

---

ui/component/claimList/view.jsx

Fix the view more/less functionality by properly reporting the total number of claims
Claim length is being reported after the claim list has been truncated.
Total number of claims is now reported correctly.
</details>

Hotfix the view more/less functionality

---

ui/redux/reducers/publish.js

Apparently, a user is experiencing `423 locked` errors from the server, which should not happen given the locking mechanism plus the user wasn't trying to do concurrent uploads.
The Resume button was missing, which made things worse.
Anyway, fix the Resume button so that at least they can try to resume.
Still not clue what would cause the `423 locked`, but should be something related the backend's file-locking stuff.

Publish: fix Resume button not appearing after 'conflict'

---

ui/scss/all.scss
ui/scss/component/_animation.scss
ui/scss/component/_comment-create.scss
ui/scss/component/_emote-selector.scss
ui/scss/component/_file-price.scss
ui/scss/component/_sticker-selector.scss
ui/scss/component/_view_count.scss
ui/scss/component/claim-preview-reset.scss
ui/scss/component/notifications-banner.scss
ui/scss/init/_breakpoints.scss
ui/scss/init/_gui.scss
ui/scss/init/_vars.scss

Issue Number: 🧀🧀
`init/vars.scss` being imported multiple times to the `<head>`. Probably because breakpoints inside `var.scss` were going to be converted into native css variables but they weren't able to because @media queries doesn't support css variables. So they had to import it multiple times to use breakpoint scss variables. 
`init/vars.scss` being imported only once and for that breakpoints separated into a new file init/breakpoints.scss
No breaking changes I'm aware of.
</details>

Fixed vars.scss being imported multiple times

---

ui/component/app/view.jsx
ui/effects/use-connection-status.js

Was trying to save one event listener in the previous implementation and rely on other redux state-changes to spark a GUI update, but turns out there are scenarios where nothing is updated and the "offline" nag is stuck on screen.
Do it properly using the event listeners. The nag should now update promptly.

Fix "you are offline" nag being stuck

---

ui/util/web.js

Closes #513 Meta: Invalid "card.odysee.com" used as thumbnailUrl
```
const encodedURL = Buffer.from(url).toString('base64');
```
The above won't work for a `data:image` thumbnail, so just skip it.  I believe the rest of the code will fallback to the default OG image when nothing is returned, but need a review just in case I missed something (oEmbed?)
I think the GUI is already blocking `data:image`, so these are just a handful, probably coming from older Desktop app or cli

OG: Skip 'data:image' when generating cards.odysee.com urls

---

flow-typed/livestream.js
ui/component/channelContent/index.js
ui/component/channelContent/view.jsx
ui/component/claimListDiscover/context.js
ui/component/claimPreviewSubtitle/index.js
ui/component/claimPreviewSubtitle/view.jsx
ui/component/claimPreviewTile/view.jsx
ui/component/fileSubtitle/view.jsx
ui/component/livestreamDateTime/index.js
ui/component/livestreamDateTime/view.jsx
ui/component/livestreamLayout/view.jsx
ui/component/livestreamLink/view.jsx
ui/component/scheduledStreams/view.jsx
ui/page/livestream/index.js
ui/page/livestream/view.jsx
ui/redux/actions/livestream.js
ui/redux/reducers/livestream.js
ui/redux/selectors/livestream.js

Add stream start to active live streams, and refactor how active livestream data stored in redux
Active live streams show the release time.
Active live streams show stream start time.
</details>

Add stream start time to active live streams

---

ui/redux/actions/rewards.js
ui/redux/selectors/rewards.js
ui/rewards.js

Closes #531
> _but beamer can add to the "recurring" reward, probably easier_
Adding the last claimed date would remove the need for the history loop.
For now, I think there could be users with a long history, so only look up to 15 items from the back.

Change logic for daily reward claiming to weekly

---

ui/redux/reducers/subscriptions.js

This was found by Miko while testing the "fast action" PR, but is reproducible in production.
- Do a search like "Test" and filter to "Channels Only".
- Follow a bunch @test channels
- Unfollow any one of them. All of them gets unfollowed.
The change in b9fc9b63 to compare the lower-case channel name probably made it even worse, as something like `@TeSt` would be removed too.
Not sure why channel name was used in the first place ... perhaps it was to cover canon vs perm uri?  Or something to do with deleted channels?
Anyway, comparing uri makes more sense, so doing that instead.

Fix: unsubsribe action removes all with same name

---

ui/page/notifications/index.js
ui/page/notifications/view.jsx
ui/redux/actions/notifications.js

Part of "[#385 Defer api.odysee.com calls to their respective pages / install new](https://github.com/OdyseeTeam/odysee-frontend/issues/385)"
Pull out `notification/categories` from `doNotificationList` and fetch it in Notifications Page. I don't there there are other places that need it for now.

Defer `notification/categories`

---

ui/component/claimTilesDiscover/index.js
ui/component/claimTilesDiscover/view.jsx
ui/redux/selectors/claims.js

Closes [#555 Don't refresh tiles/claim search after blocking results are in + don't change](https://github.com/OdyseeTeam/odysee-frontend/issues/555)
Also includes prop optimization commit, so the diff is larger.  Actual fix is just a few lines in the last commit.

Don't refresh tiles while fetching and if same results

---

ui/redux/actions/app.js
web/component/browserNotificationSettings/use-browser-notifications.js

- If an API is down the user can be undefined. We should verify user is defined to avoid errors.
- Make sure analytics reporting doesn't interrupt subscription flow.
- clean up duplicate code
- Even though a user object is expected to be present whether logged in or out, if an API is down the user can be undefined. If the user is undefined the push notification code will fail.
- A failure in analytics reporting could potentially cause the notifications ui to report a failure.
- Push notification code checks user is defined.
- analytics can't affect subscribe ui.
</details>

Update push notifications system

---

ui/redux/actions/app.js

- Slow for users with many channels.
- The need to do it in Sync Loop is more applicable to Desktop.
- Decided to just remove it from sync loop.
- It will still be called when entering `/$/channels`, so that's an alternative to fix things when it is out of sync.

Remove `channel_list` from end of Sync Loop

---

ui/component/publishAdditionalOptions/view.jsx
ui/component/publishFile/view.jsx
ui/component/publishForm/view.jsx
ui/component/publishReleaseDate/view.jsx
ui/component/publishStreamReleaseDate/view.jsx
ui/constants/publish_sources.js
ui/modal/modalPublishPreview/view.jsx
ui/redux/selectors/claims.js

- Fix publish form when editing a livestream claim. 
- Hide internal tags from publish modal.
Editing a livestream puts the form in to a broken state that makes it difficult to adjust the scheduled date/time.
Editing a livestream puts the form in to a correct state and exposes the appropriate date/time controls based on source.
</details>

Fix publish form when editing livestream 

---

ui/i18n.js
ui/redux/actions/settings.js
web/webpack.config.js

In the original Desktop code, new strings encountered during runtime will be automatically added to the local `app-strings.json` file. The feature is unavailable in Web because writing to file would require explicit permissions.
Partially restore the functionality by saving the strings to memory and retrieving it from the console via `copy(window.new_strings)`. It's a little bit of manual work, but I think it is good as it forces a sanity check before committing (previously, experimental/developmental strings are committed and being translated in Transifex).

i18n: restore ability to retrieve new i18n strings

---

ui/constants/storage.js
ui/redux/reducers/publish.js
ui/util/tus.js

- Closes #592
- It was possible for an upload to stay "locked" e.g. when browser is killed.
When refreshing or opening a new tab, always clear the locks. The on-going sessions will re-lock them immediately.

Uploads: prevent perpetual locked upload

---

ui/component/fileViewCount/view.jsx

fetch for view count should not only happen on initial render, but also when the claim id changes. (side effect from misunderstanding of a previous issue)
</details>

Make sure view count fetch runs when claim ID changes.

---

ui/redux/actions/sync.js

- When signing up, the "channel suggestions" page was stuck because `prefsReady` was never set as `preference_get` was never called.
- It was never called due to the optimizations to skip it when there is no difference between the local and server wallet.
- The first ever `sync/get` will result in a "no wallet" error, and there is already a `catch` to handle it. But the change in 38c13cf5 caused the `catch` to be skipped and went directly to `sync_apply` instead. Although the `catch` is also doing the same thing (`sync_apply`), it also has an additional callback to call `preference_get`.
- Fixed by ensuring this scenario ends up in the `catch` block like it was originally intended.
- We also did some optimization in the callback to skip the final `preference_get` if there is no difference …

Sync: fix new user sign up flow

---

web/index.js

f0cd1592 did an additional call instead of replacement.
Aside: the 1 hour value only has effect in dev instances. For prod, CloudFlare seems to override that to 4 hours.

Skip checking DIST_ROOT twice

---

static/app-strings.json
ui/component/channelEdit/view.jsx
ui/component/channelThumbnail/view.jsx
ui/component/selectAsset/view.jsx
ui/constants/cdn_urls.js
ui/redux/actions/publish.js

Should handle more file types now, and return errors (need to add proper error parsing: ```webparray(2) { ["type"]=> string(5) "error" ["message"]=> string(56) "Upload valid images. Only GIF, PNG and JPEG are allowed." }```

Take 2: speech > thumbnails CDN upload

---

ui/redux/actions/publish.js

I'm leaving the generic "Unexpected JSON" error alone for now, as I think this should be fixed at Nick's end.

Thumbnail uploads: report file details

---

ui/component/headerProfileMenuButton/index.js
ui/component/headerProfileMenuButton/view.jsx

Closes [#627 account header doesn't refresh on sign up / log in](https://github.com/OdyseeTeam/odysee-frontend/issues/627)
Looking back at [[Header] Changes, fixes and improvements (#493)](https://github.com/OdyseeTeam/odysee-frontend/pull/493), noticed that old code was looking at `has_verified_email` instead of just checking whether an email exists. So, restored original code.
This does have a side-effect of the Logout button not showing any email address underneath it immediately after sign up (with the flow cancelled). But I vaguely recall it was that way previously. A refresh cleans it up.
Perhaps another `user/me` when leaving the Sign Up page can make everything in sync, but this PR simpler to test.

Fix: account header doesn't refresh on sign up / log in

---

ui/component/sideNavigation/view.jsx

[Issue Number: 594](https://github.com/OdyseeTeam/odysee-frontend/issues/594)
On mobile, when the page loads the menu is initialized to open and then animates to closed.
On mobile, when the page loads the menu is initialized to closed.
</details>

mobile menu fix animation close on page load

---

ui/component/viewers/videoViewer/internal/videojs.jsx

Vidcrunch makes an invisible Aniview video player div that covers up the DOM and breaks the app because it causes a lot of the buttons to not work. It shows up after you scroll down to the video div. This code hides the video player until the user scrolls to the ad and the video is rendered and becomes visible.

Fix vidcrunch on ios to only show ad when its scrolled to

---

ui/component/claimList/view.jsx

When the "Upcoming livestream" appears in a list, infinite scroll stops working.
The difference between `mainEl.getBoundingClientRect().bottom` and `window.innerHeight` became slightly greater than 0.5, so it was deemed as "haven't reached the bottom".
Coincidently, I've been wanting to make the inf scroll load earlier (instead of after reaching the absolute bottom) to make the experience smoother, so added a 200px threshold, which is roughly the height of a tile. This gets us the new behavior while also fixes the original problem.

Fix infinite scroll when "Upcoming livestream" appears

---

ui/component/claimPreview/index.js
ui/component/claimPreview/view.jsx
ui/component/common/tooltip.jsx
ui/component/fileViewCount/index.js
ui/component/fileViewCount/view.jsx
ui/util/string.js

Received complaints -- some people prefer to see full resolution.
- As a compromise, we'll only apply the compact notation when then value is greater than 10k, with the exception for Tile View Counts where we'll always apply it due to space limitation.
- Also added Tooltip for Follower count.
- The string was always in 'en' locale in some instances, so it wasn't grouping up digits properly in Japanese, for example.

View/Follower count: only use compact when > 10k 

---

ui/component/channelContent/view.jsx
ui/component/scheduledStreams/view.jsx

Don't show the hide setting on the upcoming list on channel page.
The scheduled stream hide setting is visible on channel pages.
The scheduled stream hide setting is visible only on home and following pages.
</details>

Don't show the hide setting on the upcoming list on channel page.

---

ui/component/scheduledStreams/view.jsx

This wasn't causing any issues, but in any case, we should be more precise and query specifically for streams. 
The query for scheduled streams uses the default claim types in it's query. (stream, repost, channel)
The query for scheduled streams specifically queries just for streams.
</details>

Make sure to specifically query for streams in the scheduled listing

---

ui/page/discover/view.jsx

Behavior we want:
- hide Advanced Filter for Wild West
- show Advanded Filter & Filter for everything else
Note:
Requires the other PR for the filters to work correctly, but both are testable in `kp`

Fix advanced filter showing up in Wild West

---

ui/component/claimListDiscover/view.jsx

Putting up on `kp` for testing (building...)
----
After enabling Advanced Filter in Category Pages, the 'Content Type' filter only works for "repost/video/list".
When `streamType` is not provided, it defaults to 'Video|Audio', making it always "defined":
```
streamType = SIMPLE_SITE ? [CS.FILE_VIDEO, CS.FILE_AUDIO] : undefined,
```
This seem to override the purpose of `defaultStreamType`, which will not be used unless the client explicitly set `streamType=null`, which currently is only being applied for `RECENT_FROM_FOLLOWING[]`.
```
const streamTypeParam =
streamType || (CS.FILE_TYPES.includes(contentTypeParam) && contentTypeParam) || defaultStreamType || null;
```
Cleared the forced default and let it fall back to `defaultStreamType` instead.

Fix ignored 'Content Type' filter

---

ui/component/claimListDiscover/view.jsx

`kp`
Channel Page 'Content Type' filter not working
The Advanced Filter work by placing a `?content=` URL param. The list component then parses it and makes the `claim_search` params accordingly. But:
1. There is a mix up in how the list component treats `?content=`.
- The original code seems to treat this as a way to define the type externally but only for a list without `claimType` defined via code. In other words, if `claimType="something"`, `?content=` is ignored.
- On the other hand, the Advanced Filter relies on `?content=` being used.
2. `?content=` is then split between `claimTypeParam` and `streamTypeParam`. The current code does not check if the split makes sense, e.g. if `?content=channel` and `streamType` was `['video']`, these 2 are incompatible and produces no results.
1. …

Resolve claim and stream types when there is a filter

---

ui/comments.js

This will be an exception where the non-wrapped version is easier to read.

Comment api: re-format to single-line.

---

ui/redux/reducers/subscriptions.js

Closes #644 investigate following vs subscription preference data
- iOS app uses colon for following/subscriptions.
- Front-end code handled the "colon vs. hash" for `CHANNEL_SUBSCRIBE,` but not for `CHANNEL_UNSUBSCRIBE`
Not really sure what's going on in the iOS side:  unfollowing from Web does clear the entry in the wallet (confirmed from Desktop), but iOS stays followed.  Is it just not syncing correctly?
_update: yeah, just a live sync problem.  Killing the app and restarting fixes it ... I guess it syncs only on startup_

CHANNEL_UNSUBSCRIBE: handle colon vs. hash uris

---

.gitignore

I'm proposing a minor addition to the .gitignore file to accommodate vscode.  By default, even with the flow extension installed, it throws errors about the flow types that it is mistaking for typescript type annotations, which are only allowed in .ts(x) files:
By ignoring this directory, we can disable the validation for the workspace, allowing leaving this to flow.

Ignore .vscode directory to allow disabling js typechecking.

---

package.json
web/package.json
web/yarn.lock
yarn.lock

Updating nodemon to the latest version to open up use of the --inspect flag for remote debugging.

Upgrade nodemon to latest and add --inspect flag for remote debugging

---

flow-typed/Comment.js
ui/redux/actions/comments.js

Commentron json params are usually underscored instead of camel-cased.
Double-checked commentron code:
```
// MentionedChannel channels mentioned in comment
type MentionedChannel struct {
ChannelName string `json:"channel_name"`
ChannelID   string `json:"channel_id"`
}
```
I don't get notified on either format though ... maybe it's not enabled in commentron yet.

Corrected `mentioned_channels` parameter name

---

static/index-web.html

In 36fe7366, the approach to fix the "missing chunk" error and user using old code was to disable caching on the html so that user always grabs the one that's pointing to the latest ui.js.
But https://cristian.sulea.net/blog/disable-browser-caching-with-meta-html-tags/ says 3 sets of `meta` is needed to, and we missed out one. That probably explains why refreshing sometimes does not work, although I've also read that some browsers simply ignores these meta.

Fix "don't cache html" meta tags

---

ui/redux/actions/collections.js

A huge list like http://localhost:9090/$/list/d91815c1bc8c80a1f354284a8c8e92d84d5f07a6 (193 items) often produces fewer results in the final rendered list.
The same list of IDs was passed into `claim_search`, and we just increment the `page` for each batch of 50. However, it seems like `claim_search` does not honor the order between each call, and some results from the previous page took the place of the results in the next page.
When batching, slice the ID list ourselves to bypass the problem for now.

The case of the missing Collection item

---

ui/component/livestreamComment/view.jsx

Closes #295 Livestream chat: Deleting comment that was already deleted by someone else, makes chat blank.

Comment options: hide "Remove" when comment is removed.

---

ui/component/claimList/view.jsx

From the Draggable PR, the draggables retained the key but regular lists lost it.

ClaimList: fix missing key

---

ui/component/claimPreviewSubtitle/index.js

Closes #87 Repost - Top result should show followers properly"
The winning url for "bret" search is "lbry://bret", which is a repost.
We need to use the canon url to retrieved the fetched view count.

Top Search: handle sub count for Repost

---

ui/component/socialShare/index.js
ui/component/socialShare/view.jsx
ui/page/invite/index.js
ui/page/invite/view.jsx
ui/redux/actions/user.js
ui/redux/selectors/user.js

Closes #385
As mentioned in the ticket, the current places where that info is needed is in the Invites Page and Social Share Component.
1. Invites Page: it is already doing the fetch on mount, so no issue there.
2. Social Share: show spinner until the data is fetched.

Defer `user/invite_status` from startup

---

ui/component/fileActions/view.jsx

Fixes https://github.com/OdyseeTeam/odysee-frontend/issues/663
The query param was not being encoded for the query string side. A "+" on the path side is valid, but represents a space in the query string and needs to be encoded.

Correctly encode the path for query string

---

ui/component/autoplayCountdown/view.jsx

On large screens, the comment field and autoplay countdown can both be visible at the same time. The currently code only stops the timer when the countdown component is not visible on screen.
The page annoyingly navigates away while typing.
When servicing the timer, check if the current active element is an input type. As far as I know, there is no React equivalent for this.

Stop autoplay-next countdown when any input is in focus.

---

ui/component/viewers/videoViewer/view.jsx

Fixes https://github.com/OdyseeTeam/odysee-frontend/issues/689
The core issue is that the function `centerPlayButton` was utilizing the audio tag, which was not rendered and giving 0's for initial measurement variables.  Walking up the dom to the video parent element guarantees a div that can be measured with the expected dimensions.
This fixes the immediate bug, but likely worth returning to at some point to see if this can be done with CSS.
Verified fixed when embedded:
Verified no regressions on post pages:

Fix play btn calcs as audio tag was not measuring as expected

---

ui/constants/file_render_modes.js

Closes [#761 Should Posts have embed links](https://github.com/OdyseeTeam/odysee-frontend/issues/761)
The original code also supported text modes like PDF and also images, all of which looked really bad, so it's unlikely someone is utilizing it.
Disabling them until a designer can fix 'em.

Limit embed generation to just Audio and Video

---

.env.defaults
config.js
extras/recsys/recsys.js

Easier to point to a localhost server to capture the beacons for debugging.

Move recsys endpoint to .env for easier debugging

---

ui/component/viewers/videoViewer/internal/videojs.jsx
ui/component/viewers/videoViewer/view.jsx
ui/constants/pages.js
ui/constants/player.js
ui/page/file/view.jsx
ui/redux/actions/content.js
ui/store.js

"Fixes" https://github.com/OdyseeTeam/odysee-frontend/issues/20
@infinite-persistence, I'm not certain if this interfere's with what you might have in flight on this ticket, but this will patch two of the three issues until the api issue can be resolved.  Essentially, it just assumes that if there's a time stored, but there is no length known, then it assumes the stored time is correct.  Also, on dispose, if it's almost done, we'll just clear the saved time.
Of the three bugs noted, this won't address the cross-tab issue.

Patch to restore position upon returning to video until more fully fleshed out fix can be introduced

---

ui/component/viewers/videoViewer/view.jsx

Issue Number:https://github.com/OdyseeTeam/odysee-frontend/issues/776
click => dispatch => updateProps => render
this takes about 1000ms - 1500ms (Macbook pro 16 (2019), i7, 16gb, chrome 6x slowdown)
click => updateLocalState => render => dispatch => updateProps => render
this takes about 100ms - 300ms (Macbook pro 16 (2019), i7, 16gb, chrome 6x slowdown)
This is following a design principal known as "optimistic UI" where you do an action later but show its optimistic response first, not the biggest fan but in situations like this it works in a pinch.
One improvement that I could recommend is what if dispatch fails then the toggle should go back to its original state, but I don't ever see that happening so I undid that part for now.     
Please …

Fix autoplay next

---

ui/util/web.js
web/src/html.js

Issue Number: closes #828
working here: https://salt.odysee.com/@MasoniteShadow:9/odysee!-what-has-changed-and-why-i'm:4
simply reversed the `escapeHtmlProperty` into a new `unscapeHtmlProperty` and even if some characters are invalid for claim uris, the app should return the appropriate response then. Should be fine here since `requestPath` is used for resolve and nothing else is replaced? still needs review

Unscape uri before Claim resolve

---

web/src/html.js

`Lbry.resolve` won't work with timestamps in the url.

Strip timestamp from url when resolving for OG

---

web/src/html.js

`/$/embed/尾崎豊--－-大阪球場ライブ%E3%80%801_6/bfd63daa9453bb1a11674ca8a7c5f5dd6b49d024?r=2ituZftpdG18f1TBADDbCaaEZ9ecYYYm` wasn't working
Probably need to revisit this properly, but for now, grab the `requestPath` that's needed for resolving before escaping the characters.
Tested that `http://localhost:1337/$/search?q=%22\/%3E%3Cimg%20s+src+c=x%20on+onerror+%20=alert(1)+\%3E` would still be blocked.

Fix broken resolves due to escaped characters

---

ui/component/comment/index.js

Closes [#852 Markdown inline images in comments don't work for any channel level](https://github.com/OdyseeTeam/odysee-frontend/issues/852)
The prior commit simplified the props from individual comment fields to just 1 `Comment` object, but there was a typo in the parameter where it should be `channel_url` instead of `author_uri`.

Comments: inline image not working for level4/5 channels

---

ui/component/claimList/view.jsx
ui/component/collectionContentSidebar/view.jsx
ui/component/collectionEdit/view.jsx
ui/page/collection/view.jsx

Code-splits the module into "dnd.js", reducing the ui.js bundle size. This module is only needed when viewing lists.
`ClaimList` can probably improve further by only using the dnd components in "edit" mode.
- The dnd modules are not default exports, so the additional chaining to `React.lazy` was required.
- Experimenting with using an Object to store the import so that a single "prettier-ignore" can be used to make it not wrap.
- The FlowFixMe came from the original code. It is unclear why it is needed to resolve the module, but Haffa mentioned it's something related to .flowconfig.

Lazy-load "Beautiful Drag-N-Drop"

---

ui/scss/component/_header.scss

When attempting to open the navigation on mobile, I often end up revealing the hidden "skip navigation" accessibility button.
This is due to a CSS specificity issue with the new theme.  This PR increases the rule specificity to address the issue.
Before
After

Fix css specificity issue on skip-button.

---

ui/component/livestreamChatLayout/view.jsx

had to change `superChatsByChronologicalOrder` as well so `.sort()` wouldn't affect it

[Fix] Revert tips by amount on hyper chat banner

---

ui/component/uriIndicator/view.jsx

Separated the commit just to make the upcoming diffs easier to read.
- Marked optional props properly.
- Re-ordered to make it easier to differentiate "props used in jsx" vs. "from redux".

UriIndicator: props cleanup, no functional change

---

ui/component/livestreamDateTime/index.js
ui/redux/selectors/livestream.js

- "https://odysee.com/LIVE:6dd" yields "Live 3 months ago" (incorrect)
- "https://odysee.com/@RekietaLaw:a/LIVE:6dd" yields "Live 30 minutes ago" (correct)
Use claim ID instead of uri when searching `activeLivestreams`

Fix livestream date incorrect if short url is used

---

ui/modal/modalAutoGenerateThumbnail/view.jsx
ui/scss/component/_file-render.scss

- Closes #655 
- It also exceeds horizontally on mobile.
Just add css constraints.

Fix video thumbnail selector exceeding the modal size

---

ui/modal/modalError/view.jsx

These are now checked at client side (not CDN side), so not actually an error worth collecting.
Also removed "Uploading the same file from multiple tabs or windows is not allowed." -- no longer exists.

Don't report thumbnail size errors

---

ui/component/fileRenderMobile/index.js
ui/component/fileRenderMobile/view.jsx
ui/page/file/index.js
ui/page/file/view.jsx

The playing URI was being cleared every time we leave the File Page, I believe to prevent the floating from continue playing outside of the File Page.
Close FileRenderMobile by checking playingUri/primaryURI instead.
For the case of livestreams, just display it.

Fix autoplay-next not working on mobile

---

ui/page/home/view.jsx

When loading the homepage, I kept seeing a blank page with footer for a while. Even Google pageSpeed has picked that up:
Closes #572 Slow appearance of tiles
The tiles were originally delayed to prevent the "Upcoming Livestream" section from causing layout shifts.
With the new theme, the footer would cause a visible shift anyway.  Hiding the footer is one solution, but I think not showing anything until the fetch is done is bad because the livestream fetch could stall.
Also, even with the delay, there is some visible shift anyways as shown in the second video:
https://user-images.githubusercontent.com/64950861/154492452-a2336650-d494-4e44-918a-d5ec23c3776c.mp4
https://user-images.githubusercontent.com/64950861/154492464-97edf3ef-b926-4364-a3f6-0e00b5e32dfb.mp4
There is a double-render of …

Fix missing homepage placeholder while waiting for livestream data

---

ui/component/app/index.js
ui/component/app/view.jsx
ui/component/headerProfileMenuButton/index.js
ui/component/headerProfileMenuButton/view.jsx

Closes #535
- Header: Use the "channel list undefined" instead of "active channel url undefined" to determine if the button should be "pending".
- App: restore the use of `activeChannelClaim` instead of `activeChannelId`. In the existing design, the latter is never cleared is some situations, so the former is more accurate as it takes the current channel list into account. We might want to hide (not export) `activeChannelId` to avoid this mis-use again.

Fix header avatar stuck in pending mode when all channels are deleted

---

ui/util/storage.js
web/setup/publish-v2.js

Closes #861 (or at least tries to).
Following advice from `https://github.com/tus/tus-js-client/issues/315#issuecomment-1046821112`, this should eliminate localStorage use from the `tus-js-client` side.

tus: QuotaExceededError

---

static/app-strings.json
ui/redux/actions/publish.js

<sub>Related: #889</sub>
> _I think a big part of the problem is a brave / adblock list that we turned up on. Maybe if we get the failed to fetch, we can mention to try disabling that. It's called "AdGuard Français" , and on Brave, it's on: brave://adblock/_
> _This also prevents thumbs from loading...not sure how we can poke for that..._
Getting 50-100 errors per day, mostly in French. This will be a band-aid until the AdGuard fixes it.  
Not the best solution since it singles out a product (right thing to do?)
Attempted/discarded solutions:
1. Check if all tiles are blank and then only warn the user
- Unfortunately, we are using a `div` rather than `img`, which doesn't have an `onError` to detect it.  Don't feel like adding bloat to `ClaimPreviewTile`
2. Try to detect …

Band-aid: warn about AdGuard blocking our CDN

---

ui/component/claimPreviewSubtitle/view.jsx
ui/component/claimPreviewTile/view.jsx
ui/component/sideNavigation/view.jsx
ui/component/uriIndicator/view.jsx
ui/util/string.js

Closes [#865: Hide @ symbol in areas where channel names are implied](https://github.com/OdyseeTeam/odysee-frontend/issues/865)
Will probably take some time to get used to it for old timers.

ClaimPreview & sidebar: strip '@' since channel is implied

---

ui/component/channelContent/view.jsx
ui/component/claimListDiscover/view.jsx

It's confusing to see blank channel pages due to this setting.
Closes #943

Ignore "search in language" setting in Channel Page

---

flow-typed/Comment.js
static/app-strings.json
ui/component/formFieldDuration/index.js
ui/component/formFieldDuration/view.jsx
ui/constants/modal_types.js
ui/modal/modalBlockChannel/view.jsx
ui/modal/modalMinChannelAge/index.js
ui/modal/modalMinChannelAge/view.jsx
ui/modal/modalRouter/view.jsx
ui/page/settingsCreator/index.js
ui/page/settingsCreator/view.jsx
ui/scss/component/section.scss
ui/util/commentron-error.js

_If approved, route back to me, I'll make the merge (want to check the overlap with SBL is easy to see)._
----
Closes [#834 Add channel age restriction commentron in creator settings ](https://github.com/OdyseeTeam/odysee-frontend/issues/834)
> _Max date it can do is back to : 2022-02-08 - so don't allow a days value that's higher than this. (hint before selection / submission if possible)_
My initial understanding was that it is ok to set beyond this date (e.g. "1 year"), just that any channels created before Feb 7 will still be able to comment even if they are less than a year old.  That feels like ok behavior to me (easier for user to grasp), but turns out setting anything before that date will block all channels.
So, the final commit changed the warning message and also blocks the …

Comment: minimum channel age

---

ui/page/discover/view.jsx
ui/scss/component/_livestream.scss

Closes [#948 wildwest: always show boosting message, move next to category name](https://github.com/OdyseeTeam/odysee-frontend/issues/948)
1. Make "Show less livestreams" share the same space as "Boosted by LBC", instead of only showing either 1.
- It's a bit troublesome to move it next to the filter without tweaking the generic `ClaimListDiscover`, so I think this would be a good compromise.
2. Fix "Show less livestreams" being super tiny in mobile.

WildWest: always show boosting message

---

ui/component/sideNavigation/view.jsx

Issue Number:
Closes #941 
cannot scroll after clicking settings on mobile
can scroll after clicking settings on mobile
when the side navigation is destroyed, it enables scrolling
- [x ] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
</details>

fix mobile scrolling issue

---

ui/component/claimPreviewSubtitle/index.js
ui/component/claimPreviewSubtitle/view.jsx
ui/util/string.js

Closes [#968 Truncate views/subs in other areas](https://github.com/OdyseeTeam/odysee-frontend/issues/968)
- Corrected logic for `minThresholdToApply`, which was ignoring the case of "no threshold needed", causing it to not be truncated in Channel Page. We want to always truncate there due to the smaller cards.
- Missed out handling `ClaimPreviewSubtitle`.

Fix sub/view count not in compact form for some components

---

ui/component/app/view.jsx
ui/component/settingAccount/index.js
ui/component/settingAccountPassword/index.js
ui/component/settingAppearance/index.js
ui/component/settingAutoLaunch/index.js
ui/component/settingContent/index.js
ui/component/settingSystem/index.js
ui/component/settingUnauthenticated/index.js
ui/component/sideNavigation/index.js
ui/component/syncEnableFlow/index.js
ui/component/syncToggle/index.js
ui/component/wunderbarSuggestions/index.js
ui/page/settings/index.js

1. We were manually adding `selectLanguage(state)` as a prop to components used in Settings Page to trigger a render. Flaws:
- Unclear that the unused prop is just to trigger a render.
- Manually adding on a case-by-case basis will break over time, especially when language can now be changed outside of the Settings Page.
2. The translation file fetching is delayed and also takes time, so the GUI will end up having mixed strings on F5, depending on when the fetch completed.
Make the app wrapper have a key that's tied to the language and translation data, so the entire app renders when language changes. Seems like a common design in most apps.
Part of #921 language refresh / selection issues

Render whole app on language change

---

ui/component/commentMenuList/view.jsx

If it's a pinned comment, dismissing it is probably the action that the user is looking for, so doesn't make sense to put at the bottom.

Moved "Dismiss Pin" to the top

---

static/app-strings.json
ui/component/claimListDiscover/view.jsx
ui/page/channelsFollowing/view.jsx
ui/page/discover/livestreamSection.jsx
ui/page/discover/view.jsx
ui/scss/component/_livestream.scss
ui/scss/component/_main.scss

The `useDualLayout` junk is super confusing to maintain and no longer extensible.
At the expense of making the "livestream + regular" list no longer seamlessly continuous when expanded (or when there just a handful of livestreams), use the new `subSection` feature to inject the livestream tiles.  This is far easier to manage and tweak.
Requires more testing.
Part of #728

Swipe livestream + re-implement category livestreams

---

ui/component/claimList/view.jsx
ui/page/channelsFollowingManage/view.jsx
ui/page/search/view.jsx
ui/scss/component/_spinner.scss

Closes #997
Test:  `kp` dev instance
- Preferred the simpler spinner for the Tile Layout than using placeholder tiles.
- The `useLoadingSpinner` is defaulted to `false` for now, so we can leave `ClaimListDiscover` (Category Pages) untouched (less testing).  When refactoring `ClaimListDiscover` in the near future, we can remove the custom placeholder implementation and flip `useLoadingSpinner` to default to true.

ClaimList: add default page-load indicator | Apply on Search and Following-Manage Page

---

ui/component/viewers/videoViewer/view.jsx
ui/effects/use-interval.js

Currently, the position of a video is saved when pausing, seeking, or navigating to a url that is handled by the router. However, if you close the tab or navigate away from the site with a hard link, the play position is lost.
This patch will intermittently save while the video is playing to better prevent losing video progress.  An arbitrary interval of 15 seconds was chose, but this can be adjusted if there is some more appropriate interval.
</details>

When video is playing, save position intermittently

---

ui/component/settingAppearance/view.jsx
ui/component/settingUnauthenticated/view.jsx
ui/redux/actions/settings.js
ui/util/default-languages.js

This is a follow-up for #1016
Still doesn't affect anything at the moment;  just keeping things in sync and reduce work for the next person when we remove homepages from our bundle.

Missed remaining 'homepages' imports

---

ui/component/userSignUp/view.jsx

Closes #1020 strange refresh on signup + youtube sync
It's due to the sync-on-focus.
Only show the spinner for the initial wallet sync. I thought we can do without the spinner for sync completely, but based on the comments below, better to retain that for the initial sync.  I think the rest of the stages don't need to block over a sync call.
```
// Don't claim the reward if sync is enabled until after a sync has been completed successfully
// If we do it before, we could end up trying to sync a wallet with a non-zero balance which will fail to sync
```

SignUp: don't show spinner when in focus (aka GetSync)

---

ui/redux/selectors/search.js

Instead of filtering the entire list for a suitable `nextUri` and then picking the first one, short-circuit when candidate is found.

Recommended: optimize nextUri calculation

---

ui/redux/selectors/search.js

When 'selectRecommendedContentForUri' is filtering results against the blocklist, it relies on claim data which could be unresolved yet. It filters to empty results for this scenario, hence the flashing message.
Just return raw results when claims are not resolved yet, so that the GUI knows it needs to show the placeholders while resolving. After resolving, it'll go through the blocklist filtering again.

Recommended: fix "no results found" flashing after search

---

ui/component/commentsReplies/view.jsx

No replies when:
- haven't fetched yet
- replies blocked/muted
It's being displayed as a dot in these scenarios.

Hide comment thread-line when no replies

---

ui/component/channelContent/view.jsx
ui/component/claimList/view.jsx
ui/component/claimListDiscover/view.jsx
ui/component/claimTilesDiscover/view.jsx
ui/component/recommendedContent/view.jsx
ui/effects/use-last-visible-item.js
ui/page/discover/view.jsx
ui/page/home/view.jsx
ui/page/search/view.jsx
ui/scss/component/_ads.scss
web/component/ads/index.js
web/component/ads/view.jsx

#1018
- <img width="150" alt="image" src="https://user-images.githubusercontent.com/64950861/157102383-d169a2b1-7d97-4b57-9582-c93080a2e068.png">
I kinda like the original's (Recommended's) background color, to differentiate it against the rest.  Can remove if dislike.

Ads cleanup

---

ui/component/channelContent/internal/searchResults.jsx
ui/component/channelContent/view.jsx
ui/component/claimList/view.jsx

Closes [#605 Add pagination support to channel search](https://github.com/OdyseeTeam/odysee-frontend/issues/605)
Test: the usual place.
The previous attempt (https://github.com/OdyseeTeam/odysee-frontend/commit/69de63c436a3511756684de62cfbe49b6950db41) didn't work because the wunderbar is part of the list component, so it is unmounted when we switch between the Normal and Filtered list, causing it to lose focus while typing.
Also, creating another full-blown ClaimList* component was probably redundant (we should be consolidating instead).
ClaimListDiscover recently added a new `subSection`, so we can place the filtered `ClaimList` here without causing the wunderbar to unmount.
Wrapped the "lighthouse search with channel_id" into `searchResults.jsx` for now as a quick and isolated …

Channel Search pagination

---

web/component/browserNotificationSettings/use-browser-notifications.js

useBrowserNotifications: don't set state if already unmounted.

---

static/app-strings.json
ui/component/claimPreviewTile/view.jsx
ui/component/collectionPreviewOverlay/view.jsx
ui/component/collectionPreviewTile/view.jsx
ui/component/collectionsListMine/view.jsx

#950 
> _playlists page - right now we show watch later on top, and if you have stuff here, you have to scroll down to other playlists. Show a selector on top? Whatever other improvements we can make here to improve UX._
Use swipe layout for mobile.

List Page: use swipe layout for mobile

---

ui/component/collectionPreviewOverlay/view.jsx
ui/component/collectionsListMine/view.jsx

Closes [#1071 Limit tiles shown in horizontal mode, option to show all ](https://github.com/OdyseeTeam/odysee-frontend/issues/1071)
- ListOverlay: don't loop through all items if we just want 2. `map` doesn't short-circuit.
- Playlist: reduce show count from 12 to 6 on mobile.

Playlist tile optimizations

---

ui/scss/component/_notification.scss

#950 
> _notifications count clashes with color of the expand button in top right_
----
Before and after:
I think both the button and bubble should retain their colors (used to it + makes sense), so just add a border.

Notification bubble: add border since it's the same color as an active button

---

ui/component/fileValues/view.jsx

Closes [#916 "NaN in Total Staked Amount"](https://github.com/OdyseeTeam/odysee-frontend/issues/916)
Contemplated putting the fallback into `<CreditAmount>` itself, but decided to minimize testing. Not sure if there are clients that would rely on NaN being used.

Handle case of missing `effective_amount`

---

ui/redux/actions/collections.js

We need to store the resolved claims first before marking `COLLECTION_ITEMS_RESOLVE_COMPLETED`, otherwise the GUI still sees undefined claims and tries to resolve again.
798 just accidentally flipped the order due to refactoring, I believe. It's now back to original.

Fix #798: fix action dispatch order in doFetchItemsInCollections

---

ui/component/claimMenuList/index.js
ui/component/claimMenuList/view.jsx
ui/redux/reducers/collections.js
ui/redux/selectors/collections.js

Issue Number: https://github.com/lbryio/lbry-desktop/issues/6205
The last used collection is not displayed in the menu options.
The last used collection is displayed in the menu options:
</details>

6205 remember last used playlist choice odysee

---

ui/component/recommendedPersonal/view.jsx
ui/page/home/view.jsx

- "Following" was showing up in place of "Featured"
- "Following" doesn't appear until livestreams are fetched, causing shifts.
When "Upcoming Livestreams" was implemented, it was trying to retain the original behavior of not showing "Following" title if that was the first in the list.  It's a chicken-and-egg problem, causing extra renders due to the need to check if the other guys was rendered.
With FYP, there are now more combinations to handle, and network calls to wait for.
Just show the title...

Just always show homepage segment titles..

---

ui/modal/modalRouter/view.jsx

This should be equivalent to the previous, just that the promises are stored in an object rather than variable. Benefits:
- Allows a single "prettier-ignore" to bypass the multiline import.
- Slightly less work when adding new modals by not having to create a named variable and handle the switch-case.
The webpack lazy-load syntax is unfortunately verbose, so this is the best I can come up with for now.

Refactor modals; no functional change

---

ui/page/livestreamSetup/view.jsx

If the active channel doesn't have 50 LBC support, we are stuck in the "you can't stream" state. But I have other channels that are eligible.
The "congratulations" string is done in a non-localizable way.  It tries to explain why this channel can stream.
Before I fix the i18n, do we need such a string?  
- Can the subtitle be just "Expand to learn more about setting up a livestream."?  That seems to make more sense given what appears after the expansion.

Go Live: fix missing channel selector

---

flow-typed/notification.js
ui/component/snackBar/view.jsx
ui/scss/component/_snack-bar.scss

- Add close button to allow immediate dismissal.
- Add ability to support sub messages. Will be typically used for error codes, etc.
- Add ability to define 'long' auto-dismiss duration (15s) vs. the default of 5s.  This will be used for semi-important messages.
- I didn't add 'off' because there is a comment saying that this scenario should use the Error Modal instead, so respecting that for now.

Snack: sub-message, close button and duration setting

---

ui/page/signInVerify/view.jsx

Add a persistent (per refreshed session) flag to skip any actions sparked by future renders after it has already been authenticated.
Tested as much as I can, but do try at `kp` in case I broke something.

Fix double `email_user/confirm` due to language render

---

static/app-strings.json
ui/lbry.js
ui/redux/actions/wallet.js
ui/scss/component/_snack-bar.scss

_Putting this up in `kp` for experimenting. Not being able to reproduce the SDK timeout makes it hard to confirm things.
Also, my initial design to make long pending calls visible in the GUI didn't work well, so back to drawing board for now (but that's just an enhancement)._
- Errors like "unexpected token at..." and "failed to fetch" are being logged, rather than the actual call error.
- Attempt to make the logs more helpful, and the error message more meaningful to the user.
- Starting off with `publish` SDK call as an experiment. Can add others if this method works.
Inline with https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#checking_that_the_fetch_was_successful.

Better handling of SDK errors

---

ui/component/claimList/view.jsx

The loop was executed over the entire `tileUris` regardless of whether `excludeUris` existed.

Don't run filters unless necessary

---

ui/page/channelsFollowing/view.jsx

Clean up for 17a9b84d
We are now using `subSection` for livestreams, so no point passing in `prefixUris`, which causes additional processing.
(It wasn't visible because `showNoSourceClaims` was removed, but processing still happens).

Following Page: fix redundant livestream data passed in

---

ui/component/sideNavigation/view.jsx
ui/scss/component/_navigation.scss

Ticket: Closes #1107
Test: `kp`
- Alternative if list is too long (although I'd rather scroll than click-to-expand):  
- Only show both of them in `Expanded` mode, while only showing "Lists" in `Micro` mode

Sidebar shortcuts to built-in lists

---

ui/component/claimList/view.jsx
ui/component/claimListDiscover/view.jsx

Ticket: #946
Test:  the usual dev instance
- Copied the functionality from `ClaimTileDiscover`. Tried to use the same variable names to help the future consolidation work.
- Removed `excludeUris` from `ClaimList` as it makes the caching harder.

Make ClaimListDiscover retain results while searching

---

ui/scss/component/_navigation.scss

"Lists" section is only for authenticated, and causes stray separator line and padding

Sidebar: handle stray separator on empty section

---

ui/component/recommendedPersonal/view.jsx

Since FYP is no longer always at the top, we can't use y=0 anymore.

FYP: fix scroll destination when collapsing

---

ui/redux/actions/subscriptions.js
ui/redux/reducers/subscriptions.js

`Lbry.claim_search` was used, so it doesn't save the resolved results to redux. Use `doClaimSearch`.

Fix sidebar active subs not batch-resolving

---

ui/component/app/index.js
ui/component/app/view.jsx
ui/component/sideNavigation/view.jsx
ui/redux/actions/subscriptions.js

- Remove the odd resolve call that's lingering in `App`. Feels out of place, plus we don't need it now since the "active subs" claim_search would contain resolved results.
- Don't search for active subs if Following count is zero.

More sidebar optimizations

---

ui/effects/use-ad-outbrain.js

They have removed the blocking transparent container when ads are not (or not yet) filled.
Test: `kp` (soon)

Outbrain: remove visibility delay

---

ui/redux/actions/search.js
ui/redux/selectors/user.js

Ticket: #1154
Test:  dev instance (pending build)
There is an intermittent bug with a batched `resolve`, where results are jumbled up. Switch to `claim_search` until that is resolved.

TMP: switch fyp batch-resolve to `claim_search`

---

flow-typed/search.js
ui/component/recommendedPersonal/view.jsx
ui/redux/reducers/search.js
ui/redux/selectors/user.js

This prevents the "no membership" and "no recommendations" message from flashing during load.

FYP: show placeholder tiles when fetching membership or fyp itself.

---

ui/page/home/view.jsx

It causes the "empty homepage" splash to briefly appear.

Homepage: don't wait for prefs if incognito

---

ui/component/webUploadList/internal/web-upload-item.jsx
web/setup/publish-v2.js

There is anecdote that we need to wait up to 2 minutes to preven the locking scenario.
`https://github.com/tus/tusd/pull/667#issuecomment-1079647640`
Instead of multiple retries at short intervals, do a one-time retry after a 2-minute wait. We'll do this until the fix is available in tusd v2.
Not showing that we are retrying in the GUI, since 2 minutes could be long. Just retain the "Uploading..." text.
Added 2 extra seconds for good measure.

tus: retry only after 2-minute wait

---

ui/redux/actions/claims.js
ui/redux/actions/comments.js
ui/redux/actions/search.js

Ticket: #1189
Test: `kp`
There is a bug in a batched `resolve` that returns jumbled data. Temporarily switch to `claim_search` until that is fixed.
- `resolve` will tell us directly that a claim has been removed or filtered, so redux will mark the ID as such. `claim_search` simply returns nothing, so we will still end up with an extra `resolve` for these items when the component tries to display it.
- The new function currently does not handle Collections (i.e. resolving individual items in the Collection) and Reposts. Given that this is temporarily, I'd like to leave `doClaimSearch` as is, instead of trying to replicate what's in `doResolveUris`.
- Since we don't care if the resolve fails (and we weren't doing anything in the `catch` anyways), use `finally` instead.
- There is some DRY …

Batch resolve with claim_search | [Recommended, Comments]

---

ui/component/claimListDiscover/view.jsx

Symptoms match.  Closes [#1216 Active livestream shows in Upcoming + Followed ](https://github.com/OdyseeTeam/odysee-frontend/issues/1216)
My bad.

ClaimListDiscover: fix broken `excludeUris` logic

---

ui/effects/use-ad-outbrain.js

https://discord.com/channels/362322208485277697/363087331475062785/958695965798301716
The variable name changed. This seems to be the only one left.
Perhaps we need a formal method from Outbrain for removal?

Fix outbrain not removed after auth'd

---

ui/component/livestreamLayout/view.jsx
ui/component/livestreamScheduledInfo/view.jsx
ui/page/livestream/view.jsx
ui/util/time.js

Ticket: Closes #1228
- Pass through `getTimeAgoStr` so that the value gets localized.
- Pass the simpler `number` around instead of the `moment` object for better memoization.
Due to how `getTimeAgoStr` is written, we now get to see the time actually counting down, vs "in a few seconds" currently in production.  I think the counting-down behavior was the original intentional, since a 1s timer was used (otherwise, a 1-minute timer could be used) ... or maybe not since streams may not start on the dot.
In either case, it ends with "Starting soon"
_<sub>Left = this PR (updated every second), Right = production</sub>_

Fix livestream countdown i18n

---

flow-typed/homepage.js
ui/component/claimListDiscover/index.js
ui/component/claimListDiscover/view.jsx
ui/component/claimTilesDiscover/index.js
ui/component/claimTilesDiscover/view.jsx
ui/component/sideNavigation/view.jsx
ui/effects/use-resolve-pins.js
ui/page/discover/view.jsx
ui/page/home/view.jsx
ui/util/buildHomepage.js

Dependency: deploy after PR #1205 
Ticket: closes #1189
<strike>This version includes both the `resolve` and `claim_search` version.  Flip between the 2 using `USE_CLAIM_SEARCH`.
:warning: It's currently using `resolve` (despite buggy) because pin URLs are canonical and I don't know how to derive the claim ID from that -- I don't think there an option to pass urls to `claim_search`?</strike>

Batch resolve pin urls

---

flow-typed/content.js
ui/component/socialShare/index.js
ui/component/viewers/videoViewer/index.js
ui/page/file/index.js
ui/page/file/view.jsx
ui/redux/reducers/content.js
ui/redux/selectors/content.js

Maybe related to https://github.com/OdyseeTeam/odysee-frontend/issues/99#issuecomment-1042384649
`fileInfo` does not contain `metadata` anymore -- not sure what happened. With zero duration, `videoPlayedEnoughToResetPosition` was never true.
But the claim usually contains the duration already, so we can use that. There are some audio/video claims that don't, but those are a minority.
First 2 comments are just cleanup work.

Fix failing video position reset

---

flow-typed/homepage.js
ui/effects/use-resolve-pins.js
ui/util/buildHomepage.js

pinnedUrls = resolve
pinnedClaimIds = claim_search
Make `pinnedClaimIds` take precedence for now, since the homepage is defining both to support Android.
For some reason, I previously made `pinnedUrls` the priority, thinking this should be the "correct" one to use when the SDK is fixed.

Swap pinnedUrls vs. pinnedClaimIds precedence

---

.prettierignore
static/app-strings.json
ui/constants/errors.js
ui/redux/actions/publish.js
web/setup/publish.js

Closes #1256
For `notify`, "file is currently locked" and "no such file or directory" is indication that the previous "failed" SDK call actually worked. Tell the user to check the transactions.
This is the band aid until odysee-api/401 is addressed.

Publish: handle failed 'notify' at the server

---

ui/redux/reducers/claims.js

Ticket: #108
Uploads Page uses `claim_list`
Channel Page uses `claim_search`
A second `claim_list` would instantly show updated results, but `claim_search` takes a long while to reflect the deletion.  If both are waiting for a transaction, why did `claim_list` work as expected?
This PR only handles the `claim_list` (Uploads Page).
The `claim_search` version would be troublesome to handle. If a refresh would bring back the results (due to the `claim_search` slow update behavior), we would need to store the deleted claim persistently. Then ...
- Store where? rehydrate?
- When to clear?
- How to make each `ClaimList` filter this out without polluting the code? etc.
...will be messy. Feels easier to "fix" at the `claim_search` to make it update faster like `claim_list`.

Remove abandoned claim from Uploads Page

---

ui/page/fileListPublished/view.jsx
ui/scss/component/_pagination.scss

Closes #1257
The hit-area is just extremely small (just the text) and apparently due to an accessibility issue.
```
https://github.com/AdeleD/react-paginate/issues/125#issuecomment-276625181
```
_<sup>(Not creating a link to avoid unnecessary mention)</sup>_
Changed the css as suggested by the maintainer.
Rave, any potential side effects (e.g. accesibility?).  Seems to work with keyboard.

Fix `Paginate` click area

---

ui/component/claimPreview/view.jsx
ui/component/reportContent/view.jsx
ui/component/settingsRow/view.jsx
ui/component/walletSend/view.jsx
ui/modal/modalBlockChannel/view.jsx
ui/modal/modalHideRecommendation/view.jsx
ui/page/listBlocked/view.jsx
ui/scss/all.scss
ui/scss/common/_non-clickable.scss

- Adding `content__non-clickable` everywhere probably isn't the right way when we move forward to separating `all.scss`.
- Not intuitive -- easier to use if it's an attribute to `ClaimPreview`.
- Consolidate to a re-usable `.non-clickable` class.
- Made Wallet Send search preview non-clickable as a temporary band aid until the channel-finder is consolidated.
- `listBlocked`: something is overriding the pointer, so non-clickable isn't working. Removed for now -- doesn't really matter.

Better non-clickable implementation

---

ui/component/commentsList/view.jsx

In Medium layout, the Expand/Collapse button would still appear even for 0 comments.
Hide the button when comments = 0, but didn't hide the section because the separator line feels useful as a visual guide to mark the sections.
@saltrafael, take a look just in case I broke the logic for other scenarios?

Comments: don't show Expand button if no comments

---

ui/component/commentsList/view.jsx
ui/scss/component/_card.scss
ui/scss/component/_comments.scss

- When collapsing, scroll back to the first comment instead of hanging in the Recommended section.
- Enhancement for 5380bc04: don't show "Collapse/Expanse" if there's only 1 comment. The comment itself is already collapsed to 3 lines, so it won't take up too much height.
- Fix css: recalling what Dan mentioned: if following BEM right (modifiers shouldn't be used standalone), we wouldn't incorrectly use `@extend` in this case and confuse the reader.
- Enlarged the empty spacing to make it symmetrical with the Recommended section below it.

Medium-layout: more "comment section collapse" fixes

---

ui/page/home/view.jsx

Closes #1307 newly added categories aren't adding to existing customized homepage
In Customize, new categories were appended at the bottom, but forgot to repeat the behavior on the actual homepage itself.
`kp`

Fix new categories not showing until Customize is opened

---

ui/redux/actions/comments.js
ui/redux/reducers/comments.js

Due to "Own Comments" being implemented the same way as "Discussion Page", the comment lookup did not work for the abandoning case.
Just skip the local cleanup of `byId` -- it doesn't matter, as the GUI uses `selectCommentsForUri` to grab the per-channel comments, so it would still disappear in the GUI immediately.
`kp` (after build is done)

OwnComment Page: deleting comment shows failure despite successful 

---

ui/redux/actions/app.js

Potentially closes #1319
- `persistor.purge` returns a promise, we should wait for the resolved results before reloading, instead of just adding an arbitrary `setTimeout`.
- Perhaps the `setTimeout` method is to ignore a super-long or hanged purge (not sure), but it wouldn't be right since it would end up in a limbo state.
- Log errors to get clues for future.
- Reduced code by moving the reload to `finally`.

Fix signout sequence not cleaning up correctly

---

static/app-strings.json
ui/component/claimTilesDiscover/view.jsx

Just like `ClaimListDiscover`, stop `claim_search`-ing if the result is a failure (null).
Leaving the placeholder tiles as is for now. Can show the timed out message like `ClaimListDiscover` -- just toggle `SHOW_TIMEOUT_MSG`.
Closes #1320

ClaimTilesDiscover: stop repeating claim_search on failure

---

web/src/html.js

The changes to escape characters caused `ctx.query` to be nulled.
As a quick fix, stash that value early on.
Results (back to working state):
Not sure if need to escape/un-escape the query string for this case.

Fix broken Search Page OG

---

ui/component/claimPreview/index.js
ui/component/claimPreview/view.jsx
ui/component/claimPreviewTile/index.js
ui/component/claimPreviewTile/view.jsx
ui/redux/reducers/livestream.js

1. Update `viewersById` after fetching active livestreams
- `viewersById` is usually updated by websocket, but since we have the latest data, might as well use it.
2. Livestream tile/list: show viewer count if data is available
- As of this commit, only the Channel Page is fetching the data through the new API, which has the viewer count correctly populated.
- For both "0" and "undefined", continue to show as "LIVE".
Test: `kp`
Ticket: #16 
- Thumbnail flickers when when there is an update.  Probably need to memo the sibling component somebody.

Livestream tile/list: show viewer count if data is available

---

ui/redux/actions/settings.js
ui/redux/selectors/settings.js
web/component/meme.jsx
web/src/getHomepageJSON.js
web/src/homepageApi.js
web/src/html.js
web/src/routes.js

Item 2 of [#1318](https://github.com/OdyseeTeam/odysee-homepages/issues/1318)
- Had to create v2 as there is no backward-compatible location in the v1 json to place it.
- v2 allows any future expansion beyond 'categories' and 'meme'.
- One-meme-per-homepage is also supported, but not enabled for now.
Format:

Homepage API v2 -- includes 'meme'

---

static/app-strings.json
ui/component/publishName/index.js
ui/component/publishName/name-help-text.jsx
ui/component/publishName/view.jsx
ui/redux/actions/claims.js
ui/redux/selectors/publish.js

??
https://odysee-workspace.slack.com/archives/D02EKAWJ8EB/p1650218769018309?thread_ts=1649984883.723529&cid=D02EKAWJ8EB
`kp`
- Use "`claim_search` + all own channel IDs" instead of `claim_list` to retrieve all all own claims with the same name (case-insensitive).
- Caveat: annonymous claims will be excluded.
- When a clash occurs, there is a possibility that we have multiple existing entries (e.g. "xxX", "xXx"). Since we don't know which one is best to fall back, I removed the "edit" button for this case and replaced with a simpler text
- If not mistaken, the rest of the code still needs `selectMyClaimForUri` to be case-sensitive, so augment the selector to support both through an optional parameter.

doCheckPublishNameAvailability: case-insensitive version

---

ui/page/embedWrapper/view.jsx

Closes #1345
The refactor in  [04c5ac46](https://github.com/OdyseeTeam/odysee-frontend/commit/04c5ac460bd3c3e391b26d32f61a3bc9fa7eac4c#diff-7cad9126bc5596b95beaee0e28af64ea74e73ab38d583fbdb3907c0abc2e0856R158) broke the logic, because `!hasCost` would incorrectly include an undefined `costInfo` (haven't fetched) as free content.

Fix hidden purchases through embeds

---

ui/page/home/view.jsx

Closes #1074 (band-aid)
In mobile, the second livestream tile in Following gets missing because of the Ad being in 'replace' mode.
Switch from 'replace' to 'insert' mode in Mobile layout.
If missing (replaced) tiles is a problem, the true fix would be to always use 'insert' mode, and either live with the uneven tiles, or wait for our design master's solution.

Ad: change to 'insert' mode in Mobile layout.

---

ui/component/claimList/view.jsx
ui/component/claimPreviewTile/view.jsx
ui/component/collectionsListMine/view.jsx

Closes #1308, Closes #1363
Ported the `isAbandoned` handling from the list-layout to the tile-layout (yet another grumble on why tile vs. list is not just a css difference but an entire different component).
Because "ClaimList + tileLayout" was showing abandoned claims by default all this while, searched around to see if it was still needed. I think only `collectionsListMine` would require that (or maybe not, can remove later).

ClaimPreviewTiles: hide abandoned tiles by default

---

ui/component/livestreamLink/view.jsx

| Ticket | Closes [#1358 - flicker on livestream tile when viewers updates](https://github.com/OdyseeTeam/odysee-frontend/issues/1358) |
| ------------- | ------------- |
| Test    | `inf` |
Defining the component that way results in unique Card wrapper on each resolve, so everything gets torn down and re-mounted, causing the flicker.
There is a css side-effect with the fix though: the tags changed from red to black. But tags are inconsistent through the app ... sometimes black, sometimes red (I think it should always be red + smaller font from the body).

LivestreamLink: fix flicker when a child updates

---

ui/page/discover/view.jsx

- I got the previous logic completely wrong.
- Wild West's release time now comes from the homepage definition, but since the definition currently does not support "start of week", continue to hardcode the customization here.
- This logic also fixes the release_time for Tags.

Discover: fix release_time for Tag and Wild West

---

ui/component/claimListDiscover/view.jsx
ui/page/discover/livestreamSection.jsx
ui/util/default-languages.js

|  |  |
| --- | --- |
| Test: | `inf` |
| Ticket: | Part of #1368 (_"if user overrides the category homepage language with a different language setting + use 'search this language' option, use that instead. It's not typical this will happen, but probably expected."_)| |
- Refactored to move more logic into `resolveLangForClaimSearch`
- Replaced the ternary version to make it more readable (hopefully).
- Inverted the language filter precedence by honoring the user's setting first.
- Note: for both User and Category filters, URLSearchParams will always take precedence.

SearchInLanguage: honor user's setting before category's setting.

---

ui/page/discover/view.jsx

Ribbon:
- hide: category pages, except Wild West
- show: Following, Tags, Wild West

Fix missing repost ribbon for Tags

---

.flowconfig
ui/component/claimListHeader/view.jsx
ui/contexts/claimSearchFilterContext.jsx
ui/page/discover/view.jsx

Closes #1368
> can we remove the repost filter option on categories outside of wildwest/following?
Using `context` to:
- reduce the amount of files that need to change.
- avoid prop-drilling.
- allow the ability to dynamically define the Filter's allowed values in a contained manner.
Clients that don't need customization simply does not need to wrap their component with the context.
The context only contains Content Type for now, but can include anything that future clients need to dynamically adjust.

Category: Hide "Repost" from ContentType filter, except for WildWest

---

ui/component/fileRenderFloating/view.jsx

this is mainly a fix for development, since it's really annoying when the page hot-reloads and the video disappears, maybe there are edge cases this could fix also, but easy to revert if breaks anything else
to test simply change anything like type `console.log(1)` anywhere in the code while a video is playing

Fix broken player rect state when app is updated and resize failed

---

ui/component/claimListDiscover/view.jsx
ui/page/discover/view.jsx

Test: `inf`
Closes #1378
> "Content Type: Any" uses `claim_type: [streams, reposts, channels]`,  with `stream_types: ["video", "audio"]`, so channels aren't returned, and not any types of streams either.  Probably shouldn't have `stream_type` filter there.
(This also happens in categories, but maybe wanted in there?)
This one is probably a legacy issue since Odysee.
Due to this line in `ClaimListDiscover`:
`defaultStreamType = SIMPLE_SITE ? [CS.FILE_VIDEO, CS.FILE_AUDIO] : undefined, // add param for DEFAULT_STREAM_TYPE`
Wanted to check if this fallback was meant for Categories only or any list, but the git history is not preserved because Odysee was a squashed single-commit back in the `SIMPLE_SITE` days.
Will assume it was meant for Category Page only and moved that line from the …

Fix 'content=any' not producing Channels in result

---

web/src/tempfile.js

Related: #1386
The code was caching the first result and returning that.
We would expand the cache for multiple files, that that also require checking if the file has changed, so just read the content every time -- I think the file is small enough?

Fix tempFileMiddleware serving a cached .well-known file

---

ui/component/common/paginate.jsx

Issue Number:https://github.com/lbryio/lbry-desktop/issues/1280
FormField not resetting value after calling new page
Sets FormField to null after page change
A simple setTextValue(""); on line 49 of the handlePaginateKeyUp function in the paginate.jsx, dealing with local state of this component.
- [ x] Bugfix: I feel a text box not set back to null is a bug
- [ x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [ x] I have checked that this PR does not introduce a breaking change
- [ x] This PR introduces breaking changes and I have provided a detailed explanation below
</details>

added setTextValue to handlePaginateKeyUp function

---

static/app-strings.json
ui/component/router/view.jsx
ui/constants/pageTitles.js
ui/redux/actions/settings.js

Completely remove any need to update things on our side when a Category is added or changed.
<strike>Will need to inform homepage owners to directly translate the `label` field, so we don't need to use our translation system.  But can push first (doesn't impact existing translations).</strike> _Update:_ scratch that ... Chinese homepage is shared between 2 languages, and translating that way wouldn't work.  Continue with existing method, I guess.

Auto-populate category page titles

---

ui/util/livestream.js

I assume `viewCount` always exists;  if not, probably need to handle.

Sort livestreams per viewCount, descending

---

static/app-strings.json
ui/redux/actions/comments.js
ui/util/toast-wrappers.js

Test:  `inf`
Ticket:  Part of #1705
<strike>## Concerns</strike>
<strike>In order to know if we have already reacted from another comment, we need to fetch reactions for all of our channels.  This increases the `reaction.List` call by N_OWN_CHANNELS per comment page.
If this is fine, then great.  Else, we can try to only fetch-all when a reaction is being done, rather than when a reaction count is normally being fetched.</strike>
- This PR doesn't cover comments (but the test instance covers both)

Allow only 1 comment reaction per account

---

ui/constants/errors.js
ui/lbry.js
ui/util/fetch.js
web/setup/publish-v1.js

Previously, we tried to inform the user that when an SDK call such as `support_create` and `publish` fails (specifically, timed out), the operation could be successful -- please check the transactions later.
However, we only covered the case of `fetch` actually getting a response that indicated a timeout, e.g. "status = 524". For our SDK case, the timeout scenario is an error that goes into the `catch` block. In the `catch` block, we can't differentiate whether it is a timeout because it only returns a generic "failed to fetch" message.
Since `fetch` does not support a timeout value, the usual solution is to wrap it with a `setTimeout`. This already exists in our code as `fetchWithTimeout` (yay).
By setting a timeout that is lower than the browser's default and also lower than the SDK …

Add a timeout on SDK calls to allow specific error messages.

---

flow-typed/livestream.js
ui/redux/actions/livestream.js
ui/redux/reducers/livestream.js

We were already limiting the call to once-per-5-minutes (for the successful case), so just need to put failure cases into the mix.
Retry 3 times before stopping.
Test:  `inf` (when build is done)

Limit livestream fetches when failed

---

ui/component/yrblWalletEmpty/index.js
ui/component/yrblWalletEmpty/view.jsx
ui/page/wallet/view.jsx

Closes #799
`TxoList` is not shown when balance is zero. A zero balance doesn't always mean zero transactions.
Just like in other components, don't make `YrblWalletEmpty` a mutually-exclusive thing.

Fix missing txoList when balance is 0

---

ui/component/snackBar/index.js
ui/component/snackBar/view.jsx
ui/redux/reducers/notifications.js
ui/redux/selectors/notifications.js
ui/scss/component/_snack-bar.scss

Part of #1412
New toasts/warnings could be buried by existing ones, or unclear that there is a stack of them queued up.
This is getting more apparent with the commenting restrictions, as we need to inform the user immediately after a button is pressed.
- Reverse the toast display order to show the latest first
- Add GUI to indicate the stacking scenario.
@saltrafael, I think the Wallet Send is the only non-toast GUI that need to look at `selectToast`.  I think the change in behavior on the selector shouldn't affect the component, but can you help double confirm?

Stacking toasts

---

ui/page/home/index.js
ui/page/home/view.jsx
ui/redux/actions/settings.js
ui/redux/selectors/settings.js
web/component/meme.jsx
web/src/getHomepageJSON.js

Closes #1446
- Requires an accompanying commit in `odysee-frontend`.
- The change assumes that the `odysee-frontend` is the only project that uses these files directly, i.e. other clients all use the API instead.
Merging strategy:
1. Homepage:  Set the script to point to `homepage.memes` branch.
2. Push this PR.
3. Let it build ...
4. Restore script back to `master` for homepages.
5. Push the homepage PR.
6. Let it build ...

Support homepage-specific memes

---

web/src/html.js

A content page contained `"` as a tag, and that caused the meta generator to produce a malformed page.
`@Ads:e`

Meta: escape chars when generating `keywords` from `tags`

---

ui/page/discover/view.jsx

Closes [#1484 "How fresh" selector on category pages, when sorting by "Top", does nothing](https://github.com/OdyseeTeam/odysee-frontend/issues/1484)
Only pass the prop when there 'freshness' filter is not active.

Fix 'freshness' filter not working in Category Pages

---

extras/recsys/recsys.js
ui/component/viewers/videoViewer/internal/plugins/videojs-recsys/plugin.js
ui/redux/selectors/claims.js
ui/redux/selectors/subscriptions.js

Closes #1317
Behavior is as described in the ticket (thanks, jbn for the details :+1:)
Depending on the outcome of https://odysee-workspace.slack.com/archives/C02FQBM00Q0/p1652175686742469, some rework might be needed.  This version follows suggestion (a) in the chat, so the initial frame and any subsequent seeked frames all count as 1s.

Recsys: send `totalPlayingTime` instead of `events`

---

.env.defaults
config.js
ui/effects/use-get-thumbnail.js
ui/util/web.js
web/src/fetchStreamUrl.js
web/src/html.js
web/src/routes.js
web/src/rss.js

- There are 2 versions of `Lbry` and `buildURI` -- the app and web-server version.  There are subtle differences between them, and for the app case, importing the web-server version results in a query into an invalid URL.
- Function was changed from returning a string to returning a promise.
- The app only needs it in `use-get-thumbnail`.  Use the existing `doFileGet` framework, which indirectly caches results.
- Since `generateStreamUrl` (renamed to `fetchStreamUrl` for clarity) is currently only needed for web-server, I moved it into the `web` folder to avoid misuse in app.
- Await on the promise. Unfortunately, this also means the entire chain of function calls need to be adjusted to be `async`.

Use `get` instead of generating the stream url

---

ui/lbry.js
web/lbry.js

No analytics for the server side

Temporarily prevent invalid `get` calls until we figure it out

---

static/app-strings.json
ui/effects/use-claimList-infinite-scroll.js
ui/page/channelsFollowingManage/view.jsx
ui/page/watchHistory/index.js
ui/page/watchHistory/view.jsx
ui/redux/selectors/content.js

Test:  `kp`
Doing individual resolves is taxing.
Add infinite scroll and batch-resolve each page. Factored out the method used in Manage Following.

Watch History: infinite scroll and batch-resolve

---

ui/component/fileRenderFloating/view.jsx
ui/component/swipeableDrawer/view.jsx
ui/scss/component/_livestream-chat.scss
ui/scss/component/_main.scss

Issue Number: closes #1120 
- Allows mobile drawer to be resized (fullscreen)
- (very similar to yt app comment, description etc drawers)
- Allows desktop chat to be resized horizontally (wider on big screens)
- Also fix chat drawers being open when switching pages

Allow chat to be resized

---

ui/component/claimList/view.jsx

_Found this while trying to rebase adnim, where Category Page inject ads every other page.  It's the same problem as the PublishFile.  Gotta be mindful of this in future reviews._
`tileUris` is being used as an effect dependency, but it gets re-created on every render (same content, but different reference), so the `setUriBuffer` effect ended up in a loop.

ClaimList: fix infinite effect loop

---

ui/component/channelContent/index.js
ui/component/channelContent/view.jsx
ui/component/recommendedContent/view.jsx
ui/page/discover/index.js
ui/page/discover/view.jsx
ui/page/home/index.js
ui/page/home/view.jsx
web/component/ads/index.js
web/component/ads/view.jsx

@toshokanneko, some cleanup ideas while trying to merge into adnim.
I know you're working on some fixes too, so didn't want to push yet.  Didn't fully test yet.  But maybe you can cherry-pick this if you want.
We can't encapsulate `!hasPremiumPlus` also, right?  I think you need the injected item to be mounted?

Move `PremiumPlusTile` into `Ads`

---

ui/lbry.js
web/lbry.js

This reverts commit f6f15531d48991b554cd65a0ec6759923b9e264f.
The root-cause was known (8dd0982f), and I don't think it worked because:
1. The issue happened at the web side which didn't have logging.
2. The `[object Promise]` came after the `get`, not before.

Revert "Temporarily prevent invalid `get` calls until we figure it out"

---

ui/page/embedWrapper/index.js
ui/page/show/index.js
ui/redux/selectors/claims.js

`ByUri` - returns the storage variable (array or object).  Usually through `selectBlahByUri(state)`
`ForUri` - returns the specific entry in the storage variable.  Usually through `selectBlahForUri(state, uri)`

Fix selector naming convention

---

ui/component/publishFile/index.js
ui/component/publishFile/view.jsx

Per doc:
> _A React component should not cause side effects in other components during rendering._
----
- I didn't fully test this as I don't have a high bit-rate file, but the errors are no longer present.
- Should try with bad file, and ensure message goes away when selecting a good file.
- There are a few more two-way binding state ... those might cause issues too, but this one is the obvious low-hanging fruit

PublishFile: fix render function violation

---

ui/scss/component/_ads.scss
ui/scss/component/_claim-list.scss
web/middleware/cache-control.js

1. Hardcoding breaks any image changes done on dev instances or locally.
2. The relative path used is bad, and there are few more instances of it. But continue as is for now, will file a ticket to fix all of them.
3. Fix caching.

astronaut_n_friends.png: fix src and caching

---

ui/component/claimPreview/view.jsx
ui/component/claimPreviewTile/view.jsx

_See commit messages_
----
@toshokanneko, can you help to review the second commit just in case I messed up?  Behavioral differences:
- `onHidden` would now also be called if the list wants to exclude livestreams (although I think only FYP is using `onHidden` at the moment, and FYP doesn't come with livestreams)

ClaimPreviewTile: fix render violations and `onHidden` logic

---

ui/component/comment/index.js
ui/component/comment/view.jsx

@saltrafael, safe?
This is just removing one prop to calculate in `select`, and skip the need to pass to `ChannelThumbnail :: obscure`

Comment: remove the muted prop

---

ui/component/viewers/videoViewer/internal/videojs-events.jsx
ui/component/viewers/videoViewer/internal/videojs.jsx
ui/component/viewers/videoViewer/view.jsx
ui/page/file/view.jsx

Issue Number: closes #1470 
- Let the position be cleared at the end like regular videos and can come back to it

Remove clearPosition functions for playlists

---

package.json
yarn.lock

This includes the desired latest `http-streaming`, so no more need to do custom `resolutions`.
Tested with a day's usage of random features (livestreams, mobile, etc.). But second set of testers is always good.
Test:  `INF`

Upgrade video.js to 7.19.2

---

ui/component/wunderbarSuggestion/index.js
ui/component/wunderbarSuggestion/view.jsx

This list is not using ClaimPreview or ClaimPreviewTile, so the filtering was missed.

Fix geoblocked items appearing in wunderbar suggestion popup

---

ui/component/channelContent/view.jsx
ui/component/fileTitleSection/view.jsx
ui/component/geoRestictionInfo/index.js
ui/component/geoRestictionInfo/style.scss
ui/component/geoRestictionInfo/view.jsx
ui/component/postViewer/view.jsx

Closes #1100
Contents aren't block if you own them, but need to tell creator that is it blocked for others.
- Show a banner on Content and Channel Page for this scenario.
- Hover tooltip is available for the full text. For mobile, tapping it reveals the message.
Note that this only applies to the locale from where the creator is viewing it from. We can ignore locale, but would then need to display _all_ geo-restrictions related to the content in a list.

Geoblock: show warning for own content

---

ui/redux/reducers/claims.js

- Closes [#1535 bunch of channels (from featured?) resolved on page load](https://github.com/OdyseeTeam/odysee-frontend/issues/1535)
- It was due to the use of reposts in the Category. As we did not store the repost's original channel claim, `ChannelThumbnail` couldn't find the author and requested a separate `resolve`.
Store the repost's original channel claim as well.

Resolve: store repost's original channel too

---

ui/util/geoRestriction.js

My bad, added an unnecessary check in the previous change that shorted the logic too early.
Accessing an object using 'null' or 'undefined' as the key won't cause trouble (and is expected in this case), so just suppress flow instead of fixing it using
`channelId && geoBlockLists.livestreams[channelId]`
https://github.com/OdyseeTeam/odysee-frontend/issues/1100#issuecomment-1138928520

Geoblock: fix anonymous claims passing through

---

ui/component/router/view.jsx

Prevents the router switch from being rendered before all the data is available.

Get rid of 'content not found' page in categories

---

ui/component/viewers/videoViewer/internal/videojs.jsx
ui/scss/component/_videojs.scss

Currently, iOS is showing an errant CC button to the left of the play button due to a misreading of embedded subtitles, however on a video with actual subtitles the CC button doesn't show up, therefore subtitles are turned off for iOS
Meanwhile on other platforms, the CC button is in the wrong position
This moves the CC button to a better position (based the choice off YouTube)
The upload with a CC button is at: https://odysee.com/DIRECTONOCTURNODELQUINTACOLUMNA-PROGRAMA301-:7169b6a98141f08018886a136d79b183ca036625

Don't show subs button for iOS and show in correct position for the rest of platforms

---

ui/component/router/view.jsx
ui/page/show/index.js
ui/page/show/view.jsx

This is a follow up for 2b60fe95
- Not every page needs the Category data, so only block for Category pages.
- `categoryPages.length` was rendered as a number while blocking for the fetch.
It's a chicken-and-egg thing because we don't know what the category path is, but fortunately categories and internal pages start with `/$/`, so we can make a reliable guess. The other internal pages would have matched the defined routes and would not reach this function.

Don't block entire router while fetching Categories

---

ui/component/app/view.jsx
web/component/adsSticky/index.js
web/component/adsSticky/view.jsx

Test: `kp` 
----
https://odysee-workspace.slack.com/archives/C02G20Z2AEL/p1654171314724029?thread_ts=1654089384.715699&cid=C02G20Z2AEL
Content: not showing ads for signed-in users because it interferes with commenting.
Channel: same behavior as Categories (i.e. show is not Premium+).

Show Sticky in Content and Channel Page for incognito

---

yarn.lock

This diff came up when building. Probably missed from the eslint update PR.

Missing yarn.lock commit

---

web/src/getHomepageJSON.js
web/src/homepageApi.js

Formatting changes for Roku to parse the data properly.
Closes https://github.com/OdyseeTeam/odysee-homepages/issues/1570
Wasn't sure whether to use something generic like `format=cat_array`, but ended up with `format=roku`.
1. https://odysee.com/$/api/content/v2/get
2. https://kp.odysee.com/$/api/content/v2/get
3. https://kp.odysee.com/$/api/content/v2/get?format=roku
1 should equal 2, and 3 is the new format.

Homepage API: add `?format=roku` support

---

ui/component/viewers/videoViewer/internal/videojs-events.jsx

The exception thrown was causing the rest of `onInitPlay` to not run, e.g. "Tap to mute" not appearing, etc.
Closes #1663

MediaSession: handle null thumbnail

---

web/src/html.js
web/src/metadata/googleVideo.js

The `contentUrl` was a redirect -- it needs to be directly pointing to the file itself instead.
1. Copied the way the url is generated from the RSS code.
2. Incrementally added more metadata for SEO.
- <img width="200" alt="image" src="https://user-images.githubusercontent.com/64950861/172863578-87feff68-1374-4a39-a1f1-0ed82307f117.png">
1. I think the video url needs to be crawlable.  Is it?  I assume we blocked all crawlers for `player.odycdn`
- <img width="437" alt="image" src="https://user-images.githubusercontent.com/64950861/172862804-0911e5fb-9e70-4ed2-9b3a-152e81fee280.png">
- <sub>https://developers.google.com/search/docs/advanced/crawling/verifying-googlebot</sub>
2. This does incur an additional fetch for the streamURL.  Hopefully it doesn't impact page load.  I didn't notice a …

GoogleVideo: fix `contentUrl` and add more metadata

---

web/src/routes.js

- When `/$/download/:claimname/:claimId` is invalid<sup>1</sup>, it results in a bad loop that keeps requesting the same thing. Eventually it stops, though.
- When `/$/stream/:claimname/:claimId` is invalid, it results in a 302 page that simply says `Redirecting to .`, and is increasing in count as reported in search console.
Return a 404 not found for these.
I'm guessing prior to `get`, it just returns whatever the generated URL's server error was?
----
_<sup>1</sup> This includes deleted claims ... when deleted, `get` returns nothing._

Handle invalid `/$/download` and `/$/stream` with a 404

---

ui/component/viewers/videoViewer/internal/lbry-playback-rate.js
ui/component/viewers/videoViewer/internal/videojs.jsx
ui/scss/component/_videojs.scss

- Part of #1637 - invokes the popup menu when clicked.
- This also makes the button consistent with other `MenuButton`s, i.e. to invoke a menu popup when clicked instead of hovered.
- Ref: `https://github.com/videojs/video.js/issues/3394#issuecomment-230793773`
- Most of the code is just 1-liner tweaks from the original, instead of having to fork it.  Will consider creating a PR to videojs so we don't need to maintain this override.
----
```
if (btn && btn.buttonPressed_ && relatedTarget !== btn.el().firstChild) {
btn.unpressButton();
}
```

Playback-rate: fix popup behavior

---

ui/component/channelThumbnail/view.jsx

Closes #1684
While Lighthouse suggests adding `alt`, I think it's just a recommendation that does not affect the Core Vitals score directly -- the large css plays a bigger role at the moment.
Also, we could consider these as more "decorative" than "functional", because the channel name string is the primary link to enter a channel page.

ChannelThumbnail: remove alt text to prevent from being used as search result

---

ui/component/viewers/videoViewer/internal/chromecast.js
ui/component/viewers/videoViewer/internal/videojs.jsx

Fixed the title that did not update from stale closure because we no longer re-initialize the plugin, plus frozen controls.
We still continue to sever the connection when switching sources for now (although videojs is now single-instance) due to a problem that stops the next remote playback after 5-10 seconds. Unclear whether it is the plugin problem or due to our changes (although I don't see this issue in their repo).
----
_We can ship this first while the weird issue is being figured out. Better than not working, plus it's equivalent to what we had before_

Fix chromecast title handling

---

ui/component/app/view.jsx
web/component/adsBanner/view.jsx
web/component/adsSticky/view.jsx

I've tested the various scenarios (Premium+, Incognito, mobile, etc.), but do give it a shot given my bad track record in this area.
Sorry, no test instance since I'm preserving the load-order problem for Adnimation.
- Fixes the issue of In-content not loading when going from Homepage -> Category -> Homepage the first time.
- This was due to the shared `OBR` instance between the Sticky and In-content.
- No longer need to re-load the scripts on every page navigation -- this should improve user performance and reduce DOM clutter.
- Enable sticky for homepage.
- Temporarily address the script load-order problem by moving components around. Not ideal, but works for now.

Outbrain fixes and updates

---

ui/component/fileRenderInitiator/view.jsx
ui/effects/use-get-poster.js
ui/page/embedWrapper/view.jsx

Closes [#1526: strange thumbnail size requested on mobile layout (pc only?)](https://github.com/OdyseeTeam/odysee-frontend/issues/1526)
It was trying to fetch based on the exact size of the video container, which would satisfy Core Vitals (in an overkill way), but would bring several issues:
- server-side caching would not work since everyone's window size is different in a responsive layout design.
- the additional 200ms wait for container size to settle down is not good (hardcoded wait time).
- the code did not account for device-pixel-ratio, so it's quite a wasted effort.
The embed wrapper was not going through the CDN either as a null `containerRef` was passed in.
Aside:  In the past, we used to take the same image url as the tiles, so the video poster would appear immediately due to …

Change poster-fetch implementation

---

ui/component/headerMenuButtons/view.jsx

Bring back the settings link in guest mode so users can change the language without logging in.

Add settings page button to header in guest mode

---

web/component/ads/view.jsx

- I previously hardcoded both IDs since the script was not looking the right one at one point, but I guess that was unnecessary.
- I don't think it causes any problems, because I'm still just loading 1 script (no double video, just 2 divs for them to choose).
- Note that we are still using the `filepage` script since the `homepage` one is (still) not working.

Undo the hardcoded ad div id

---

ui/component/viewers/videoViewer/internal/videojs.jsx

`playsinline` attribute isn't being persisted after previous bugfix, this fixes it on iOS

Fix playsinline bug on iOS

---

ui/redux/selectors/search.js
ui/util/search.js

Bring back the refactoring commits from the reverted #1616.
No functional change -- equivalent code.
Needed to do the same thing for the uuid stuff.

DRY: recommended selectors

---

ui/redux/actions/claims.js

- http://localhost:9090/@AlphaNerd:8/the-crypto-market-dumps-again-(xmr-is-on:6
- One of the comments contain a link to a playlist of 13 items, which results in 3 additional `claim_searches` of 5 each
In `doResolveUri`, if the `uri` is a collection, it will attempt to fetch all items in the collection.
Can't think of any special reason to keep the page-size small, and not seeing any notes in the commits either, so bumping it to 50.

Change collection item fetch-page from 5 to 50

---

ui/component/header/view.jsx
ui/component/page/view.jsx
ui/page/reportContent/view.jsx

Closes #1709 - If you sign in while reporting, you end up in the homepage
The other option is to just make `<Header>` always redirect back to where it came from using the full path. But existing code elsewhere seem to always trim off any params (e.g. `location.search`, `location.hash`) when doing redirects.
So, ended up making it generic and let the caller decide where to redirect (and with what params).

ReportContent: redirect back after logging in

---

extras/recsys/recsys.js

Ticket: #1745
The search result (and the uuid) won't be ready when a recommendation is clicked, but a stub recsyst entry is created at this point. In the past, the uuid was randomly generated, so it didn't matter.
Ensure the uuid field is filled when the recommendations are finally loaded.

Recsys: fix missing uuid

---

ui/component/viewers/videoViewer/internal/videojs.jsx

Addresses issue: https://github.com/OdyseeTeam/odysee-frontend/issues/1716
Hypothesizing that the state occurs when both calls to `play()` fail (based on my own testing of how to replicate the state), this will catch the second `play` error and show the overlay as if the video has been paused
Hopefully a user who is experiencing this can test it first before a merge to confirm it fixes their issue

Show controls if both calls to play() fail

---

ui/component/fileThumbnail/index.js
ui/component/fileThumbnail/view.jsx
ui/redux/selectors/claims.js

Note: This goes into the playlist PR, not `master`.  Not pushing directly in case there are rebase problems, or if there is conflict in meaning.
Seeing a bunch of bad resolve calls.
- FileThumbnail can work without `uri`, so we still need to check for `uri` before making the fetch.
- Given that `hasResolvedClaim` now incorporates `uri` into the logic (differentiating between unresolved vs. not needed), use `=== false` instead for clarity.
- The extra `&& uri` is to keep lint happy.

Fix a bunch of `lbry://undefined` resolves

---

.env.defaults

Currently `LBRY_API_URL` is not set in `.env.defaults` but rather uses the default value in `Lbryio`.

Add lbry_api_url to env defaults

---

web/setup/publish-v2.js

- Previously, we tried to solve the "file locked" problem by only making one retry after a super long delay. This was from an anecdote that it's more likely to lock up if the delay was short.
- This didn't help at all for our case, and Andrey has made some locking mechanism changes in the backend.
- The reduced number of retries probably increased the number of "failed to upload chunk" errors (not sure), which is supposedly a normal occurrence and we're expected to keep retrying.
Restoring the retry behavior and continue to monitor...

Publish: restore the multiple retries

---

ui/component/viewers/videoViewer/internal/videojs.jsx
ui/component/viewers/videoViewer/view.jsx
ui/redux/selectors/claims.js

It seems like the existing `embedded` needs to specifically mean `/$/embed` (external from odysee.com), so had to add another variable.

Recsys: add `isEmbed` to videos in Markdown (posts, comments)

---

ui/page/fileListPublished/view.jsx

This reverts commit 1dccc1ac644ee506239ffc4513de4c8f29770653.
- Closes #1770
- Re-opens #1515
1515 is just an annoyance, while the current issue is a non-functional page, so reverting for now and revisit later.

Revert "Fix uploads page cleared/reloaded on each navigation"

---

ui/component/common/markdown-preview.jsx

Depending on what the markdown content was, React crashes when unmounting the component if Google Translate is active.
It seems like the content is too dynamic to apply the same workaround used in 1772 for FileReactions (someone else can take a stab).
Until we have a better solution, just make the markdown component (posts, comments, file description, etc.) not participate in Chrome-level translations. It's not a good solution from a user standpoint, but it at least it doesn't crash.

Workaround for markdown crash with Google Translate

---

ui/component/publishReleaseDate/index.js
ui/component/publishReleaseDate/view.jsx

Closes #1738
You can use `new Date(store.getState().publish.releaseTimeEdited * 1000)` to test along, with the following to keep in mind:
- On a cleared form, the calendar should be showing "--:--:--" but it is currently showing some value. The fix is in the upcoming publish reform branch.
- When an entered value is invalid (e.g. future), `releaseTimeEdited` is not updated + form disabled + warning appears (i.e. invalid values are not stored in redux).

PublishDate: make widget follow the 24h format setting

---

package.json
yarn.lock

Bump `videojs` to 7.19.2, it includes some updates for `http-streaming` which may be useful
Deployed to anthony for testing

Bump videojs to latest version

---

ui/component/channelSelector/index.js
ui/component/channelSelector/view.jsx
ui/component/channelThumbnail/index.js
ui/component/channelThumbnail/view.jsx
ui/component/comment/view.jsx
ui/component/livestreamComment/view.jsx
ui/component/premiumBadge/index.js
ui/component/premiumBadge/view.jsx
ui/component/sideNavigation/index.js
ui/component/sideNavigation/view.jsx
ui/component/textareaSuggestionsItem/index.js
ui/component/textareaSuggestionsItem/view.jsx
ui/component/uriIndicator/index.js
ui/component/uriIndicator/view.jsx
ui/component/wunderbarSuggestion/index.js
ui/component/wunderbarSuggestion/view.jsx
ui/page/channel/index.js
ui/page/channel/view.jsx
ui/page/odyseeMembership/view.jsx
ui/redux/selectors/claims.js

_@saltrafael, can you help to review in case I missed something?
The only thing that I noticed didn't work is in `textAreaSuggestion`, but seems like the badge is not appearing in Production either (not something we need to figure out at this point, I think)_
----
Closes [#1753 odyseeMembershipByUri function causing unnecessary renders](https://github.com/OdyseeTeam/odysee-frontend/issues/1753)
While the rendering issue in the ticket is due to the way the props are defined, it also surfaced a prop-drilling issue with PremiumBadge.  Lots of components are listening to changes in `odyseeMembershipByUri` unnecessarily.
Instead of asking the parent for the membership db, it can retrieve from Redux itself. This prevents the prop from crossing 2 levels of components and causing unnecessary …

`PremiumBadge`: retrieve membership db internally instead of from parent

---

ui/component/channelContent/view.jsx
ui/component/claimListDiscover/view.jsx
ui/component/claimListHeader/view.jsx
ui/page/discover/view.jsx

Ticket: #1762
For the placement of the button, putting it inside the expanded settings group feels the most natural, plus we then don't need to check whether the channel has reposts or not before displaying it (the expanded area is for stuff like this).
While it is currently persisted, it is no per-channel.  Usually, doing something like `usePersistedState(`blah-${pathname}`)` would achieve this, but because `ChannelContent` is not remounted when `pathname` changes, the state becomes incorrect.  Put to draft if this is critical -- can be fixed, just thinking of the best solution (remount, or tweak `usePersistedState` to respond to key changes -- most likely the latter).

Add "Hide Repost" button in channel page

---

ui/redux/actions/rewards.js
ui/redux/selectors/rewards.js

If the reward-list fetch is slow, the selector assumes the weekly_watch hasn't been claimed yet, causing an unnecessary claim.
The selector now tells the caller if there is no data -- up to caller on what to do (in this case, don't claim the reward).
It should be harmless if the claim action was missed, since the user can still manually claim it.

Assume `weekly_watch` is claimed when data is insufficient

---

yarn.lock

Don't really have any direct behaviorial fixes that would benefit us, but it includes a few smaller fixes and dep updates.  I guess no harm upgrade to latest and greatest?
Tested for a few hours ... looks ok.

tus-js-client: 2.3.0 to 2.3.2

---

web/setup/publish-v2.js

When it upload reaches 100%, click Cancel (not refresh).
There was an old hack in b0509bc9 where we decided to wait a while before sending `notify` as the server was not responsive. Since the task was dispatched before the Cancel action, the server cleared the upload first and later received the `notify`.
Instead of trying to cancel the timer, I think the hack is no longer needed given the throughput and lock fixes. With things running back in sequential mode, the Cancel button will now just show the "upload already completed" modal in this scenario.

tus: Fix `upload not found` scenario

---

ui/component/webUploadList/internal/web-upload-item.jsx

Closes #1804
Can't recall why it was removed ... probably for something not important.

Publish: restore percentage label when uploading

---

ui/component/common/markdown-preview.jsx

When Safari parses lbry:// URLs, it breaks them as they are not
compliant with the RFC 3986 URI syntax. This causes iframes in text
posts which link to a lbry:// URL to not display on Safari.
Instead, just use the lbry:// URL matched from the iframe regex instead
of parsing the iframe on Safari.
For more info see https://github.com/OdyseeTeam/odysee-ios/issues/217#issuecomment-1116993724.
On https://odysee.com/@dev-test:8/test-embed:b
iframes and URL text rendered correctly, like on other browsers.
</details>

Fix lbry:// URLs in iframes being broken by Safari

---

.env.defaults
ui/component/webUploadList/internal/web-upload-item.jsx
web/setup/publish-v2.js

Second attempt, this time just hiding the cancel button when the upload is done. If user is impatient and refreshed in between this and `notify`, it will still be resumable later.
Bumped MINIMUM_VERSION to nudge for a refresh so we get a slightly more accurate logging, and also to prevent the issue from lingering.

(patch) tus: Fix `upload not found` scenario

---

ui/component/collectionItemsList/index.js
ui/component/collectionItemsList/view.jsx
ui/redux/actions/collections.js
ui/redux/reducers/collections.js
ui/redux/selectors/collections.js
ui/util/url.js

> _:warning: This goes into `playlist-v2` branch instead of `master` due to large conflicts. 
> :information_source:  Can be shipped together with that, or after.  
> :bulb: Maybe this can be reviewed and merged into salt, so we can test both `playlist-v2` and this PR together, since `playlist-v2` still have some outstanding issues to handle._
#1758
This alleviates the lock-up that is caused by large number of invidual resolves. There will still be some minor stutter due to the large DOM that React needs to handle -- that is logged in 1758 and will be handled separately.
Performance:
- ~200 items: completes 2s
- ~600 items: placeholders appear after 10s, completes after 40s (vs. CPU 100% for >4 minutes in production).
Private list items are being resolved individually, super slow if the …

Batch-resolve private collections

---

ui/component/webUploadList/internal/web-upload-item.jsx

https://odysee-workspace.slack.com/archives/C02GSHBKYEM/p1657571082411839?thread_ts=1654909550.197639&cid=C02GSHBKYEM
If the user refreshed on a v1 upload, we can't do much but must at least provide a Cancel button for them to remove the entry.
- Restore the cancel button behavior for v1 like it was before.  The recent changes on the visibility of the Cancel button should only be applied to v2.
- Also fixed missing cancel button on v2 after refresh if the progress reached 100%.

Fix v1-publish items not removable

---

static/app-strings.json
ui/component/reportContent/index.js
ui/component/reportContent/view.jsx

- Use `finally` instead of an arbitrary timer to clear the spinner when resolving the claim.
- Move away from `makeSelect*`
- `perform`: use object form as there is no customization.
- Effect-dependency cleanup.

ReportContent: cleanup and improvements

---

ui/page/discover/view.jsx

Fixes the "force repost" behavior in Category Page.
Got the logic wrong when the boolean parameter was inverted from "force" (+ve) to "hideRepostOverride" (-ve) to support the "Hide Repost" button.
`hideRepostOverride`:
- undefined = follow user setting
- true = always hide
- false = always show << we want this

(patch) Add "Hide Repost" button in channel page

---

ui/redux/actions/app.js
ui/redux/middleware/shared-state.js

Closes https://github.com/OdyseeTeam/odysee-frontend/issues/1815#issuecomment-1178728712
When settings are changed before the first successful sync, the changes are on top of the default wallet preferences, and becomes the "latest". When sync is possible again later, the bad data is pushed to the cloud.
Continue to operate on `local` until the first successful sync. Most of the GUI will warn (or even prevent) the user from changing settings in this scenario, so the amount of "discarded" changes in `local` is minimal.

Sync: operate on `local` until the first successful sync

---

ui/page/channelsFollowingDiscover/index.js
ui/page/channelsFollowingDiscover/view.jsx
ui/redux/selectors/settings.js
ui/util/url.js
web/src/getHomepageJSON.js

:warning: Requires https://github.com/OdyseeTeam/odysee-homepages/pull/1751
Test: `kp`
Adds ability for homepage team to define the Discover list of IDs.
If undefined, falls back to English's list. If English is also undefined, falls back to LATEST / PRIMARY.

Grab Discover IDs from homepage API

---

static/app-strings.json
ui/component/webUploadList/internal/web-upload-item.jsx
web/setup/publish-v2.js

#631 
`https://github.com/tus/tus-js-client/issues/255`
- `touch` the file while it is being uploaded, or anything that would change `File` object.
- This can happen in real life: Android, by torrent apps, by anti-virus, etc.
- On Google Drive, it shows up as "File Unreadable" and there is no way to resume (`https://support.google.com/drive/thread/46682177/mp4-file-upload-fails-with-file-unreadable-error?hl=en`)
Currently, unless the user refreshes, the "Resume" button uses the same `File` object, so we end up with the same error again.
- Since we can't programatically detect this scenario (vs. temp network glitch), always assume it so and force the user to re-select the file.
- Reduce the number of auto-retries back to 3, since it's pretty much pointless if it not a trivial connection …

tus: handle "failed to upload chunk" when file is modified

---

ui/component/fileRenderInitiator/view.jsx
ui/component/headerNotificationButton/view.jsx

Issue Number: closes #1849
- Only applies to Comment Replies since assumes the video was already watched before

Disable autoplay when clicking comment reply notification links

---

ui/constants/errors.js
web/setup/publish-v2.js
web/setup/publish.js

The forced timeout seems to be causing more errors than usual on large files, which naturally take longer on the SDK side.
Just beautify the message instead of forcing a timeout. Should have done this in the first place.
Note that I wasn't able to fully test this given it's hard to replicate, but it shouldn't cause any problems even if the code fails to capture the scenario -- it will just show the original error message, and the "remove" modal will still explain things.

notify: remove forced timeout, just beautify message

---

ui/modal/modalRouter/view.jsx

If something wrong happens due to internet connection and we have something to convey through the modal, the message is lost because we can't fetch the lazy loaded modal.
Make ModalError part of ui.js
ModalError handles `event/desktop_errors` -- if failed to dispatch this due to connection errors, maybe should try stash and retry later, so that we don't lose any valuable logs?  Not that critical, though.

Don't lazy-load ModalError

---

ui/util/geoRestriction.js

A channel was blocked in UK, with a specific content that's blocked in AU|NZ.
The code assumed that the channel geoblock data will always be a superset, which is incorrect.

Geoblock: handle slipped content when the channel is only blocked in other regions

---

ui/component/app/view.jsx
ui/component/channelSelector/view.jsx
ui/component/commentsList/view.jsx
ui/component/fileRenderFloating/view.jsx
ui/component/livestreamChatLayout/view.jsx
ui/component/notification/helpers/text.jsx
ui/component/router/view.jsx
ui/component/swipeableDrawer/view.jsx
ui/component/textareaWithSuggestions/view.jsx
ui/effects/use-resolve-pins.js
ui/page/channel/view.jsx
ui/page/channelsFollowingManage/view.jsx
ui/page/discover/livestreamSection.jsx
ui/page/livestream/view.jsx
ui/page/show/view.jsx
ui/page/signInVerify/view.jsx

Patch for 4893085e
Double-dash is the documented way to add comment after an eslint rule, so saves one additional line/clutter.

Use single-line for eslint-bypass comments

---

flow-typed/Collections.js
ui/component/buttonAddToQueue/view.jsx
ui/component/claimMenuList/view.jsx
ui/component/claimPreview/internal/buttonRemoveFromCollection/view.jsx
ui/constants/collections.js
ui/modal/modalRemoveCollection/view.jsx
ui/redux/actions/collections.js
ui/redux/actions/content.js
ui/redux/reducers/collections.js
ui/redux/selectors/collections.js
ui/util/collections.js

Problem with using literal:
- error-prone (typo)
- harder to add new types (e.g. sections, channels, etc.) -- it will be easier to search for areas to update if a constant was used.
- Use constant.
- Add flow to capture potential mistakes.
- Factor out the collection-type logic so that it'll be easier to tweak later.

Add flow to "collection type"

---

ui/modal/modalPublishPreview/view.jsx
web/setup/publish-v1.js
web/setup/publish.js

- Seeing lots of preview timeout failures (should be SDK timeout).
- https://odysee-workspace.slack.com/archives/C02GSHBKYEM/p1658270926490769
- We are showing the "wait a few minutes and check transactions" message in this scenario, as if it was published.
Don't fail on this scenario -- just not show the estimated transaction amount.
I think we can shorten the timeout further specifically for preview ... 60s seems too much just for an intermediate modal that can actually be suppressed by the user in the first place.  Thoughts?

Publish: don't fail on `preview` timeout

---

ui/component/viewers/videoViewer/view.jsx

Fixes Issue Number: #1859 
Play a video -> autoplay ON -> recommended loaded -> play a livestream -> the play next button stays there

Fix next item button appearing on livestreams

---

ui/component/recommendedContent/index.js
ui/component/recommendedContent/view.jsx
ui/component/searchOptions/index.js
ui/component/searchOptions/view.jsx
ui/component/wunderbarSuggestions/index.js
ui/component/wunderbarSuggestions/view.jsx
ui/constants/search.js
ui/page/search/index.js
ui/redux/actions/search.js
ui/redux/selectors/search.js
ui/scss/component/_button.scss
ui/util/query-params.js
ui/util/search.js

_It's up on `kp`, but cors issue is also there.  Can't fully test -- just checked the payload.
The recs one does go through, but doesn't seem to make any difference._
----
Closes #1106
- Include:
- Wunderbar popup
- Search Page
- Recommended Section
- Exclude:
- Channel search bar

Pass "search in language" to some Lighthouse calls

---

web/setup/publish-error.js
web/setup/publish-v1.js

Trying to figure out "stream name cannot be blank" problem.
Eventually the `misc` could be opened up for all errors, but not exposing it in the function prototype for now.

Publish: log the params for v1 errors

---

ui/component/collectionItemsList/index.js
ui/component/collectionItemsList/view.jsx
ui/page/collection/index.js
ui/redux/actions/collections.js

When viewing own edited playlist (`/$/playlist/<id>`), the GUI jumped the gun and resolved entries individually because `urlsReady` is true given that edited URLs are stored in the wallet.
This is the same problem with the private list that was fix recently, but we also need to resolve the collection to get the collection claim, but resolve the edited URLs from the wallet instead of from the claim.

Optimize resolves for edited playlists

---

flow-typed/content.js
ui/component/app/view.jsx
ui/modal/modalAnnouncements/view.jsx
ui/redux/actions/sync.js
ui/redux/reducers/content.js

1. Change homepage to one that has a different announcement than English's (e.g. Spanish).
2. Refresh --> see Spanish announcement.
3. Change back to English.
4. Refresh --> see old English announcement again.
Keep a list of hashes instead of just 1 to account for various Homepages.

Announcements: handle history being replaced when Homepage changes

---

ui/modal/modalRemoveComment/index.js
ui/modal/modalRemoveComment/view.jsx

Due to the context menu being in the far right, I've often hit the wrong context menu and deleted the wrong comment, as the modal only said "are you sure?".
This gives me a chance to double confirm.

RemoveComment: show the msg in the modal to avoid deleting the wrong one

---

ui/component/viewers/videoViewer/internal/videojs.jsx

Some streams are using an old host which is causing SSL issues

Switch over to use different host for loading streams

---

ui/index.jsx

This appears in each sentry breadcrumb
The warning seems to be useless since there is no code (even in other repos and build machine) that uses SDK_API_HOST.

Remove SDK_API_URL warning

---

ui/component/recommendedContent/view.jsx
web/component/ads/view.jsx

Vendor suspects this is causing the other tile to not load, but 2nd video tile still doesn't load. But use it nonetheless to reduce one variable.
One of the script doesn't work in mobile (misalignment issue), so just remove that.
Test: `kp` after 8 minutes

Remove double ad-tag

---

ui/redux/actions/publish.js

Livestream-creation goes through a different code path than the usual v1/v2 publishing, and there was a bug for not handling "Error vs. string" in the middle of this path.
While at it, ensured that we show the full explanation for this path instead of the generic "${method}: Your action timed out, but may have been completed.".

Fix blank string in Error Modal on livestream-creation timeout

---

ui/component/publish/livestream/publishLivestream/view.jsx
ui/component/publish/upload/publishFile/view.jsx
ui/redux/selectors/publish.js
ui/util/lbryURI.js

"_Stream name has invalid characters_"
https://odysee-workspace.slack.com/archives/C02GSHBKYEM/p1659617796387469
Linux allows any character for a file name, so '\n' slipped through when selecting a file from the file browser.
The actual fix is just the `regexInvalidURI` regex change (please double-check).
The rest is just DRY stuff.

Filter out '\n' from 'name'

---

ui/component/uriIndicator/view.jsx

Show claims with invalid channel signature on previewTile as Anonymous. (Does already show as Anonymous on content page)
Example can be seen on this channel http://odysee.com/@MyGreatChannel:3a. This claim http://odysee.com/aaaaaa:07 showed as belonging to the channel, but it wasn't signed by the channel owner. (Invalid channel signature)
Also can be seen here https://odysee.com/@KeyTestChannel:d (Public key is updated, but some claims aren't singed with new key)
New|Old
(Tom said that hub should check validness of signatures by default for claim_search in general. But also said this maybe ok, so made a PR in case it is)

Show claims with invalid channel signatures as Anonymous

---

ui/component/headerNotificationButton/view.jsx
ui/component/notification/helpers/target.jsx

- Closes #1953
- Closes #1952
The change in d34d32ac caused the `search` parameter to be blank (everything went into `pathname`).
1. Parse the notification target and define `pathname` and `search` to feed into `NavLink::to`
2. It seems like the `push` in `NavLink::onClick` is redundant (`onClick` and `to` is union'd?), so removed that.

Fix notification popup redirects

---

extras/lbryinc/lbryio.js

Default api calls from 'get' to 'post'

---

extras/lbryinc/lbryio.js

Cloudflare not working nicely with post calls for blocking/filtering caching, reverting for now. We'll see if we can fix, and if not, may need to exclude filtered/blocked, or anything where auth token is null.

Revert "Default api calls from 'get' to 'post'"

---

ui/component/commentCreate/view.jsx

:warning: this goes into `chat-revamp-v2` rather than the usual `master`.
Actual change (minus refactoring):  [link](https://github.com/OdyseeTeam/odysee-frontend/pull/1964/commits/9c182fab2d56117a80537baa482cf2f3ebedc845?diff=split&w=1)
Typing on the input field is slow (although ok in development build) because everything is re-rendered when `commentValue` changes. `EmoteCategory` is the slowest based on the profiler.
Memoize `<CommentSelectors>` so that `EmoteCategory` doesn't re-render.

commentCreate: prevent CommentSelectors from re-rendering on input change

---

ui/redux/actions/comments.js

Clearer diff: https://github.com/OdyseeTeam/odysee-frontend/pull/1963/files?diff=split&w=1
`doFetchModBlockedList` is blocking the ui thread.
Duplicate data in `doFetchModBlockedList::blockListsPerChannel` to about 1000. The tab is dead when function hits, about 4s after reload.
- Yield occasionally using the `setTimeout` method.
- Doing a chunk size of 1 for now so we don't have to yield the inner loop as well (seems good enough based on a relatively large blocklist).
- Can't do `await` in a callback, so must change the `forEach` to a `for`.
- The creation of `storeList` should probably be outside of the loop, but retaining so that the diff is more readable + this is more of a scalability problem rather than efficiency.

doFetchModBlockedList: don't block ui thread

---

ui/redux/actions/collections.js

Closes #1972
Open local edit page for some playlist
Update thumbnail there
Opening playlist crashes page
---------------------
Bad typo caused the thumbnail url to become the description, which later couldn't be parsed.

doCollectionEdit: fix typo causing description to be incorrect

---

extras/lbryinc/lbryio.js
ui/analytics.js
ui/analytics/apiLog.js
ui/analytics/events.js
ui/analytics/overview.md
ui/analytics/watchman.js
ui/component/app/view.jsx
ui/component/channelEdit/view.jsx
ui/component/creatorAnalytics/view.jsx
ui/component/fileRender/view.jsx
ui/component/inviteNew/view.jsx
ui/component/repostCreate/view.jsx
ui/component/tagsSearch/view.jsx
ui/component/tagsSelect/view.jsx
ui/component/userEmailNew/view.jsx
ui/component/userFirstChannel/view.jsx
ui/component/viewers/videoViewer/internal/videojs-events.jsx
ui/component/viewers/videoViewer/view.jsx
ui/component/wunderbarSuggestions/index.js
ui/effects/use-get-ads.js
ui/index.jsx
ui/page/collection/internal/collectionPublish/view.jsx
ui/page/discover/view.jsx
ui/page/livestream/view.jsx
ui/redux/actions/app.js
ui/redux/actions/publish.js
ui/redux/actions/settings.js
ui/redux/middleware/analytics.js
web/component/browserNotificationSettings/use-browser-notifications.js

No functional change, just re-organizing
Test: `kp`
- Harder to maintain with events, watchman, api, sentry, etc. all lumped into 1 file -- can't tell which variable is for which component.
- Swapping out or upgrading sub-components (e.g. sentry revamp) would also be easier if they are organized per file.
- `events` is probably the less critical one to test (but I still tested) since GA is going away ... might route those to sentry later if things go well with the revamp.
- Areas that require a second set of eyes are probably just watchman and api (for the views).
- Just noticed that watchman faces the same ublock problem, but most likely a known problem.
- Wanted to avoid changing the interface to reduce chances of mistake (e.g. `analytics.reportEvent` to `analytics.event.report`), but …

Refactor `analytics.js`

---

ui/component/claimList/view.jsx

Closes #1980 -- crash when trying to re-order a playlist
Seems like the update was only needed for DND in modal.

Partial undo of the firefox drag-and-drop fix

---

ui/component/collectionGeneralTab/view.jsx
ui/component/common/markdown-preview.jsx

Additional changes for 289dadbb
- Make the md component not crash so that users get a chance to fix the field.
The code can be eventually removed later.

(patch) "doCollectionEdit: fix typo causing description to be incorrect"

---

web/component/adBlockTester/view.jsx

Part of #1983
Place a bait div with class names that would trigger ad blockers.
- Does not work 100%, e.g. Privacy Badger blocks bad behavior/scripts and not ads per-se.
- The trigger list might need to be expanded to cover more blockers. This was only tested with uBlock-o.
- Now that ad-tiles have a good-looking placeholder, do we even need to detect ad-blockers?
- For the uneven-tile scenario, I'm still seeing that in production anyways even with blockers correctly detected.
- Seeing the same with competitors as well -- small price to pay for using ad blockers.
Can't recall if there are other reasons we needed that for...

Replace ad-detection script with simple css trigger approach

---

static/index-web.html

https://odysee-workspace.slack.com/archives/C02FVMZ8SFJ/p1658333988736469
- https://odysee-workspace.slack.com/archives/C02FGH8E6EQ/p1658373279679609
- Notifications seem to still work on dev instance, but let's monitor on the real thing.
- Complete removal will done in the Sentry revamp, where some of the event can be routed to Sentry.

Disable GA

---

ui/analytics.js

It's over-logging, capturing things from other packages like ads.  Almost 4x.
Gotten enough sample data to fine-tune the filtering, so disabling it for now.

Temporarily disable sentry

---

ui/page/playlists/internal/collectionsListMine/view.jsx

Band-aid for #2007
Still not sure how a null name would propagate here during confirmation (should investigate further), but this would at least prevent the crash and simply retained the order.

Handle null/undefined names in collection sort

---

web/bundle-id.js
web/src/html.js
web/webpack.config.js

- 2 issues in 1. 
- Test: `kp`
1. Sentry -- it needs a version number to tie up source-maps.
2. New bundle ID for the `ui.js` file.
- solves issue_2003
- easier to determine which commit a particular ui.js is from.
`"<YYYYMMDDHHMM>.<commit_id_12_chars>"`
- The time will be in UTC.
- Rationale for format:
- Putting the date in front allows the string/file to be sortable.
- Combining both date and commit id covers the case of rebuilding from the same commit, i.e. BUILD_REV would still end up unique.
- `COMMIT_ID` comes from the command line, which it currently does in production. If not provided (e.g. debug), the rev would just be the date string.
Closes #2003
It's a combination of 2 problems:
(a) `getJsBundleId` houses a file-level variable that would end up in a new context when Node …

Add `BUILD_REV` + fix `jsBundleId`

---

static/app-strings.json
ui/page/playlists/internal/collectionsListMine/view.jsx
ui/redux/actions/claims.js
ui/redux/actions/collections.js
ui/util/url.js

Several issues found while investigating the issue reported from the user with 609 public playlists.
See commit message for details.
Better diff:  https://github.com/OdyseeTeam/odysee-frontend/pull/2036/files?diff=split&w=1

Playlist: handle `null` entry and large public collection fetch

---

.env.defaults

Seems like the token got invalidated (or deleted or restricted) after the reboot last night, as we got a permission error while uploading.
The new errors that came in for that build messed up the grouping -- something to figure out how to handle.
Switched to new token in production.

Bump rev to rebuild with new sentry token

---

ui/component/claimListDiscover/view.jsx

The following 2 commits introduced some errors:
- 0cc3af28: "flow fixes"
- Seems like a misintepretation of lint warning, as the effect is meant to be a one-off.
- dfc013d4: "more recon"
- Seems like a merge error, as `orderParamEntry` should only be used in a `POP` action.
The 2 broken scenarios are:
1. Enter /$/popculture. Assuming the current order is "Trending" as an example...
2. Click "New"
3. Click "Top"
4. Click Back -- order must be "New"
5. Click Back -- order must be "Trending"
1. Click "PopCulture" in the sidebar
2. Change the order, e.g. to "New"
3. Click "Playlists" in the sidebar
4. Click "PopCulture" in the sidebar -- order must be "New"

Fix broken orderParam persistence

---

static/app-strings.json
ui/component/claimPreview/view.jsx
ui/page/channelsFollowingManage/view.jsx

Closes #2045
An oversight when re-implementing that page -- a "manage" page should always show full/raw list to allow removals.

Follow-Manage: don't hide blocked & muted channels

---

ui/component/claimPreview/view.jsx

Deleted channels aren't showing up properly in the Following-Manage page
Redo 080a36c5 a bit by not making `showUserBlock` cover both abandoned and nsfw -- there is `showUnresolvedClaim` for the former already.
Technically, even this solution is wrong because `obscureNfsw` is available for that, but unfortunately this needs to fan out to `ClaimList`, `ClaimListDiscover`, etc., which is a pain to test. There is a ticket for that major refactoring.
080a36c5 just wanted to display abandoned and nsfw in the Blocklist page, so this solution still achieves that since the block list page is already passing in `showUnresolvedClaim`

(patch) show blocked mature channels on block list

---

ui/component/fileRender/view.jsx

Just skip the call for web, which the browser already handles.
An alternative fix is to provide a proper exit-fullscreen stub that does nothing.

Fix exit-fullscreen unhandled exception

---

ui/redux/actions/settings.js

`user/language` being called before `user` is populated.
One of the highest hits in Sentry.
Not the cleanest/robust of solutions, but this avoids polluting all clients with checks on `user !== undefined`.

user/language: handle "could not authenticate user"

---

ui/component/viewers/videoViewer/view.jsx

`error()` returns a `MediaError`-like object, not `Error`-like object. Sentry mishandles it.
Log the individual media errors in a way that Sentry accepts.
We could now get a count for loading issues like "The media could not be loaded, either because the server or network failed or because the format is not supported.", etc.  But I assume the backend would be logging a similar thing, so not sure if the front-end needs to do the same.

Fix logging of videojs media errors

---

ui/component/viewers/videoViewer/view.jsx

Server-side rule didn't work, so handling it from the SDK...

Sentry: consolidate videojs error with variable values

---

ui/page/search/view.jsx

Not critical, but at least handle it gracefully.
Users seem to end up in these page somehow.

Handle crash on empty `/$/search` query

---

ui/component/viewers/videoViewer/internal/videojs-shortcuts.jsx

"HTMLMediaElement.currentTime setter: Value being assigned is not a finite floating-point value."
S_23723

Video: ignore seek shortcut while video is still loading

---

ui/component/claimPreview/index.js
ui/component/claimPreviewTile/index.js
ui/effects/use-get-thumbnail.js

If an image file does not contain `thumbnail.url`, the fallback is to fetch the image itself as the thumbnail. But for the case of a reposted image file, the `get` API ends up throwing a "stream doesn't have source data" error because the repost uri was used.
Also, `claimPreviewTile` was missing the `streamingUrl` selector like it's `claimPreview` counterpart.
1. Use the repost src uri when doing `get`.
2. `claimPreviewTile`: get `streamingUrl` prop.
3. Change the `streamingUrl` prop to look at the repost src instead.

Fix thumbnail fetch for reposted image (without `thumbnail.url`)

---

web/component/adsSticky/view.jsx

Copy/pasted from vendor -- but we don't need to use the newer `append` function ... `appendChild` works fine.

Fix adSticky failures on older browsers

---

ui/analytics/sentryWrapper.js

Documentation uses `whitelistUrls`, but saw folks mentioning in threads that it is now `allowUrls`. Tried it, and sure enough it prevented ad errors from being sent. No wonder it hasn't work since lbry.tv.
Note that it will no longer send entries in development build, because that is served by `webpack://`. Not sure whether it's wise to add that at this point.

Sentry: `whitelistUrls` doesn't work; `allowUrls` does

---

ui/component/publish/livestream/publishLivestream/view.jsx

Replays zero minutes long shown as "0 minute" (no plural)
Shown as "0 minutes".
One minute long replays are shown as "1 minute".
Longer are shown as "x minutes".
</details>
**Note:** I haven't tested this change, but I think it's simple enough that nothing should break.

Fix one/other plural format in livestream replays

---

ui/redux/actions/user.js

Handling uncaught errors.
It doesn't seem like the function intended to do anything on failure, and neither does its caller, so just log the error for now.

Handle failed `version` in `install/new`

---

ui/page/top/index.js
ui/page/top/view.jsx

Seems like we are redirecting to empty top page from `/$/signin` and `channel/new`
#2083 will be required for the full fix, but handle the crash for now.
Removed unused prop while at it.

Fix crash in `/$/top` with empty query

---

ui/component/creatorAnalytics/view.jsx

https://sentry.lbry.tech/organizations/odysee/issues/22608
Double-checked with the iapi repo

`channel/stats`: not all error responses come with `status`

---

extras/lbryinc/lbryio.js
ui/analytics/sentryWrapper.js

- This will end up capturing trivial network errors as well, so it is expected to be noisy. But the idea is to allow creation of a custom spike alert that's specific to iapi.
- It currently groups up all methods into a single entry. To isolate them, use the "Tags" or "Open in Discover" feature in the dashboard.
- :question: Can spread it out to per-method if that's easier to detect issues from specific commands.  But my guess is it's usually all or nothing when downtime occurrs
- This does not change the existing code flow -- it only sends out analytics on failure and re-throws the error.

Record internal api failure count

---

extras/lbryinc/lbryio.js

- In addition to uncaught exceptions, a prior PR attempted to log all error responses from the internal api.
- But `customer/status` returns an error for users without a card, instead of returning it as a valid response (e.g. "no card").
Just ignore that command for now.
Not sure if Sentry will hold as a metric collector ... might need to turn this off entirely.

Ignore `customer/status errors`

---

ui/component/fileRenderFloating/view.jsx

https://sentry.lbry.tech/organizations/odysee/issues/29809
Per MDN, "className can also be an instance of SVGAnimatedString if the..."

(patch) Re-do: fix volume slider issues

---

ui/redux/setup/tabState.js

The Watch History never worked correctly when multiple tabs are opened -- I think the last tab to call `purge` (closed) wins.
We have tab-sync now, so it should work correctly.

Tab-sync the Watch History

---

ui/component/claimListDiscover/view.jsx
ui/component/claimTilesDiscover/index.js
ui/component/claimTilesDiscover/view.jsx
ui/constants/tags.js
ui/page/discover/livestreamSection.jsx
ui/page/discover/view.jsx
ui/page/home/view.jsx
ui/util/claim-search.js

#2159
```
- hide member only content on categories, and homepage categories.
- Leave on following / wild west.
- Do this by appending the c: members only tag to not tags claim searches.
```
- Protect `MATURE_TAGS` array from unintended edits (e.g. pointed to directly by a variable, and then `push` or `splice` is called).

Claim*Discover - ability to exclude members-only content

---

static/app-strings.json
ui/component/app/view.jsx
ui/constants/modal_types.js
ui/modal/modalRouter/view.jsx
ui/modal/modalSignOut/index.js
ui/modal/modalSignOut/view.jsx
ui/redux/actions/app.js
ui/util/beforeUnload.js

Closes #419 
We use `beforeUnload` to invoke the browser's alert message when there are pending actions like Uploading or unsaved Settings.
The sign out code have no idea this is going on, so when it tries to reload, the alert appears in a recursion.
- Add a wrapper for the `beforeUnload` functionality, so we can keep track of it.
- Before signout out, open a modal and list out all the pending actions,
- This also solves the problem of the browser alert not saying anything useful to the user (all browsers no longer relay the msg param and just show a generic one to avoid spam abuse).
- If OK is pressed, we unregister the listeners and proceed as normal.
It would be nice if we could show the same modal on an F5 case, but I don't know how to intercept that case. Maybe in the future.

SignOut: prevent infinite loop from 'beforeUnload' listener

---

ui/modal/modalConfirmTransaction/view.jsx

Closes #1890
`channel_id` not being populated

Fix wallet-send always being anonymous

---

ui/modal/modalSignOut/style.scss
ui/modal/modalSignOut/view.jsx

When a ul-li is used within a bordered box, the asymmetrical margin causes the list to be "shifted" downwards.
Taking a risk by making a global change rather than a wrapped one. This will cause the list to have a bottom margin instead of zero in Posts, for example, but I think the symmetry looks better anyways, unless there is a specific case that doesn't want that.

Fix <li> margin symmetry

---

ui/component/claimListHeader/internal/additionalFilters/index.js
ui/component/claimListHeader/internal/additionalFilters/style.scss
ui/component/claimListHeader/internal/additionalFilters/view.jsx
ui/component/claimListHeader/style.scss
ui/component/claimListHeader/view.jsx

- To prep for more "Hide xxx" actions
- The "Hide Repost" checkbox was a eyesore as it doesn't look integrated with the rest.
See individual commits for details
Localization will break the "even width" sizing with Duration -- will come back to that later when there is a good solution. At minimum, a hover tooltip was added if the string ends up truncated with ellipsis.

ClaimListHeader: style fixes to prep for more "Hide xxx" actions

---

ui/component/viewers/videoViewer/internal/plugins/videojs-http-streaming--override/playlist-selectors.js

null access violation
It's just doing label-override, so nothing crucial

Skip "auto: ???p" label-override when algo returns nothing

---

ui/page/discover/view.jsx
ui/util/search.js

https://odysee-workspace.slack.com/archives/C02F638TB0T/p1663945340034239?thread_ts=1663779156.006539&cid=C02F638TB0T
See commit messages. I went off-script in the second commit, but I think that behavior is better?
:warning: Homepage team needs to remove `9999` still for the non-Top case.

Tag: Freshness fixes

---

ui/component/app/view.jsx

The file-drop area gets stuck in a loop on Firefox
The `event.dataTransfer.files` mysteriously gets set to 0 in Chrome at some point during the drag operation. The Firefox behavior actually makes more sense, where `event.dataTransfer.files` is retained since we did not explicitly clear it.
The code seems to depend on the weird behavior, and several hacks to emulate that wasn't successful. The fix should probably be something small, I just couldn't get it right.
Just disable for Firefox since it isn't functional anyway.

FileDrop: temporarily disable for Firefox

---

ui/component/selectThumbnail/view.jsx

Ticket: Closes #2205
We still need to block `data:image` because:
- Our CDN still doesn't handle it, so claim previews all fail.
- Potentially maxes out the claim meta size limit.
- Google Videos doesn't accept it (although we could wrap with CDN if supported later).
Check was removed in 69def916
@saltrafael, take a quick peek?  I'm just concerned I'm not seeing the full picture and broke something else instead.

(regression) Block encoded thumbnail URLs ('data:image')

---

web/setup/publish-v3.js

Can't say for sure, but it seems like the comparison with `upload is still in process` error message no longer works to reliably determine the wait time.
Restore the old hardcoded 15s for now.  Hardcoded stuff will not work 100%, but let's see if this lowers the "does not exists" error even further.

Publish: put back `notify` delay + more logs

---

ui/constants/errors.js
ui/redux/actions/publish.js

_:warning: This goes into memberships, not master._
This is what happens when I hardcode a 1s timeout on `v1`, and the Post actually got through.
You looking for something like this?

Restricted Content: handle publish timeout case

---

ui/modal/modalPublish/index.js
ui/modal/modalPublish/view.jsx

#401 - publish-success modal clears Post while you are still editing.
The original version tried to keep the form's data until Success so that we can re-upload the Post in the event of a failure.
But recent changes have introduced a `beginPublish` hook which clears the form every time you enter it. This makes the "clear on success" action no longer necessary, and fixes the annoying issue mentioned in 401.
The problem now becomes "data loss on page re-entry" for Post that you haven't submitted yet.
Pushing this first since it's no worse thatn status quo, and that the new issue requires a bigger change.

No need to clear Publish Form on success for now

---

flow-typed/stripe.js
ui/component/walletFiatAccountHistory/view.jsx

Closes #2229 
Downside to using `/$/search` is that it generates a bunch of redirects in the history, so back navigation becomes confusing (looks stuck).  Maybe the number of redirects itself is another bug.
Reduce the impact by spewing it into a new tab. The history actually becomes even longer there (don't know why), but at least the overall behavior is better that way (user just closes tab to "go back").

Fix incoming "Tip Location" link

---

ui/modal/modalPublish/index.js
ui/modal/modalPublish/view.jsx

5d2c9676
Removed too many things. We still need to clear the publish form on 'submission', just not on 'success'.

(patch) No need to clear Publish Form on success for now

---

ui/redux/reducers/claims.js
ui/redux/selectors/claims.js

- The stripe response for type could be `tip | rental | purchase | ???`, so someone who sent a tip could be gaining a purchase.
- Backend doesn't check?
- Fix `myPurchasedClaims` growing indefinitely with duplicate data for each `customer/list` with the same payload.
- Cannot de-dupe an array of Objects using the set method since each Object reference is always different regardless of content.
- I assume that the transaction data could change, but the `id` does not change, so using `id` for the comparison.

Purchase fetch and validation fixes

---

ui/redux/actions/stripe.js

Outgoing was showing "oldest first".
Remove the `reverse()`.  
- Did the backend flip the order at one point?

Stripe outgoing txo: remove the reverse sort

---

ui/scss/component/_header.scss

https://odysee-workspace.slack.com/archives/C02G20Z2AEL/p1666259109170879
- For Firefox 40 - 105, the logo works with or without `max-width` defined.
- For Firefox 106, the logo does not appear with `max-width` defined.
I don't really understand the full picture, but I believe it's no longer needed after the recent header component changes.
Confirmed with designer that max-width seems unnecessary. 
Tested against Firefox, Opera, Chrome, Safari.
0214c805 (fix logo size on firefox)

Fix missing logo in Firefox 106

---

ui/component/claimTilesDiscover/index.js
ui/component/claimTilesDiscover/view.jsx

Closes #2297
The Homepage's Following Section was stuck in an infinite `claim_search` loop when there are no results.
ClaimTilesDiscover assumes that there will always be results, and since it doesn't do pagination either, it doesn't check for the "last page reached" flag, hence the infinite loop.
Brought over some code from ClaimListDiscover/ClaimList.
We really need to consolidate these 2 components soon (#1163).

ClaimTilesDiscover: handle 0 results case

---

ui/component/fileRenderInitiator/view.jsx

#2304
This prevents `viewFile` from being hit too early.

Assume claim is lbc-paywalled until costInfo is fetched

---

ui/component/fileActions/view.jsx

Just some minor removal and shortening
On top of the logic error, I think I implemented the restriction incorrectly. It should always be displayed, but can't be clicked if not paid. Should we do this instead?
Also, the current logic requires both LBC and $ to be cleared. If the claim is paywalled by both (say from Desktop or some other means), the requirement doesn't feel right.

(minor cleanup) Show reactions on own claims

---

extras/lbryinc/lbryio.js
ui/component/viewers/videoViewer/view.jsx

No point collecting if we aren't monitoring these:
- videojs media errors
- iapi failures (we have a separate monitoring tool for that already)

Disable few unmonitored Sentry items

---

ui/component/playlistCard/view.jsx

Issue Number: closes #2061
from https://sentry.lbry.tech/organizations/odysee/issues/29538/?project=2&query=scrollTo&statsPeriod=14d
just don't scroll to currently playing item in those cases

Playlist: `le.scrollTo` is not a function

---

ui/component/viewers/videoViewer/internal/plugins/videojs-snapshot-button/plugin.js
ui/component/viewers/videoViewer/internal/videojs.jsx
ui/scss/component/_content.scss
ui/scss/component/_videojs.scss

Allows users to take a snapshot of the video at a given point
Might be interesting to open-source this separately as its own plugin, everything worked for me to do that except that I think the `playerClosed` event is something custom we use and also I couldn't get the `crossorigin` attribute to remain permanent, though perhaps that is due to how we store and reuse the videojs instance? Still uncertain about that

Snapshot button

---

ui/component/fileThumbnail/internal/thumb.jsx
ui/component/fileThumbnail/view.jsx
ui/effects/use-lazy-loading.js
ui/page/playlists/internal/collectionsListMine/internal/collectionPreview/view.jsx
ui/util/claim.js

Issue Number: closes #2339
- `thumbnailUrl` was being set to the `thumbnail` or `MISSING_THUMB_DEFAULT`, so instead use the resolving state when `undefined`, and use the fallback correctly when:
- image fails to load
- returned thumbnail value is `null`

Thumbnail: fix `images don't show on previews until loaded directly`

---

ui/component/router/view.jsx
ui/constants/pages.js
ui/page/iconsViewer/index.js
ui/page/iconsViewer/style.scss
ui/page/iconsViewer/view.jsx

Alphabetical list of all icons for easy viewing/selection at `/$/icons_viewer`

Add page that lists all icons

---

ui/component/claimListDiscover/view.jsx
ui/effects/use-fetch-view-count.js

Simply moved the `let finalUris` into a `setState` and then that whole condition inside its own `useEffect`

Fix: loading Docs page not fully displaying resolved items

---

ui/component/settingsStripeCard/view.jsx
ui/component/txoList/view.jsx
ui/component/walletFiatAccountHistory/view.jsx
ui/component/walletFiatPaymentHistory/view.jsx
ui/page/creatorMemberships/creatorArea/internal/overviewTab/internal/channelOverview/view.jsx
ui/page/creatorMemberships/creatorArea/internal/overviewTab/style.scss
ui/page/creatorMemberships/creatorArea/internal/overviewTab/view.jsx
ui/page/settingsStripeAccount/view.jsx
ui/page/wallet/view.jsx

Also renames Transactions to Tips for greater clarity, and directs people to the Stripe dashboard to see their full balances

Touchup frontend to remove Total Received amount values

---

ui/page/channel/tabs/homeTab/internal/homeTabSection/view.jsx

Doesn't leave empty channels stuck on the resolving state placeholder anymore

Fix: channel page resolving/empty states

---

ui/page/show/index.js
ui/page/show/view.jsx

Issue Number: https://github.com/OdyseeTeam/odysee-frontend/issues/2399
- navigating to the playlist canonical claim uri (rather than the `/$/playlist` page) would redirect to the first item and start playing it, but when direct loaded it was missing the fetch items call so at least the first item needs to be resolved so it doesn't show the "download" page

Playlist: fix dead links

---

ui/component/common/markdown-preview.jsx
ui/scss/component/_livestream-chat.scss

Use thumbnail CDN for GIFs in markdown.

Enable thumbnail CDN for gifs

---

ui/page/claim/internal/claimPageComponent/internal/channel/tabs/aboutTab/view.jsx

Fixes this:
Channel page has "Last Updated", but it is showing creation time.  
Updated the text to "Created At"
https://odysee.com/@Odysee:8?view=about
(OLD)

Last Updated showing creation time on channel about tab -> change the text to say Created At

---

flow-typed/Lbry.js
ui/component/claimListDiscover/view.jsx
ui/component/claimListHeader/view.jsx
ui/constants/claim_search.js
ui/scss/component/_claim-search.scss

Attempt to merge min/max duration filter to one setting
Separate longer and shorter duration filter settings
One duration filter setting, allowing min and max duration.
----
Need some help with styling. (Assuming this is good otherwise)
This line makes setting look bad on mobile, but don't know what's it needed for, or proper way to avoid. https://github.com/OdyseeTeam/odysee-frontend/blob/master/ui/scss/component/_claim-search.scss#L84  
</details>

Attempt to combine min/max duration setting to same

---

ui/scss/component/_file-render.scss

This seems to work better than current one. Stuff doesn't seem to get pushed out with non 16/9 videos.
Nothing seems to have broken, but not sure.
NEW | OLD

Attempt to temp fix to make player not grow too large

---

ui/redux/selectors/claims.js

`uri` was forgotten to pass in`selectClaimForUri`.
Now the repost count shows with the repost button

Fix attempt - show amount of reposts on file page

---

ui/component/publish/shared/publishReleaseDate/index.js
ui/component/publish/shared/publishReleaseDate/view.jsx
ui/component/publish/shared/publishStreamReleaseDate/index.js
ui/component/publish/shared/publishStreamReleaseDate/view.jsx

-DateTimePicker defaulted to browser's language. (Could be different from page language)
Now uses language set on page.
-DateTimePicker on Go Live page didn't handle 24h clock format.
Now it does.  
Note: `null` and random string as a locale defaults to English.

Attempt to make DateTimePicker use app language + handle 24h clock on livestream page

---

ui/redux/actions/collections.js
ui/redux/reducers/collections.js

**Old behavior:**
If there is an entry in updatedCollection, updatedAt time of the edited list in the editedCollections list will revert to that on http://odysee.com/$/playlists page.
Steps to see the issue:
1. Have collection that's in updatedCollections
2. Edit it
3. Go to http://odysee.com/$/playlists 
4. UpdatedAt time shows the old updatedAt time from updatedCollections.
(5.) Next prefrence_set will also change the updatedAt of the list in the  editedCollections to the older time
**New behavior:**
When collection is edited, it gets removed from updatedCollections, so above can't happen.

Fix attempt - remove collection from updatedCollections on edit

---

ui/component/dateTime/index.js
ui/component/dateTime/view.jsx
ui/component/publish/livestream/publishLivestream/index.js
ui/component/publish/livestream/publishLivestream/view.jsx
ui/component/rewardListClaimed/index.js
ui/component/rewardListClaimed/view.jsx
ui/modal/modalPublishPreview/view.jsx
ui/page/creatorMemberships/creatorArea/internal/supportersTab/index.js
ui/page/creatorMemberships/creatorArea/internal/supportersTab/view.jsx
ui/page/listBlocked/index.js
ui/page/listBlocked/view.jsx
ui/page/wallet/walletFiatAccountHistory/index.js
ui/page/wallet/walletFiatAccountHistory/view.jsx
ui/page/wallet/walletFiatPaymentHistory/index.js
ui/page/wallet/walletFiatPaymentHistory/view.jsx

Release date always being in English despite the language setting.
Release date shown under the video is always in English
Release date under the video tries to get the format based on language.  
(Defaults to English when language doesn't match any locale in `moment`.)
For English language using `LL` changes the format from: `December 7th, 2022` to `December 7, 2022`
But `MMMM Do, YYYY` doesn't work well with other languages
Release date for German language new vs current
</details>

Attempt to use page language when formating release date

---

ui/component/fileWatchLaterLink/view.jsx
ui/component/playlistCard/index.js
ui/component/playlistCard/view.jsx
ui/modal/modalClaimCollectionAdd/internal/claimCollectionAdd/internal/collectionSelectItem/view.jsx
ui/page/playlists/internal/collectionsListMine/internal/collectionPreview/view.jsx
ui/util/collections.js

Built-in playlist always show English name. (Except within the 3-dot menu in thumbnail)
Changed built-in lists to use localized string in these places:
-title in playlistspage
-now playing <listname>
-notification from hovering "add to watch later"
-add to playlists modal

Attempt 2 to use translation for built-in playlist titles

---

ui/page/claim/internal/claimPageComponent/internal/channel/tabs/homeTab/internal/homeTabSection/view.jsx
ui/page/claim/internal/claimPageComponent/internal/channel/tabs/homeTab/style.scss
ui/page/claim/internal/claimPageComponent/internal/channel/tabs/homeTab/view.jsx

Old looks like this:  
Now should look like this(edit still bit off, but less bad?):  
https://odysee.com/@a:f1

Home page fix attempt (too much playlist items shown? + playlists section overlapping on edit )

---

ui/redux/actions/claims.js

Issue Number: #2518 
SDK channel_update gives error for `null`  values , so remove params with those before sending.

Fix attempt - channel update without thumbnailUrl

---

static/app-strings.json
ui/component/walletSendTip/view.jsx

The old strings weren't translatable in all languages(like Finnish). `claimTypeText` translates to different word depending of the context.   
Made separate phrase in each situation for each claim type.   
Also changed "Tip this %claimType%" to "Leave tip for the creator". (Sounds better?)
)

Make support texts more translatable + tip text change?

---

ui/redux/reducers/claims.js

Issue Number: #2492 
Also some stuff  in channel's about page doesn't get cleared anymore while pending confirmation.
Claim.meta gotten from `channel_update` is empty, so put claim in the `pendingById[]` after it's merged with oldClaim.

Merge claim.meta for pending claim from old claim on update

---

ui/page/playlists/internal/collectionsListMine/internal/collectionPreview/index.js
ui/page/playlists/internal/collectionsListMine/internal/collectionPreview/view.jsx
ui/redux/selectors/collections.js

NEW | OLD (Lists that aren't loading in old had some deleted items )
- Couldn't figure out how to make preview overlay to appear properly on lists like that, but at least the lists themselves appear now.  (Currently no overlay preview at all for lists with deleted items in early indexes)
- `selectThumbnailClaimUrisForCollectionId` was used only in one place(as far as I can tell) and for different purpose than name suggests. Seemed like duplicate of `selectUrlsForCollectionId`(which was/is used to get the thumbnail urls for collectionPreviewOverlay https://github.com/OdyseeTeam/odysee-frontend/blob/master/ui/component/collectionPreviewOverlay/index.js#L10) So seems that there's no need for it anymore?
- Doesn't seem to break anything, but don't know if I'm missing something (Also not sure …

Fix attempt - show lists which have deleted items in lower indexes in  playlists + delete unused function?

---

.gitignore
ui/component/sideNavigation/view.jsx

When the sidebar is open, and the user clicks on an element in the top navbar, then the sidebar does not hide
When the sidebar is open, and the user clicks on an element outside the sidebar, then the sidebar hides
https://user-images.githubusercontent.com/84881706/218353162-cf33b12f-c140-4875-b2e6-c05e9d58bf38.mp4
</details>

Sidebar hides when user clicks outside it

---

ui/component/comment/index.js
ui/component/comment/view.jsx
ui/component/commentMenuList/view.jsx
ui/component/sideNavigation/view.jsx
ui/scss/component/_comments.scss

- **Collapse first level of replies by default**
Hiding them seems pointless when most claims have less than 100 comments anyways.
- **Resolve channel titles**
Show titles instead of names (@handle) for the comment authors.
- **Add context menu to authors**
Resolved author titles use the same context menu as they do in the chat.

Comments upgrade

---

ui/component/router/view.jsx

Issue Number: #2550 
Setting timeout of 0ms seems to be enough to fix it. 
Don't know if best solution, page quite often loads as scrolled to top, and then instantly jumps to the wanted scroll position. (I think it used to load page to the wanted scroll position without the jump, but not sure)

Fix attempt - Restore scroll position in categories

---

ui/component/sideNavigation/view.jsx

Sometimes page loads for me looking like one in the screenshot. Sidebar categories are loaded, but only show when sidebar is expanded.
Don't fully understand why it happens, but this seems to fix it.
EDIT: Supposed to fix #966

Fix attempt - Sometimes blank side bar on page load

---

ui/modal/modalPublish/index.js
ui/modal/modalPublish/view.jsx

Supposed to fix publish form details getting cleared when previous upload finishes.
Noticed now that this was fixed at one point, but was reverted. I don't quite understand the reason, is it still up to date?
https://github.com/OdyseeTeam/odysee-frontend/commit/d2243f41972d78bbb961e0d4f7c88eb698cf76ca
Currently publish forms seem to always clear on entry in case that's related, so couldn't figure out why this would be needed anymore.

Fix attempt? - Don't clear publish form when previous file finishes uploading

---

flow-typed/Lbry.js
ui/component/claimListDiscover/view.jsx
ui/component/claimListHeader/style.scss
ui/component/claimListHeader/view.jsx
ui/scss/component/_main.scss

Allows filtering anonymous uploads in https://odysee.com/$/discover (tag search)
Not page wide setting since this also filters channel claims. 
This should otherwise be functional, but don't know what to do for UI(this was the only idea I had). Can you help @toshokanneko?

 Add option to hide anonymous on /$/discover

---

flow-typed/homepage.js
ui/component/app/index.js
ui/component/app/view.jsx
ui/component/homepageSelector/index.js
ui/component/homepageSelector/view.jsx
ui/component/settingAppearance/index.js
ui/component/settingAppearance/view.jsx
ui/component/settingUnauthenticated/index.js
ui/component/settingUnauthenticated/view.jsx
ui/index.jsx
ui/redux/actions/settings.js
ui/redux/selectors/settings.js
ui/util/homepages.js
web/src/getHomepageJSON.js
web/src/homepageApi.js

1. `existing` To retrieve full homepage dataset :
- https://odysee.com/$/api/content/v2/get
- <img width="370" alt="image" src="https://user-images.githubusercontent.com/64950861/222883568-001a648e-a292-45d6-80e3-fef4212d2caf.png">
2. `new` To retrieve a specific homepage :
- https://odysee.com/$/api/content/v2/get?hp=xx 
- _where `xx` = `en`, `fr`, `es`, etc..._
- The return object will still include the keys for all available homepages, but the values for unwanted homepages will be set to `null`. 
- The full key set will allow clients to generate drop-down lists without needing a different API.
- <img width="384" alt="image" src="https://user-images.githubusercontent.com/64950861/222883439-4f09788f-ec2e-488f-8bee-ec8d5d2c449d.png">
<details>
<summary>Expand...</summary>
<br>
Closes …

Support language specific `/$/content/get`

---

ui/component/livestreamScheduledInfo/index.js
ui/component/livestreamScheduledInfo/view.jsx

Use app language for date in here. (Had missed this one)

Use app language for the date in livestream overlay

---

ui/component/viewers/videoViewer/internal/chapters.jsx

Fixes:
Chapters where separator between the timestamp and the title was a tab didn't got detected.
Example:
This has no chapters in current version of Odysee.
https://odysee.com/@y:48/sup:b

Support chapters which have tab as separator (Timestamp\tTitle)

---

ui/redux/reducers/blocked.js
ui/util/lbryURI.js

Supposed to fix issue number: #2587
----- 
~Note:
Search acts bit strange if the same lbryUrl is in muted channels multiple times. Duplicated ones don't disappear when they should. (Had 4 times the DEADBUG Says in muted list)~
~Tested using `index` as a `key` in here, and above stopped from happening. But couldn't figure out a good way to make unique keys, so didn't do anything for it for now.  Guess this also pretty rare to happen.~
~In here -> https://github.com/OdyseeTeam/odysee-frontend/blob/master/ui/component/claimList/view.jsx#L442~

Fix attempt - Handle unmuting channels with ":" in url

---

ui/component/viewers/codeViewer.jsx

Ticket: Closes #2584
_Note that you still won't see it load due to an component bug -- that has been filed separatedly._
Webpack 5 changed how it handles ES6 modules by default, and here's a reminder:
> _Note that when using import() on ES6 modules you must reference the .default property as it's the actual module object that will be returned when the promise is resolved._
We probably don't need to be backward compatible with older webpack, but look for both syntax nonetheless.

Fix broken CodeMirror after webpack upgrade

---

package.json
yarn.lock

PR #2555 cleared the yarn lock.  This caused 2 plugins which are ready for videojs-8 (`^6 || ^7 || ^8`) to use 8.  This is bad because:
- We ended up packing both 7 and 8 in our app.
- Those 2 specific plugins are then built for 8 (although functionally the same, there might be build problems?).
1. Cleaned up the packaging. Use the `resolution` setting to upgrade from now, instead of surgically edit `yarn.lock`.
2. Upgraded from `7.21.2` to `7.21.4`, which brings in `http-streaming 2.16.2`.
- This is equivalent to `http-streaming 3.0.2` (meant for v8) and includes the same HLS buffer fix.  
- This may or may not fix the iPad problem.
- With that, we don't need to upgrade to v8, which doesn't make sense because plugins aren't caught up yet.
I've only tested locally because my dev instance …

Fix videojs package + upgrade to 7.21.4

---

ui/component/viewers/videoViewer/internal/videojs.jsx

As noted in 74450634, videojs dev says it can't populate what the system does not provide.
I think we just forgot that iPadOS exists.

Also use native VHS for iPad (patches 74450634)

---

web/component/adsSticky/index.js
web/component/adsSticky/view.jsx

Couldn't install blockers in BrowserStack, so had to disable by flag, but ads are still being loaded.
- `shouldShowAds` covers `locale`, so `locale` is not required. But `shouldShowAds` also looks at the user's GDPR answer -- is that why the logic was split?
- Fixed dependency.

Fix ads being loaded despite SHOW_ADS=false

---

ui/hocs/withStreamClaimRender/view.jsx

Closes #2624
We were seeing video urls with `..../undefined` being called, before the actual url is called later.
PR_2578 changed the "loading" if-block such that there is no final else-block, so the bottom code got executed and mounted the video player.
Based on the original code, it was just showing the spinner whenever there is no `fileInfo`, so I followed that logic.

Don't mount video until `get` is complete

---

ui/hocs/withStreamClaimRender/view.jsx

Reverts OdyseeTeam/odysee-frontend#2625
If a valid livestream is loaded from F5 (direct URL), it won't load.
The logic there needs to be more elaborate I guess

Revert "Don't mount video until `get` is complete"

---

ui/component/viewers/videoViewer/view.jsx

Play with "autoplay next" disable
1. Behavioral:
- If you press Shift+N while playing, the overlay incorrectly appears. 
2. Semantics
- `handlePlayNextUri` should only do what the name suggests -- injecting the overlay code there breaks the meaning and usage.
- `handlePlayNextUri` is passed to the "Next" and "Next-Shortcut" handlers -- it's weird that the overlay state permeated there, hence the behavioral bug above.

Fix recommendation-overlay semantics

---

ui/component/viewers/videoViewer/internal/videojs.jsx
ui/component/viewers/videoViewer/view.jsx
ui/hocs/withStreamClaimRender/view.jsx

`salt`
- Alleviate iOS autoplay-next permission issue by not using the Countdown screen. This then avoids the need to mute-and-play it.
- Just a temp workaround for a now until a better fix 
- [Fix undefined video url + code viewer not loading #2627](https://github.com/OdyseeTeam/odysee-frontend/pull/2627)
```
iOS scenarios that pauses autoplay
1. Playing the first video after F5 on homepage  [remains unfixed]
2. Clicking Next to play next rect               [workaround seems reliable]
3. Autoplay Next on end of video                 [workaround works 90%, fails sometimes]
----------------------------------------------------------
4. F5 on claim page (applies to all sites, a hard rule)
```

Fix: "undefined" URL | code viewer | iOS autoplay temp workaround

---

ui/component/viewers/videoViewer/internal/plugins/videojs-settings-menu/videojs-plus/Components/SettingMenu/Setting.scss
ui/scss/component/_file-render.scss

- Uses cog from packaged videojs-font font instead of copy-pasting another set of SVG.
- Removes the `div.vjs-setting-button` hack to handle mobile. Seems no longer needed after moving to font version.
- Fixes bounding area that was going off screen.
----
@toshokanneko, this is the cleanup I mentioned. 
<strike>I think the shifting issue no longer exists after this (?), but</strike> probably still needs the height adjustment that you mentioned.

Video: cog icon cleanup

---

ui/component/viewers/videoViewer/internal/chapters.jsx

I believe the issue is with `addTextTrack` not having cleanup counterparts + we are now recycling the video instance + the Safari implementation probably didn't handle it robustly.
Moved to `addRemoteTextTrack`, which the docs says it includes auto cleanup when the src changes. It is also the recommended API anyway as it comes with `removedRemoveTextTrack`, in case we ever need to manually clean things up.
Closes #2638

Fix safari-mac crash when moving from chaptered to non-chaptered video.

---

ui/component/claimPreview/view.jsx

Closes #2607
Undo a line introduced in [e1b13013](https://github.com/OdyseeTeam/odysee-frontend/commit/e1b13013bcb802a67b7daaf87aa2021ff9a8f1a2#diff-5f51ecc20c34db2478b2507e7e03c183dbca1eb3cec96fc46fe0ede1ef5210daR358-R361) (click and wait for auto scroll) that's causing the problem.
Logically, `shouldHide` can be because of `!claim` (among others), so adding a `claim` there doesn't make sense.
But it's unclear what the change was trying to fix (was squashed), so this could re-open some issues. But whatever that issue is, it'll require a different fix (separate if block)

Fix abandoned claims showing up in Recommended

---

static/app-strings.json
ui/component/channelSelector/internal/loading-selector.jsx
ui/component/channelSelector/view.jsx
ui/component/headerProfileMenuButton/index.js
ui/component/headerProfileMenuButton/view.jsx

Removes loading state from profile menu button. This prevented opening of profile menu when `channel_list` didn't return or was slow. 
Moved the logic to channel selector, so it shows some indication for channel list still loading.
NEW | OLD

Fix attempt - Always functional profile menu button

---

static/app-strings.json
ui/redux/actions/file.js

- The message is not localized.
- The long `uri` would be truncated anyway.
- "Please try again" does not help for access-related issues.
Relay the error message

Improve file::get error

---

ui/page/channelsFollowing/index.js
ui/page/channelsFollowing/view.jsx
ui/page/channelsFollowingDiscover/index.js
ui/page/channelsFollowingDiscover/view.jsx
ui/page/home/index.js
ui/page/home/view.jsx
ui/redux/actions/subscriptions.js
ui/redux/selectors/subscriptions.js
ui/util/buildHomepage.js
ui/util/url.js

Closes #2659 - Channel names with "*" causes issues.
```
export function splitBySeparator(uri: string) {
const protocolLength = 7;
return uri.startsWith('lbry://') ? uri.slice(protocolLength).split(/[#:*]/) : uri.split(/#:\*\$/);
}
```
This function splits * (on top of # and :), and was (recently?) being used to parse subscription uris. I think * is valid in channel names?
`parseUri` is expensive, and we constantly re-parse the subscription uris to get the IDs.
We should only need to parse it when `subscription` changes, so create a cached `selectSubscriptionIds` for that. Most components just want the IDs anyway.
So, we use `parseUri` instead of `splitBySeparator`, and only do it once.

Fix subscription claim_id parsing

---

flow-typed/publish.js
ui/component/publish/shared/publishReleaseDate/index.js
ui/component/publish/shared/publishReleaseDate/view.jsx
ui/component/publish/shared/publishStreamReleaseDate/view.jsx
ui/component/publish/upload/uploadForm/view.jsx
ui/modal/modalPublishPreview/view.jsx
ui/redux/actions/publish.js
ui/redux/reducers/publish.js
ui/scss/component/_form-field.scss

- Available in `salt` :salt: 
- SDK publish payload must remain identical.
- GUI changed a bit after the logic simplification, but nothing drastic.
- More love on scheduled livestreams would be nice.
Note that there is a bug where the app doesn't return you to the right page after editing.  Will address that separately.
Several updates in this area has introduce few variables that somewhat overlap each other, making it hard to tweak for upcoming visibility (public|unlisted) changes.
- Removed overlapping variables, and document how the current one should behave.
- `releaseTime` is now the only variable needed and represents the user-entered value.  If `undefined`, it means the user didn't set any, so use `Date.now()` for Create and past value for Edits (which we can get from the Claim …

Clean up release_time publish handling

---

ui/effects/use-lazy-loading.js

Lot of FreezeFrameLite errors in Sentry
This hook marks the the source as "loaded" without actually checking if it did, so FreezeFrameLite ended up operating on an invalid image.

useLazyLoading: on set srcLoaded if the file actually worked

---

ui/component/claimListDiscover/index.js
ui/component/claimListDiscover/view.jsx
ui/redux/selectors/blocked.js
ui/util/lbryURI.js
web/src/lbryURI.js

1. Using `splitBySeparator` to parse ID from uri will fail when the channel name contains `*`. Hunt down remaining uses.
2. Fix cached selector that wasn't set up properly. 
- If the slice itself is used as the input, it will pretty much always re-evaluate.
- Before (many calls...) :arrow_right: After (3 calls as expected -- f5, muted fetched, blocked fetched)
- <img width="200" alt="image" src="https://user-images.githubusercontent.com/64950861/232117221-05c33e8a-512f-465f-abd6-64c59de25569.png">  :arrow_right:  <img width="200" alt="after" src="https://user-images.githubusercontent.com/64950861/232117244-049a5f3f-a8d1-4b58-97f3-baae5ac2095a.png">

Hunt down splitBySeparator | Fix failed selector caching

---

ui/redux/actions/file.js

With this change, the view event fires when download is clicked.

count view on download

---

.devcontainer/devcontainer.json

This is usually there in the default codespace, but since we are using a customized one, we lost the functionality.
This is needed for Jetbrains Gateway.

Codespace: add sshd

---

ui/component/commentCreate/view.jsx
ui/page/claim/internal/claimPageComponent/view.jsx
ui/page/featuredChannels/view.jsx
ui/redux/actions/comments.js

Lots of Sentry errors from this unhandled error, which is usually just due to temp network glitch.
The root-cause is that `doFetchCreatorSettings` was changed to re-throw errors so that a shortcut `then/catch` can be done directly at the React component. 
Anti-pattern arguments aside, none of the callers actually handled the `catch` block, and in fact relied of the unhandled error as a means to stop the comment from being sent.
Always handle `catch` when there is a `then`. Display proper toast.

doFetchCreatorSettings: fix unhandled catch block

---

ui/hocs/withResolvedClaimRender/index.js

Wrong function used
Fixing this means creators can now see their own geo-restricted content. If that is not desired (i.e. want a blanket block of geo-restricted content), then edit the logic in the jsx.
An upcoming PR will require claimIsMine to be correct.

withResolvedClaimRender: fix claimIsMine always false

---

ui/page/portal/index.js

Closes #2685
Don't de-reference empty `user` object. Looks like the info is just used for internal purposes, so should be safe.

Fix portals crash when user/new fails

---

static/app-strings.json
ui/page/invited/internal/invited/view.jsx

Changes the text on invite pages like: https://odysee.com/$/invite/@odysee
The current one doesn't really make sense.

Make text on invite page less strange

---

ui/component/claimListDiscover/view.jsx
ui/component/claimTilesDiscover/view.jsx
ui/effects/use-resolve-pins.js
ui/page/home/view.jsx

Aside:  aren't pins supposed to appear in Category Pages (ClaimListDiscover) too on some filters?  Not seeing them despite seeing pins being processed.  Anyway, it's a different issue.

ClaimTileDiscover: guard against pinned IDs that lead to deleted claims

---

ui/component/claimListDiscover/view.jsx
ui/component/claimListHeader/view.jsx
ui/constants/claim_search.js
ui/util/claim-search.js

Closes #2690
`Test`: salt
@keikari, can you give it a test?

Fix `duration` being applied to non-AV `claim_search`

---

ui/page/playlists/internal/collectionsListMine/internal/collectionListHeader/index.jsx
ui/page/playlists/internal/collectionsListMine/view.jsx

Fixes this:
For some reason persisted order got always set to the previous sort order, instead of what it was switched to.
Steps to see the issue:
1. Go to https://odysee.com/$/playlists
2. Change playlist order twice (or once)
3. Go to home
4. Go to playlists
5. The order isn't what it was when left off.

Fix attempt - (Playlists) Keep `persistedOption` up to date with `sortOption`

---

ui/component/app/view.jsx
ui/component/publish/livestream/livestreamForm/view.jsx
ui/component/publish/post/postForm/view.jsx
ui/component/publish/upload/uploadForm/view.jsx
ui/component/publishBidField/view.jsx
ui/page/embedWrapper/index.js
ui/page/wallet/transactionListTableItem/view.jsx
ui/redux/actions/search.js
ui/util/lbryURI.js
ui/util/url.js
web/src/html.js
web/src/lbryURI.js

The typical usage of buildURI is to wrap it inside a try-catch or check the results with isURIValid.
New users typically don't know this, but previously we just warn using a console message.
After we moved to asserts, we have to disable asserts for those correct usages (already checking output), but continue to assert on the rest.

Improve buildURI assertions

---

flow-typed/livestream.js
ui/page/home/index.js
ui/page/home/view.jsx
ui/redux/reducers/livestream.js
ui/util/livestream.js

`Test:`  salt
```
getActiveLivestreamUrisForIds: (channelIds) => selectFilteredActiveLivestreamUris(state, channelIds),
```
1. The anonymous function in the prop construction causes this component to render on _any_ redux state change. This in turn triggers N lists of ClaimTileDiscovers, which is pretty heavy
<sub>_The amount of renders from changing Theme alone_</sub>
2. In the jsx code, `sortedRowData` is being looped several times for different pieces of data.
The anonymous function method was probably used as a workaround to pass the selector itself to the jsx so it can be re-used for each homepage row.
See commit message.

Fix excessive render in Home component

---

.flowconfig
flow-typed/npm/react-beautiful-dnd.js
ui/component/channelFinder/sortableList/view.jsx
ui/component/claimList/view.jsx
ui/component/collectionItemsList/view.jsx
ui/component/homepageSort/view.jsx

Add stub module so we don't have to add Flow suppressors when importing.
- Don't ignore the package so that types can be automatically inferred.
- Ignore 'raf-schd' instead (packaged used by dnd), since it's one level down. Shouldn't have happened, but not sure what's going on.
Addressed the Flow warning on 'style' potentially not the same type as what the code expects.
Also fixed mistake with useRef, where the object is being used instead `current`. 
Similarly handled 'style' like previous case. But for the bottom part of the code, I don't want to re-test all clients, so just suppressed the warning and added an assert to keep this a "flow only" change.

Flow: fix react-beautiful-dnd

---

ui/page/odyseeMembership/view.jsx

Kept seeing this in Sentry every once a while. Informed, but seems like still there.
There is no need to use that function in the first place.

Fix Object.fromEntries not supported in older browsers

---

ui/component/claimAuthor/index.js
ui/component/claimAuthor/view.jsx

- Not getting warnings on prop mistakes (e.g. typos, wrong types, missing props, extra props).
- When using the components, the IDE sometimes doesn't show autocomplete options for the props because the component goes through the `connect` HOC.
<details>
<summary>Details  :heavy_plus_sign: </summary>
1. In `view.jsx`: 
- Split the component `Props` into 3
- Each type must be 'exact', i.e. `{| ... |}`. 
- Export the client-facing `Prop`. The other two can remain local. 
``` 
export type Props = {| 
hideActions?: boolean, 
channelSubCount?: number, 
|};
type StateProps = {|
channelUri: string,
|};
type DispatchProps = {||};
```
- Combine these 3 when used in the component.
```
function ClaimAuthor(props: Props & StateProps & DispatchProps) {
```
2. In `index.js`: 
- Add `// @flow`. 
- Import …

Example: type-safety for Component props

---

flow-typed/claimSearch.js
ui/redux/actions/claims.js

`settings` shouldn't have a positive default value like `fetchStripeTransactions: true`, because the parameter is supposed to be a incremental addition of features.
For example, if I provide `settings = { autoPaginate: true }`, this indirectly makes `fetchStripeTransactions = false`, which doesn't make sense.
Since the current behavior is to fetch purchases ubiquitously, removed the optional setting for now. If there is a need, we can add a `noStripeFetch` in the future.
This should be a safe change since it also checks if the claim has any fiat tags before doing the additional fetch.

Fix doClaimSearch signature

---

ui/component/uriIndicator/index.js
ui/component/uriIndicator/view.jsx
ui/redux/selectors/memberships.js

The current component only uses the 'uri' prop to check for a bad uri. We can just use the claim instead.

clean up uriIndicator

---

flow-typed/content.js
flow-typed/videojs-hls-quality-selector.js
ui/component/viewers/videoViewer/internal/plugins/videojs-hls-quality-selector/ConcreteMenuItem.js
ui/component/viewers/videoViewer/internal/plugins/videojs-hls-quality-selector/plugin.js
ui/component/viewers/videoViewer/internal/videojs.jsx
ui/component/viewers/videoViewer/view.jsx
ui/constants/player.js

`Test:`  salt
1. Closes #2134
2. "Original (xxxP)" not updated correctly when moving from landscape to portrait (shorts) video.
Small steps to put things in the right place before we consider the abstraction layer.
See commit messages for details

QualitySelector: use latest states instead of the one during init

---

ui/component/viewers/videoViewer/internal/videojs.jsx

The previous attempt inadvertently forced it on for other browsers; should leave it untouched so it's the default, whatever that is (seems different for each browser).
Closes #2734

2nd attempt: disable nativeTextTracks for any Safari

---

ui/redux/actions/settings.js
web/index.js
web/middleware/app-strings.js

`Test:`  salt
Troublesome to test language-related changes when localhost and dev instances can't get the strings.
Not sure what happened that CORS'd it (maybe security-tightening).
Remove CORS for app-string files.

Disable CORS for app-strings

---

ui/redux/selectors/blocked.js
ui/redux/selectors/subscriptions.js
ui/util/container.js

@jessopb, would this help, or too verbose?
----
Primary: to provide a stable empty reference for props.
Secondary: to have some helpers for common queries like `isEmpty`, which usually requires verbose syntax like `Object.keys(x).length`
- The name "Collection" would be a better name to represent "Arrays and Objects", but that has been used for playlist claims.
- Dropped the word "Util" from "ContainerUtil" to keep things short.
- Flow did not like the overloaded function, so had to split into two

ContainerUtil - helper functions for arrays and objects

---

ui/page/signInVerify/view.jsx

Sometimes when using non-english language for Odysee, the signInVerify page is blank. This seemed to happen because language change reseted the `verificationTried` to the initial state(at least seemed to).
Steps to force the issue(running into it in normal use seemed to happen very randomly):
1. Be logged in
2. Open some old verification link in a new tab
3. See log in failed text
4. Change page language in the other tab
5. Login failed changed to blank page
Should be safe to merge, just a minor fix to something I wasn't aware of when making the changes to signInVerify page

Fix - Sometimes blank signInVerify page

---

static/app-strings.json
ui/component/comment/view.jsx

Changes:
-Mention "click to view"  in slimed comments
-Content owner's comments can't be slimed

Improvement attempt - slimed comments

---

ui/analytics.js
ui/analytics/apiLog.js

Closes [Fix extras/ dependency problem #764](https://github.com/OdyseeTeam/odysee-frontend/issues/764)
Add `analytics.log('blah')` inside `selectMutedAndBlockedChannelIds`.  The app doesn't load.
Lazy-load lbryinc so that the circular dependency doesn't interfere clients that uses `import analytics from 'analytics';`
Added a wrapper so that the existing calls don't need to change.

Add lbryinc lazy-loader to address circular dependency problem

---

ui/redux/reducers/claims.js

A mutable change was happening because `resolveDelta` returns the original state when the delta is empty. That is then directly being mutated.
Just like the rest, always change through the 'delta' object and resolve that last.

(patch fa3eea07) fix: playlist always loading

---

ui/component/commentsList/view.jsx
ui/redux/selectors/search.js
ui/util/redux-utils.js

`selectRecommendedContentForUri` is an expensive one that is doing multiple loops. Also, the memoization did not work because `claimsById` will be invalidated for every `claim_search` that happens.
Before:
After
1. Break the selector into several parts. - The blocklist-filtering should not be in the same selector as the re-sort one, since the former only needs to run once. - Add another part that saves the subset `claimsById` that we need.
2. Fix the `claimsById` invalidation problem by checking and memoizing the subset. - This is not efficient given that work is already done anyway, but looking at the overall flow, the amount of work saved later (in both Redux and React) makes it worthwhile.
1. Why always re-run the blocklist filtering?
- Hm ... I just retained the old logic. One benefit …

Fix memoization for Recommendations

---

ui/redux/selectors/claims.js
ui/redux/selectors/search.js

Closes #2637
e1b13013 removed the cost-by-uri map and the cleanup broke the meaning of the code here, since:
1. costInfo is an object, not number
2. it should be checking the cost of the recs, not itself
1. Use the new cost-by-id map.
2. Start removing unnecessary selectors that have no transformation (https://redux.js.org/usage/deriving-data-selectors#balance-selector-usage)

Fix autoplay-next looping between 2 claims

---

ui/component/publish/shared/publishName/view.jsx

`claim_search` was being sent for every character, making the typing super laggy
Throttle the query at 0.75s.
I think 1s also fine, but striking a balance between immediate update (showing error as fast as possible) and reducing calls.

PublishName: throttle input

---

extras/lbryinc/lbryio.js
ui/component/streamClaimRenderInline/view.jsx

#2784
Tried using prevProps in componentDidUpdate, but it didn't seem to work.
Fires view log on every PDF once, even while navigating during floating player.

fix view log duplicates

---

ui/component/claimMenuList/view.jsx
ui/component/socialShare/view.jsx
ui/util/url.js

Patch for #2794 -- just needed to split the calls.

Only use short-urls for unlisted claims.

---

ui/component/comment/index.js
ui/component/comment/view.jsx
ui/component/commentsList/index.js
ui/component/commentsList/view.jsx
ui/component/commentsReplies/index.js
ui/component/commentsReplies/view.jsx
ui/component/reportContent/view.jsx
ui/modal/modalRemoveComment/view.jsx
ui/page/ownComments/view.jsx

Sorry, I dislike major movements like these too, but type-safety is required for the upcoming optimization rework to find all usages.
This commit is primarily just:
- moving the prop types into their respective groups.
- fixing potential bad scenarios that Flow found.
- removing unused items that Flow found.

CommentView: add type-safety

---

ui/component/app/view.jsx
web/component/ad/adErrorBoundary.jsx
web/component/ad/index.js
web/component/ad/tileA/index.js
web/component/ad/tileA/view.jsx
web/component/ad/view.jsx

Closes #2833, `LBRY-DESKTOP-WEB-1AQS`
With the ad being a react component, any uncaught error will be treated like our own and crashes the site.
- Use error-boundary to capture and stop propagation of ad errors.
- Info will still go to Sentry, but the view will simply fallback to null and the rest of the site unaffected.

Prevent uncaught ad errors being treated as "crash"

---

ui/component/scheduledStreams/index.js

If blocklists come in late for example, the search results is `undefined` because we have a new query. But most of the time, the results are the same, causing unnecessary erasure.
Skip this update. Eventually, the results will either be [...] or null, which then a new render display the right results.
I couldn't figure out how to ensure type safety, so one must ensure new props are compared in `areEqual`

ScheduledStream: don't update when transitioning to a new search

---

web/component/ad/aboveComments/view.jsx
web/component/ad/tileB/view.jsx
web/component/ad/util/importPublir.jsx

The prior commit handles the React lifecycle errors. This one handles the js side
The `globalThis` issue, and potentially future others.
Lazy-load (but no code-split) the publir component. This allows us to catch js errors and fallback to nothing.

Don't crash from ad js errors

---

ui/page/channelsFollowing/index.js
ui/page/channelsFollowing/view.jsx

Same as 2700, where ScheduledStream is constantly rendering due to failed memoization of live uris.

Repeat PR_2700 for Following Page

---

flow-typed/publish.js
ui/redux/reducers/publish.js

`remoteFileUrl` was being purged internally when that happens, hence the graying out.
Verify that the active channel actually changed before purging.

Fix livestream form disabled when restriction is selected

---

ui/redux/reducers/publish.js

> https://odysee-workspace.slack.com/archives/C02G20Z2AEL/p1686002852804409 
When lapsed and trying to edit, the form will enforce setting a future date.
The ideas was to be explicit and make the form mean what it says, so when editing:
1. If no longer want it to be scheduled, set to Public to clear the error.
2. If want to schedule again (not sure if makes sense, but possible), correct the date.
Stop enforcing as suggested.

Stop enforcing "set to future date" on elapsed Scheduled claim

---

ui/redux/actions/comments.js

We repeatedly sign the active channel name when calling Commentron APIs.
- Create `ChannelSign` that wraps `Lbry.channel_sign` and provides simple caching functionality.
- Enable 30 minute cache for "own channel names".
- Other dynamic data like "comment message" and "claim ID" remains uncached.

Cache `channel_sign` for Commentron calls

---

ui/component/publishProtectedContent/index.js
ui/component/publishProtectedContent/view.jsx
ui/redux/selectors/memberships.js
ui/util/memberships.js

#2835
> Changing channel in form while restricted settings is expanded, allows selecting tiers with no "exclusive content" perk
Using vanilla JS in React leads to update issues like this.
But I understand why it was done that way -- the color of the tiers is tied to the css, which restricts how the elements need to be structured (i.e. `.checkbox` needs to be mounted but hidden, and next to each other). We also don't want to tweak FormField for something so specific, so it's an ok tradeoff.
Ideally, the color should be part of the membership object, not by how the HTML is structured.
But since the filtered array needs to be memo'd anyway, use that as a driver for the effect. Hopefully it's good enough to cover all cases.

Fix non-exclusive-content perks appearing in form

---

ui/redux/selectors/content.js

The prior change was causing LBC-gated claims to be auto purchased

(patch 35e274) Fine-tune mod access to avoid auto-payment

---

flow-typed/publish.js
static/app-strings.json
ui/component/publish/livestream/livestreamForm/index.js
ui/component/publish/livestream/livestreamForm/view.jsx
ui/component/publish/post/postForm/index.js
ui/component/publish/post/postForm/view.jsx
ui/component/publish/shared/publishFormErrors/index.js
ui/component/publish/shared/publishFormErrors/view.jsx
ui/component/publish/shared/publishPrice/index.js
ui/component/publish/shared/publishPrice/view.jsx
ui/component/publish/upload/uploadForm/index.js
ui/component/publish/upload/uploadForm/view.jsx
ui/component/publishProtectedContent/index.js
ui/component/publishProtectedContent/view.jsx
ui/modal/modalPublishPreview/index.js
ui/modal/modalPublishPreview/view.jsx
ui/redux/actions/memberships.js
ui/redux/actions/publish.js
ui/redux/reducers/publish.js
ui/redux/selectors/publish.js
ui/scss/component/_card.scss
ui/util/memberships.js
ui/util/publish.js

- `kp`
- `inf` = master reference w/ stripe test key (but note that transcoded videos won't play here)
- Closes #2835
- Incorrect error-gating when restrictions are toggled
- Ensure restriction is still valid when scenario changes (+ don't carry over invalid ones)
- Revert #2801 
- Default to `update_only` when editing Livestreams again (personal pref)
- Closes #2834 
- Closes #2421
- Fix restrictions not actually cleared when switched to Unlisted (although the backend still serves it as long as Unlisted key is present)
- Closes #2489

Restriction-related fixes

---

ui/redux/actions/publish.js

In Livestream Edit (create too), the return page is in a funky state with prior form values.
Since the 'success' path forces a navigation to the livestream page immediately (instead of letting the Success modal decide), the form needs to be cleared immediately.
The form is already sent, so there's nothing to retain (should be safe).

Publish: clear livestream form on success

---

ui/component/postEditor/index.js
ui/component/postEditor/view.jsx

#2907 - Post Editor laggy with huge articles
The classic problem with "controlled input" -- each character-change causes the component to render itself.
Work in "uncontrolled input" mode (which simpleMDE already does) + debounce the redux write.
This is just a band-aid, as there will still be stutter every now and then when the debounced function finally executes during idle (and user coincidently types again).
But at least the user can type now for 99% of the time.
The crux of the problem is the dependence on the `fileText` state. Try this:
1. There are 4 effects that fetches the post's data (if in Editing mode). Move this into a single redux action and store the outcome into `publish.postOriginalText`, and copy that into `publish.fileText` in `doPrepareEdit`.
2. In the component, use …

Band-aid: debounce Post Editor

---

ui/redux/actions/publish.js

Skips the additional `preview=true` publish to get the LBC estimate.
The modal will still appear if the user enables it in the Settings Page.

Publish: skip LBC cost query

---

ui/redux/actions/publish.js

- `inf`, or maybe wait for actual repro steps.
> <sub><i>Did get a complaint from a user who was unable to edit his livestream placeholder to a replay. It would tell him he has a duplicate claim, so it was sending a stream create vs an edit. Trying to repro how they are getting into that scenario, works normally for us otherwise.</i></sub>
Wasn't able to replicate, but if the issue is about `stream_create` vs. `stream_update`, then that narrows it down to a missing `claim_id` when creating the payload.
The use of `selectMyClaimForUri` to get the claim-being-edited has always been sketchy, since that depends network fetches and a ton of logic. Most likely it returned undefined here.
With recent changes, we are now storing `claimToEdit` in Redux and persisting it over F5. That object is …

Publish: attempt to handle replay name-clash failures

---

ui/page/discover/view.jsx
ui/page/home/view.jsx
ui/redux/selectors/livestream.js
ui/util/livestream.js

Livestreams: fixes related to 'excludedChannelIds'

---

ui/lbry.js

> _WARNING hub.herald.session:1285: Got an invalid query from ip, for not_channel_ids with more than 2048 elements._
This is most likely coming from a huge user muted/blocked-list.
Homepage data is another possibility, but we don't have anything that large today.
Limit `not_channel_ids` to 2047 (wasn't sure if it's inclusive of 2048).
Some of the blocked list will slip through, but at least the call doesn't fail. A more elaborate change would be required for a full fix, probably at the SDK side?

claim_search: handle blocklist limit

---

ui/component/comment/index.js
ui/component/comment/view.jsx

Closes #2934 
- `UriIndicator` will display the deleted channel name as "[Removed]".
- Comment text remains displayed.
#2554 (1f60d017) removed `UriIndicator` and tries to display the best channel name format based on `comment` object data, which is populated even if the channel was deleted.
I think there was a reason why we decided to show the comment instead of hiding it, but I can't recall. Maybe it's so that the Total shown tallies, or some pagination issue.
Anyway, just hide it for now as suggested in the ticket. If an issue is found, we can try to restore the old behavior.
****

Hide comments from deleted channels

---

ui/modal/modalRemoveAccount/thunk.js
ui/redux/actions/memberships.js
ui/redux/actions/user.js

Should fix/handle currently seen errors in `#internal-apis-desktop-errors`

Account deletion - minor fixes

---

web/src/routes.js

This addresses the deeper root-cause for the ChunkLoadError.
Requesting for an missing/invalid js file like `https://odysee.com/public/some-non-existent-file.js` yields HTML, which is usually incorrectly redirected to an actual claim, or the React soft-404 page.
Besides incorrect, it is also being cached.  Users are stuck until cache is manually cleared.
- In the final catch-all stage, try to detect if it's a file request and return a 404 instead.
- Do not cache 404s.  (Same reasons as https://community.cloudflare.com/t/404s-and-caching/337151. The file could eventually be corrected).
- The body is now "Resource not found".  I think we can add plain HTML (no redirect to claims) to beautify it, as long as the status is 404.  But not sure if it's worth it.
> [!WARNING]
> Is the detection …

Serve missing internal files as 404 instead of soft-404 page

---

ui/component/sideNavigation/index.js

- This restores the original behavior of the sidebar (starting off with "first 10 subs", and later with "last 10 active subs").
- I think the filtering method failed because of canonical vs. permanent uri reference -- should have tried both or use claim ID. Anyway, reverting for now.
The ability to remove deleted channel remains active in FollowingManage Page.

Sidebar: undo filtering attempt on deleted channels (revert.19f22b98)

---

web/src/rss.js

We can probably craft these manually again, will try that later (vs calling get)

use new v6 URL for rss

---

ui/component/commentCreate/view.jsx

Closes #2993
It was trying to prevent sending the comment when membership data is missing, say from fetch failures (hence the snack to reload). But the path for anonymous claims ended up in the same place

Fix inability to comment on Anonymous claims

---

ui/page/popoutChatWrapper/index.js
ui/page/popoutChatWrapper/view.jsx

Closes #2909
The popout is a separate instance (same as separate tabs), and the popout components aren't within any of the resolve HOCs, so the membership data had to be re-fetched.

PopoutChat: fix empty page on 'members-only livestreams'

---

ui/modal/modalRemoveAccount/view.jsx

Don't re-fetch account info, after deleting the account.
lint gave error about this, but noticed now that with non-empty dependency list, it will re-fetch the account info after the account is deleted.
(Not needed, and made "Loading account info..." spinner flash there looking odd.)

Account deletion: Only run useEffect at first render

---

ui/modal/modalRemoveAccount/view.jsx

Fixes:
The modal shows the `"Failed to load account info. If the issue persists, please reach out to help@odysee.com for support.'`-message instead of `'Account has already been queued for deletion.'`, for accounts that are already pending for deletion after a page refresh.

Minor fix to account deletion message logic

---

flow-typed/Lbry.js
ui/lbry.js

In 9b44b7eb, we added an artificial fetch timeout that's shorter than the browser's default so that (1) user don't have to wait too long (2) we get to differentiate the error as being a timeout (fetch errors all use the same string).
This commit provides the ability to specify list of methods that will bypass that mechanism (i.e. use browser's default timeout length. I think Firefox was like 90s), with `txo_list` being the first (known to be long, should just wait for it)
Test: `kp`

Add ability for methods to skip the artificial timeout

---

ui/component/publish/shared/publishStreamReleaseDate/view.jsx

Prevents behavior like this:
1. Current local time in here is 9:26
2. I set scheduled time to 11:26
3. I try to set scheduled time to 10:26, and it resets to 9:56 when I type the "1".  (Also happens if starting with "2")

Set scheduled stream DateTimePicker minDate by day instead of by time

---

ui/page/claim/internal/claimPageComponent/internal/channelPage/tabs/homeTab/internal/homeTabSection/index.js
ui/page/claim/internal/claimPageComponent/internal/channelPage/tabs/homeTab/internal/homeTabSection/view.jsx

Ticket: Closes #3015
Test:  `inf`
In Channel::Home tab, a Playlist row that contains playlists without a thumbnail should be showing the first claim's thumbnail instead.
- If ClaimListDiscover is used, it's supposed to handle the search part (which also covers the thumbnail fetch). Clients just pass in the params.
- The Home tab is handling the search instead, so some logic was missed.
Just mimic the missed logic for now.
There is an open ticket to make ClaimListDiscover to be more customizable/composible so that logic remains centralized, but that probably won't be happening soon. Ideas from https://www.youtube.com/watch?v=vot0nJJ2Qdo seem useful.

Channel::Home tab missing thumbnails

---

ui/redux/selectors/collections.js
ui/redux/selectors/publish.js

Editing item order of public(not edited) list, in the publish form, doesn't save on publish.
`unSavedEdits` weren't checked for in collection params creation.

Fix attempt - save public list order changes on publish

---

ui/component/claimMenuList/index.js
ui/component/claimMenuList/view.jsx

"Edit" used to only disappear from the menu after the claim had confirmed.

Minor fix - Don't show "Edit" on pending reposts.

---

ui/component/claimMenuList/index.js
ui/component/claimMenuList/view.jsx
ui/component/claimPreview/view.jsx

**Issue:**
Removing deleted items from private list is bit unclear on desktop, and not possible on mobile.
Also deleted content doesn't look that nice in the list.
**Changes:**
-Make deleted content look similar to existing content
-Show 3-dot menu for deleted content for clearer deletion option
<details>
<summary>OLD vs NEW mobile:</summary>
</details>
<details>
<summary>OLD vs NEW desktop:</summary>
</details>

Fix attempt - Removal of deleted content from private list

---

static/app-strings.json
ui/component/userVerify/view.jsx

Change of data in the verification request card for Discord.

Correction and redirection

---

static/app-strings.json
ui/page/ownComments/view.jsx

User complained about loading own comments "hanging".  It took ~30s on their account.
Now loading long would look like this:  
https://github.com/OdyseeTeam/odysee-frontend/assets/34790748/c076a2bc-baba-4322-be61-f6007fef42e3

Show a message if loading own comments is taking >10s

---

flow-typed/notification.js
ui/page/notifications/view.jsx
ui/redux/reducers/notifications.js

Fixes:
Deleting notification in some other category than "All" didn't delete the item on the UI. (Needed to wait a min and then trigger re-fetching of notifications for it to disappear.)

Improve notification deletion

---

ui/component/viewers/videoViewer/view.jsx

Issue Number: #2895 
New behavior:
-queue pauses playing on end of the last video
-the second item from the queue doesn't start playing in middle of other playlists
Seems that a second `onVideoEnded` function gets attached to the player, when a second queue item is added. (Doesn't happen with following video adds)  
And one of those sticked around, and got called when not wanted. (I didn't quite understood how this exactly worked.)
Clearing `onEnded`s before adding a new one, seems to fix the behavior.
Also clearing them didn't seem to break anything. Looping and shuffle also kept working the same than before.

Fix attempt - Issue #2895 

---

ui/modal/modalRemoveAccount/index.js
ui/modal/modalRemoveAccount/view.jsx
ui/modal/modalRevokeClaim/index.js
ui/modal/modalRevokeClaim/view.jsx
ui/redux/selectors/user.js

-Show warning about synced channels on account deletion, if user has any synced channels
-On channel deletion, don't show the warning about synced channels, if user doesn't have any synced channels
-`selectHasYoutubeChannels`  used to always return `true` due to it working previously like this: `Number.isInteger(youtubeChannels?.length)` (returned `true` for an array with length of 0)
<details>
<summary>Channel deletion warning images:</summary>
</details>
---------
Changing the `selectHasYoutubeChannels` to return  `false`, when account doesn't have any connected YouTube channels, changes how the empty channel page looks.
<details>
<summary>Images:</summary>
OLD:
NEW:
</details>

Improve sync deletion warnings

---

ui/redux/actions/claims.js

Purchased fiat items in private lists didn't appeared as purchased, unless manually navigating to them.
-had fee info on thumbnail
-on auto-play showed "Purchase" overlay
---------------
Copy/pasted the fiat stuff from `doClaimSearch` to `doResolveUris`, seems to  work.

Check if fiat items from `doResolveUris` are purchased

---

ui/redux/actions/collections.js

Collection items randomly disappearing when editing public list. 
Assuming it happens due to there being no check if collection items have resolved before doing the edit. And if there were items still resolving, those would get deleted. (I think)
Not sure how to repro the issue exactly, but comment in the code suggests this being the case `// The resolve calls will NOT return items when they still are in a previous call's 'Processing' state.`  
So added a check for collection items being resolved, and updated the fetching to handle cases of deleted claims. 
*Note:*
Missing still proper error messaging, currently just shows error pop-up asking to try again.

Prevent editing collection while all items aren't resolved

---

ui/redux/actions/collections.js

List editing issues created by https://github.com/OdyseeTeam/odysee-frontend/pull/3061
-Allow editing private/edited lists, no matter if items were resolved or not (urls are already known, so items won't disappear, I think)
-Public list with 0 items can get considered as successfully resolved now (This caused issues if all list items were deleted.)
-Minor changes to checking for resolving items. Also noticed some items getting stuck in `resolvingUris`, shouldn't matter for this due to private/edited lists are now allowed being edited always. (I wasn't able to figure out why those were stuck, or how to clear without clearing anything unwanted)

Fix the new list editing isuses

---

ui/component/comment/view.jsx
ui/component/commentReactions/index.js
ui/component/commentReactions/view.jsx
ui/component/fileActions/index.js
ui/component/fileActions/view.jsx
ui/component/notification/view.jsx
ui/constants/tags.js

Allows disabling reactions for channel's content/comments with tag `c:disable-reactions-all`, and for content only with `c:disable-reactions-video`
*Note:*
Currently creator likes are still always allowed with this(?)

Allow disabling reactions with a tag

---

ui/component/comment/view.jsx
ui/component/commentReactions/index.js
ui/component/notification/view.jsx

Allow disabling reactions on all comments on own content, instead of own comments in other's content

Fix - disable reactions in comments

---

static/app-strings.json
ui/component/channelEdit/view.jsx
ui/component/tagsSearch/view.jsx
ui/constants/tags.js

-Show control tags for all
-Show control tags on channel page
-Move `PREFERENCE_EMBED` tag from `CONTROL_TAGS` to `INTERNAL_TAGS` 
-Custom labels for some control tags

Show control tags

---

ui/redux/selectors/collections.js

Private list with unpublished edits wasn't actually considered private. So if editing in publishing form, would cause submit  to try to do `collectionUpdate`.
Fix:
Copied the related stuff from `selectHasPrivateCollectionForId` to `selectIsCollectionPrivateForId`, just left out the checks for private versions of published lists.
Didn't test much, but don't really see how this could cause any surprises. (Unpublished collections only has the actually private lists)

Fix `selectIsCollectionPrivateForId`

---

flow-typed/Claims.js
ui/redux/actions/collections.js
ui/redux/reducers/claims.js
ui/redux/selectors/claims.js

If `claim_search` on list edit failed (timed out or other reason), the items in the list would get wiped. 
Added something to keep track of failed resolves.

Don't wipe list items on edit when claim_search fails

---

flow-typed/Lbry.js
static/app-strings.json
ui/component/claimListDiscover/view.jsx
ui/component/claimTilesDiscover/index.js
ui/component/settingContent/index.js
ui/component/settingContent/view.jsx
ui/constants/search.js
ui/constants/settings.js
ui/page/claim/internal/claimPageComponent/internal/channelPage/tabs/contentTab/index.js
ui/page/claim/internal/claimPageComponent/internal/channelPage/tabs/contentTab/internal/searchResults.jsx
ui/page/claim/internal/claimPageComponent/internal/channelPage/tabs/contentTab/view.jsx
ui/page/claim/internal/claimPageComponent/internal/channelPage/tabs/homeTab/internal/homeTabSection/index.js
ui/util/claim-search.js
ui/util/query-params.js

Adds a setting to filter out content <1min
If claim_search or lighthouse query may return results with duration, and the setting is enabled, the duration filter gets added to the query.  
Searching specifically channels/collection/etc. will still work, but these get excluded in more general queries while the setting is enabled.   
Also if  `claim_ids` is set the duration limit is skipped. (Think it's only used with collection items.)  
Also setting the duration to something else than "any", will override the setting.

Hide shorts setting

---

ui/redux/actions/comments.js
ui/redux/reducers/comments.js

Commentron all ready supported creating the channel entry on `setting.Get`, but it needed a channel name to be also passed in the request.  
https://github.com/OdyseeTeam/commentron/blob/8aa1adca3464a4ddbf4b39ab37d8ce514554034c/server/services/v2/settings/service.go#L46-L61
This seems to work now.
Also hometab sections will be blank again when there is an error, as now it should be a real error.

Create channel entry with `setting.get`

---

ui/component/viewers/videoViewer/index.js
ui/component/viewers/videoViewer/internal/videojs.jsx
ui/component/viewers/videoViewer/view.jsx

Disable "save video as" option for content with disabled downloads

---

ui/page/fileListPublished/index.js
ui/page/fileListPublished/internal/fileListHeader/internal/rightSideActions/view.jsx
ui/page/fileListPublished/view.jsx
ui/redux/actions/claims.js

Only appears if account has >1 channels
Works with claim_search and with both claim_lists.

Channel filter on uplaods page

---

static/app-strings.json
ui/page/creatorMemberships/supporterArea/pledgesTab/view.jsx
ui/redux/selectors/memberships.js

Prevents access to membership content, if the subscription status is "past_due" (Payment failed)
Has issue that if canceling membership in that state changes the status to "cancelled", it would allow access again. Don't see how to detect if it was cancelled past_due or while active

Handle past_due membership status

---

ui/component/commentsList/view.jsx

#2428 
#2912
Seems like the comment thread was just forgotten to be added to the top of the comment list. Just adding it seems to make it work great!
Example from a recent user complaint
https://odysee.com/@timcast:c/bill-maher-doesn't-understand-the:3?lc=6169df3e39c416ff8a786b738c178b7084261fac033c199389aace50cdf0166a&tc=6169df3e39c416ff8a786b738c178b7084261fac033c199389aace50cdf0166a
<details>
<summary>Images</summary>
Before: 
After:  
</details>

Fix comment threads

---

ui/scss/component/_comments.scss

Cap image height in comments

---

ui/component/recommendedContent/index.js
ui/component/recommendedContent/view.jsx
ui/component/sideNavigation/view.jsx
ui/page/claim/internal/claimPageComponent/internal/channelPage/tabs/contentTab/index.js
ui/page/claim/internal/claimPageComponent/internal/channelPage/tabs/contentTab/view.jsx
ui/page/claim/internal/claimPageComponent/internal/channelPage/tabs/homeTab/internal/homeTabSection/index.js
ui/page/claim/internal/claimPageComponent/internal/channelPage/tabs/homeTab/internal/homeTabSection/view.jsx
ui/page/claim/internal/claimPageComponent/internal/streamClaimPage/internal/markdownPost/index.js
ui/page/claim/internal/claimPageComponent/internal/streamClaimPage/internal/markdownPost/view.jsx
ui/page/claim/internal/claimPageComponent/internal/streamClaimPage/internal/videoPlayers/index.js
ui/page/claim/internal/claimPageComponent/internal/streamClaimPage/internal/videoPlayers/view.jsx
ui/page/home/index.js
ui/page/home/view.jsx
ui/page/portal/index.js
ui/page/portal/view.jsx
ui/page/search/index.js
ui/page/search/view.jsx

Remove ad injections & premium checks

---

ui/component/viewers/videoViewer/internal/plugins/videojs-http-streaming--override/playlist-selectors.js

Smooth out fluctuations in player bandwidth estimate

---

ui/modal/modalRevokeClaim/view.jsx

In channel deletion these didn't match before:
@ArsecioMúsicaCristiana <-- ú takes one backspace to remove
@ArsecioMúsicaCristiana <-- ú takes two backspaces to remove

Normalize special letters in channel deletion name string

---

ui/component/claimPreviewTile/view.jsx
ui/component/viewers/videoViewer/view.jsx
ui/scss/component/_file-render.scss

Allow right clicking of the items in the video end recommended content overlay, so they can be opened to new tabs.

Allow opening content in recommended overlay to new tabs - attempt

---

ui/component/claimListDiscover/view.jsx
ui/component/homepageSort/view.jsx
ui/component/router/view.jsx
ui/component/upcomingClaims/view.jsx
ui/constants/claim_search.js
ui/page/channelsFollowingDiscover/index.js
ui/page/channelsFollowingDiscover/view.jsx
ui/redux/selectors/settings.js

Sort channels on discover page by creation time, and from a wider categorized list. First run will stay the same. 
Later we can add some pins

New Channel discovery improvements

---

ui/page/collection/internal/collectionHeader/internal/collectionHeaderActions/view.jsx

Someone asked about LBC supporting playlist, and happened to notice that Support-button is missing on own playlist for some reason.

Don't hide "Support" button on own playlists

---

ui/redux/actions/comments.js

For last 100 commented claims, store the first commenter channel info. From that point on, only that channel can comment on the claim.

Track deleted channels locally to help with comment spam

---

ui/component/textareaWithSuggestions/render-input.jsx

Limits mobile comment input to 15 rows.
OLD: No row limit, long comment kind of breaks the UX
NEW: Should be better

Fix mobile comment input (went out of screen)

---

ui/modal/modalBlockChannel/view.jsx

User complaint. Says that "Block" being close to "Reply" can cause annoying accidental blocks. 
Would now show modal also for just personal blocks.

Show block confirmation modal for personal blocks

---

static/app-strings.json
ui/page/help/view.jsx

The "Email Us" button in same cases fails open the email app.   Some user had trouble finding the email, thought it's shown on the page.  
Since user feedback is now easy to track, added a mention that it can also be used for email change requests.

Let users know that "Submit Feedback" can be used for email change

---

ui/component/commentCreate/view.jsx
ui/component/walletTipAmountSelector/view.jsx

OLD:
NEW (removes the warning from comment tips):

Don't show "tip not sent with comment" warning, when it's sent with a tip

---

ui/component/channelEdit/view.jsx
ui/component/tagsSearch/view.jsx
ui/constants/tags.js
ui/page/claim/internal/claimPageComponent/internal/streamClaimPage/index.js
ui/page/claim/internal/claimPageComponent/internal/streamClaimPage/internal/markdownPost/index.js
ui/page/claim/internal/claimPageComponent/internal/streamClaimPage/internal/markdownPost/view.jsx
ui/page/claim/internal/claimPageComponent/internal/streamClaimPage/internal/videoPlayers/index.js
ui/page/claim/internal/claimPageComponent/internal/streamClaimPage/internal/videoPlayers/view.jsx
ui/page/claim/internal/claimPageComponent/internal/streamClaimPage/view.jsx
ui/redux/selectors/livestream.js

Adds `c:disable-comments` control tag.
Should handle:
-videos
-markdowns
-other-stream-claims
-livestream chat
The disable comments option is filtered from channel page to not cause confusion with the existing setting. 
*Note:*
I wanted to just create `selectCommentsDisabledForUri` selector, but for some reason importing this in `redux/selectors/claims` breaks things:  
`import { selectCommentsDisabledSettingForChannelId } from 'redux/selectors/comments';`
Couldn't figure out why. So instead just added the tag check separately to places where needed.
<details>
<summary>Error</summary>
</details>

Add `c:disable-comments` control tag

---

ui/page/channels/index.js
ui/page/channels/view.jsx

-removes "Earnings per view" from channel preview

Remove view rewards

---

static/app-strings.json
ui/component/IframeReact/view.jsx

Show nicer error if pdf fails to load

---

ui/redux/actions/app.js
ui/redux/selectors/collections.js

Fetch public lists on app launch.
Check if item is in lists also with claimId, in case of public list.
Also removed duplicate:
```
selectMyPublicLocalCollections,
selectMyPublicLocalCollections,
```
Based on variable names/amount it looks like it wasn't intentional.

Fix: Video not showing as "Saved" if in public list

---

ui/page/collection/internal/collectionActions/index.js
ui/page/collection/internal/collectionActions/internal/sortButton/index.js
ui/page/collection/internal/collectionActions/internal/sortButton/view.jsx
ui/page/collection/internal/collectionActions/view.jsx
ui/page/collection/internal/collectionPublishForm/view.jsx

Fixes #3193 
Couldn't figure out how to align it right like it's in Arrange-mode, but okay like this?

Playlist sort button to edit

---

ui/page/collection/internal/collectionActions/internal/publishButton/view.jsx
ui/page/collection/internal/collectionHeader/internal/collectionHeaderActions/view.jsx

*Issue:* Arrange mode doesn't get disabled when entering Publish/Edit page, and would confusingly still be toggled on when returning from those pages. 
*Fix:* Disabling Publish/Edit button/option until user has exited arrange-mode.  
(Don't want to auto handle it when exiting Publish/Edit, as the Cancelling in those would also clear possible unsaved changes that were done in arrange mode.)
Makes arrange-mode look like this:

Prevent playlist publish/edit while in arrange mode

---

static/app-strings.json
ui/page/settingsStripeAccount/view.jsx

Allows user to see bank account being connected, even if the charges haven't yet been enabled.   
(Other pages will still continue to show "Bank accounts disabled" error at this state.)

Allow viewing account on Stripe even if charges are disabled

---

ui/component/tag/view.jsx

Fixes #3192 
Not sure how make a note so it won't be just more confusing.  Ok to just highlight usage of mature word for now?

Highlight tag if it contains mature word

---

ui/page/home/helper.jsx

Fixes this blank page when there are no categories. For non-premium users there was an invisible FYP which still counted as a homepage row.
Now would look like this also in those cases.

Don't push invisible `FYP` in homepage (affected non-premium users)

---

ui/component/publish/shared/publishBid/view.jsx
ui/page/collection/internal/collectionPublishForm/internal/collectionGeneralTab/internal/additionalOptions/view.jsx

If old bid on claim is less than `MINIMUM_PUBLISH_BID`, auto increase it. 
Handles playlists and uploads.
Channels seem to be fine with too low bid when it's not changed, so left it as is.

Auto increase bid to minimum

---

ui/component/viewers/videoViewer/internal/videojs.jsx

If source/m3u8-redirect response status >= 400, use original quality.
Also log error if status code >= 400.

Default to original version if playlist fetch gives issues + log error

---

ui/redux/actions/user.js

Missed that >400 responses probably throw an error with `res.json()`. This should handle that.

Actually allow playing videos if api down

---

flow-typed/Comment.js
ui/component/commentCreate/view.jsx
ui/redux/actions/comments.js

Handles the multiple channels error, and should also handle other possible comment creation errors caused by front end.

DryRun the comment creation before submitting the tip

---

ui/component/viewers/videoViewer/internal/videojs-events.jsx

Noticed infinite looping with retry attempts on this video.
(User didn't mentioned about looping, just about the crashing itself. Saw it here in FF/Brave, so maybe device specific?)
EDIT:  Looping seems to not happen if auto play is disabled in browser
Now it would only reset the attempts if the current time actually changes when the video is "playing". 
The reset that happened on "play" also caused looping.
Currently happens when skipping to around 30mins in this video. Think the upload is corrupted in the middle.
https://odysee.com/@%D9%85%D8%B1%D9%83%D8%B2_%D8%A7%D9%84%D8%B2%D9%87%D8%B1%D8%A7%D8%A1_%D8%B9%D9%84%D9%8A%D9%87%D8%A7_%D8%A7%D9%84%D8%B3%D9%84%D8%A7%D9%85:3/2025-01-22-%D8%B3%D9%88%D8%B1%D8%A9-%D8%A7%D9%84%D9%83%D9%87%D9%81-%D8%A7%D9%84%D8%B1%D8%AC%D8%A7%D9%84-%D8%A7%D9%84%D9%8 …

Only reset player recoveryAttempts if video really started to play

---

ui/component/commentCreate/view.jsx
ui/component/walletSendTip/view.jsx

On mobile changing the hyperchat currency in the tipping modal didn't affected the currency of the actual tip.

Fix tip currency change on mobile hyperchats

---

flow-typed/stripe.js
ui/component/walletBalance/index.js
ui/component/walletBalance/view.jsx
ui/modal/modalArweaveConnect/index.js
ui/modal/modalArweaveConnect/view.jsx
ui/page/paymentAccount/index.js
ui/redux/actions/arwallet.js
ui/redux/actions/stripe.js
ui/redux/selectors/stripe.js

Renamed some selectors
Moved to checking for *default* wallet rather than "active" since many can be active.
Disabled clicking out of the connect modal.

Connect modal

---

ui/component/embedTextArea/view.jsx
ui/util/web.js
web/src/oEmbed.js

This claim generated an iframe code which had some issues on hugo
https://odysee.com/@GoodGodFather:d/Normie's-Guide-to-Satanism:7
Also using the the generated iframe src in address bar gave same error (but worked in embed outside of hugo)
https://odysee.com/$/embed/@GoodGodFather:d/Normie&#039;s-Guide-to-Satanism:7
Changed iframes to use encodedURL
New src would look like this: https://odysee.com/%24/embed/%40GoodGodFather%3Ad%2FNormie%27s-Guide-to-Satanism%3A7

Use encodeUri in iframe embeds

---

ui/component/commentCreate/view.jsx

Fixes this:
https://discord.com/channels/721806979928162404/914205457864880209/1347755826181443725
The `activeTab` doesn't get unset after it has been set once, so amount was getting passed for free comments too, and that didn't work with the commentron updates.

Fix free comments not working after hyperchat

---

ui/component/fileActions/index.js
ui/component/fileActions/view.jsx

Adds download button to these:
- paid content, if it has been purchased (Renting doesn't show download button)
- membership content, if joined to membership
- unlisted/private content

Show download button for purchased/membership/unlisted content

---

ui/page/livestreamSetup/view.jsx

This was only shown on "Setup" tab before, now on both.
Note: `disabled` isn't actually used in `LivestreamForm`, so went with just not showing the form if no channels.

No channel, no livestreams

---

ui/redux/actions/collections.js
ui/util/collections.js

-Pending collections temporarily lost their timestamps, making them appear at the bottom in some sorts. -> Filled in the timestamps.
-Sorting of claims in "Save to..." broke if there were nameless collections. -> Defaults to claim name when title is missing.

Minor collection fixes

---

ui/component/supportsLiquidate/view.jsx
ui/redux/actions/wallet.js

The slider in here didn't work at all. It had the percentages and the actual amount mixed up. And the text input didn't worked well with decimals.  
Now they should work like expected.  
Also added some toast message to tip unlock success/fail.. There was no feedback on success before.

Fix tip unlock

---

static/app-strings.json
ui/component/commentCreate/view.jsx

When user tries to comment without a channel, show this modal. (It used to re-direct to channel creations with no info.)

Add channel required to comment info

---

static/app-strings.json
ui/component/previewOverlayProtectedContent/index.js
ui/component/previewOverlayProtectedContent/view.jsx
ui/hocs/withStreamClaimRender/internal/protectedContentOverlay/view.jsx
ui/redux/actions/claims.js
ui/redux/actions/memberships.js
ui/redux/actions/publish.js
ui/redux/reducers/memberships.js
ui/redux/selectors/memberships.js

-If content has `c:membership` tag, show the membership overlay, even if no tiers, and also for the creator. (If it has tiers, it will show just the green lock for the creator like before)  
-Fix claimIds with no tiers getting stuck in fetching state (basically there was only one tier check per page load, if it wasn't returned on first try)  
-Show toast error if failed to apply membership tiers. (Only made it show on apply for now, so it won't error every time user just moves content to a different channel, since it makes empty modify call in those cases too)  
Now shows this "Waiting tier info..." text if tiers aren't fetched, so it doesn't confuse creators as much just after the upload, but still catches attention if it doesn't go away after a while.

Minor fixes/clarification to some membership issues

---

ui/page/fileListPublished/internal/fileListHeader/view.jsx
ui/scss/component/_claim-search.scss

Using smaller font size on uploads page filter buttons on mobile.
User reported issue https://discord.com/channels/721806979928162404/1412154396820639886/1412154396820639886
Should still be legible enough

Improve upload filter buttons fit on mobile

---

ui/util/url.js

Fixes YouTube comment / link breaking when sharing Odysee links containing an "@". Only fixes from within share modal.
Sharing modal uses "@"
Sharing modal uses url encoded "%40" instead of "@". Fixes broken Youtube links. 
Response to reports that links to Odysee from Youtube are broken. Confirmed that reason for this was inability to handle "@" within a URL. Encoding as "%40" fixes. 
</details>

fix: url encoding for "@" to ensure YouTube compatibility
